### ISSUE TITLE
Collaborator Summit Vancouver 2018 - Call for Sessions and Agenda - October 12th and 13th 2018.

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#100]
## Update: Per [suggestion](https://github.com/nodejs/summit/issues/100#issuecomment-422465874) and related #104, the agenda is being [maintained here](https://github.com/nodejs/summit/blob/master/2018-10-Vancouver/agenda.md) now. Please make a PR to it for changes 🙌🏽

# Collaborator Summit Vancouver 2018 - October 12th and 13th 2018

We are back with the date for the Node.js Collaborator Summit in Vancouver next to JS Interactive (which is on October 10th and 11th, 2018).
This is a live issue that will be constantly updated to match the proposed agenda.

> __Vancouver Convention Centre West Building__
1055 Canada Place
Vancouver, British Columbia V6C 0C3
Canada

## Agenda

The updated agenda is available at [here](https://github.com/nodejs/summit/blob/master/2018-10-Vancouver/agenda.md). Send PRs for updates.

## Attendance

Anyone can come, but we will not be explicitly onboarding at Collab 
Summit Vancouver. Conversations can move fast as working groups have 
a lot of context. Unlike the Spring instance of the Collab Summit, this Fall instance includes a morning of Code + Learn. The Code + Learn session guides people through contributing to the project, prior to congregating for the Summit.

Working groups will put together a brief schedule so that people can 
familiarize themselves before folks get onsite, having the general collaborator 
discussions, and then dive into breakout sessions.

Atteneeds must register at: https://www.regonline.com/?eventID=2152653&rTypeID=511098
Access code: COLLABSUMMITONLY

## Working groups in attendance

We'd love to know ahead who will be represented. Filing issues in this repo is helpful for discussion particular to a working group and how they'd like to manage their time. Linking to that here would be great! We're working on creating a Projects Board to post times for this on the conf agenda so people are aware of when a WG meets and can maybe get a break, if needed. We'll be looking at issues filed in this repo titled "Berlin: working group something something" to add these below as well.  
- Working group that will be at Collaboration Summit
  - Name of contact @github-handle
  - link to working group planning issue
  - Any extra requests(space during conf, av/sound, etc.)
  
## Travel Fund
There are funds available for any Individual Member of the Node.js Foundation to receive travel funds to Collab Summit.  Membership is free for active collaborators. Sign up [HERE](https://github.com/nodejs/members#members).

PLEASE follow the instructions for application to receive travel funds [HERE](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#process).

  
------------------------
  
@nodejs/collaborators @nodejs/tsc @nodejs/community-committee 

We should figure out what topics we want to cover. 
We think we will be best served with some monotrack presentations and discussions in the first day, and then breakout rooms in the second day. __We can change everything__, so if you think a better structure will suit us better, let us know! 
It would be fantastic if each one of the breakouts is facilitated by someone who will be responsible to "run" the breakout and do a quick presentation at the end. This person would also set some outcomes from the breakout so we leverage our time together in the best possible ways.

**Comment by chowdhurian** [comment]
Issue #100!

**Comment by yunong** [comment]
Would love to talk about diagnostics, tiers of support for tooling, HTTP/2 performance, and promises debugging. cc @misterdjules @hekike

**Comment by mhdawson** [comment]
The security-wg will want a session, proposal will be built here: https://github.com/nodejs/security-wg/issues/358

**Comment by bnb** [comment]
Would love to see a few sessions:

- @nodejs/i18n 
- @nodejs/website-redesign 
- @nodejs/community-committee

**Comment by mcollina** [comment]
We should definitely have

* @nodejs/promises-debugging cc @benjamingr 
* @nodejs/streams (I can run this together with @mafintosh)
* @nodejs/diagnostics 

And a few other suspect.

**Comment by joyeecheung** [comment]
For this collab summit I'd really love to see interactive sessions that are different from the previous discussions/talks format - the talks and discussions are great but sometimes we are more effective on GitHub and are just going to throw topics back to GitHub.

A few ideas we have discussed in May:

- Tour of V8 API/core architecture/internal C++/subsystems that need more love (to train more reviewers for those PRs)
- A hackathon to fix CI flakes
- Tools and tricks that people use to debug core (e.g. gdb/lldb, llnode, inspector, git stuff)

**Comment by chowdhurian** [comment]
From a logistical perspective, it would be **amazing** to have proposals in by the end of August, a month from now. That timeframe would be very helpful for scheduling.

Here's a possible template.

***

## Title (this goes as your issue title)

Summit Topic: _topic_ – _what will be covered_

## Motivation/Abstract

_Context_

## Agenda

It can be very helpful to have an agenda included in the proposal. The agenda can be just an empty placeholder to start; as the discussion progresses, items can be added, and finalized closer to the date of the Summit!

***

Can't wait to see y'all in Vancouver! 🎉🎉🎉 Feel free to use the following past proposals as inspiration! Remix away.

#71: Agenda for Diagnostics session at collaborator summit
#62: WebAssembly
#89: Summit Topic: Website Redesign – Content Creation

**Comment by hashseed** [comment]
Okay here goes:

**Title**: Release schedules and bisection
**Abstract**: V8/Chrome and Node.js release at different cadences, so it often becomes confusing when a new feature implemented in V8 will end up in Node.js. Conversely, bisecting issues introduced in V8 is not straightforward either. I would like to demystify release schedules and give a walkthrough on bisecting into V8.

Another one, if there is interest:
**Title**: gdb with V8
**Abstract**: Debugging V8 is not for the faint-hearted. I would like to show some tips, tricks, and techniques to gain insight into a live V8 process with gdb.

**Comment by yunong** [comment]
Did the dates change? I recall that the summit was ending on the 12th and so I booked my flight out on the 13th :(. Can we schedule the sessions for promises debugging and diagnostics on the 12th?

**Comment by joyeecheung** [comment]
@yunong The summit is going to be on 12th (afternoon-only) and 13th, I think the JSI website listed the dates as 10th-12th because technically the programs for non-Node.js-collaborators ends on 12th (code-and-learn in the morning). They don't include the summits, because technically the summits are separate from JSI.

**Comment by mcollina** [comment]
I’ll do my best to schedule those two sessions on day 1.

**Comment by yunong** [comment]
Thanks @mcollina !

**Comment by apapirovski** [comment]
> Tour of V8 API/core architecture/internal C++/subsystems that need more love (to train more reviewers for those PRs)

Some of these could likely be lightning talks. I know I could cover e.g., timers in like 5-10min.

**Comment by codebytere** [comment]
If there's interest, i'd love to do:

**Title:** The Embedder's POV
**Abstract:** In a larger JS framework that relies and gets much of its capabilities from its embedded components, we have to be cognizant of versioning and are constantly working to improve the story around the upgrade process. I'd discuss some of the primary pain points around the upgrade process and challenges it introduces, as well as some discussion around how we embed node and how both might be changed as we look to the future. The jumping off point would be Electron, but the talk would work to generalize to the larger embedder community.

**Comment by mhdawson** [comment]
In the N-API team meeting this week, we discussed and would like to have an N-API breakout.

**Comment by jasnell** [comment]
A lightening talk on trace events and diagnostics instrumentation would be worthwhile

**Comment by mhdawson** [comment]
@jasnell possibly useful to add/discuss in #71: Agenda for Diagnostics session at collaborator summit

**Comment by hackygolucky** [comment]
Would love to talk about Moderation Team and preparing potential new folks for moderating and/or nomination to the Nomination team.  ~ 60-90 minutes should be enough. May not even need a room, just a table.

**Comment by davisjam** [comment]
I would be happy to talk about some of the academic work in the Node.js space if that would be interesting.

Some examples:
- [Node.fz](http://people.cs.vt.edu/~davisjam/downloads/publications/DavisThekumparampilLee-NodeFz-EuroSys17.pdf) (mine)
- [Node.cure](http://people.cs.vt.edu/~davisjam/downloads/publications/DavisWilliamsonLee-SenseOfTime-USENIXSecurity18.pdf) (mine)
- [The Impact of ReDoS](http://people.cs.vt.edu/~davisjam/downloads/publications/DavisCoghlanServantLee-EcosystemREDOS-ESECFSE18.pdf) (mine)
- [BreakApp](http://nathandautenhahn.com/downloads/publications/vasilakis-breakapp-2018.pdf)
- [Freezing the Web](http://software-lab.org/publications/ReDoS_TR_Dec2017.pdf)
- [Synode](http://software-lab.org/publications/ndss2018.pdf)

**Comment by ladyleet** [comment]
👍👍👍👍👍 pls fill out form when you can!

**Comment by Trott** [comment]
> 👍👍👍👍👍 pls fill out form when you can!

@ladyleet I don't think there's a form for this, is there? (Are you confusing this issue with https://github.com/nodejs/summit/issues/103? Although I'd totally encourage @davisjam and anyone else to apply to talk there too.)

**Comment by ladyleet** [comment]
Oh yeah totes sorry planning too many things 🙃

**Comment by hekike** [comment]
I'd like to give a short 15 minutes talk about the debugging and performance profiling work we have been working on at Netflix.

**Comment by joyeecheung** [comment]
I'd like to propose another session:

**Title**: Automation of Node.js core workflows
**Abstract**: About a year ago we started the automation team to help improving the workflow of Node.js core collaborations. In this session I will cover what we have done, what our ongoing projects are, and what needs to be done. We will discuss about the following aspects of automation: interaction with CI, PR/backport workflows in Node.js core, and updates of third-party dependencies (and any other workflows that can use some help of automation, e.g. releases). I will also give an introduction to help more people getting involved.

**Comment by maddhruv** [comment]
sorry to raise in here
but on doing this
> Atteneeds must register at: https://www.regonline.com/?eventID=2152653&rTypeID=511098
Access code: COLLABSUMMITONLY

the card verification is done for four times and amount has been deducted for non reason and apparantely registration is not done
/cc @mcollina

**Comment by mcollina** [comment]
@maddhruv I'm not responsible for that registration.
@ladyleet might know more about it.

**Comment by targos** [comment]
@maddhruv I saw that in https://github.com/nodejs/admin/pull/223 you asked for the JSI ticket. During regular JSI registration, there will be a step asking you if you will attend the collaborator summit. You do not need to register separately AFAIU.

**Comment by maddhruv** [comment]
Oh, wonderful! :wolf: 
Thanks, @targos :handshake:

**Comment by ladyleet** [comment]
@maddhruv still having issues?

**Comment by maddhruv** [comment]
Not much, but will ping you on email if I face any issue with the visa centre executive

**Comment by hashseed** [comment]
It's now past the end of August. Who decides whether the talk proposals are accepted, and when? I would like to start preparing if the topics I suggested are interesting.

**Comment by mcollina** [comment]
I have a draft of the agenda done. We have a call this Thursday to discuss it before we make it public, I'll do so on Friday.

**Comment by mhdawson** [comment]
If its still possible the N-API team would like a session where we'd cover:

Breakout session at collaborator summit
  * cover the code layout and how to jump in - node-addon-api and core
  * cover  ways to contribute

**Comment by mcollina** [comment]
I've updated the agenda 🎉 ! Certain things are still tentative, and there are still some slots free. If you would like to take one, create an issue in this repo (or in the repo of your own wg), and add a comment to this issue. We'll take care of updating/rebalancing the agenda.

**Comment by mcollina** [comment]
@davisjam If you would like to put your name and talk title on one of the lightining talk slot, it'd be fantastic. I didn't know what to pick.

**Comment by davisjam** [comment]
@mcollina Done, thanks.

**Comment by mhdawson** [comment]
@mcollina the Security-wg had asked for a slot (see https://github.com/nodejs/summit/issues/100#issuecomment-408974021), can we add it for one of the free ones?

**Comment by mcollina** [comment]
@mhdawson done! I'm not sure how I missed that!

@bnb you suggested a session for @nodejs/i18n but no one picked it up? Who is going to lead that?

**Comment by MylesBorins** [comment]
@mcollina if it isn't too late I'd love to have a session about LTS + Release

**Comment by mcollina** [comment]
@MylesBorins Would it be ok in the main room on the first day?

**Comment by MylesBorins** [comment]
@mcollina I was thinking more of a smaller break out but I'll take what I can get 😄

**Comment by mcollina** [comment]
@MylesBorins would you mind opening an issue in the LTS repo, and adding that to the agenda?

**Comment by ofrobots** [comment]
Hi Folks. If there is still room on the agenda, I would like a session on supporting WASM native modules. I can help lead it.

**Comment by mcollina** [comment]
@nodejs/i18n @nodejs/community-committee @bnb do you need the slot I marked for i18n on day 2? We can use that.

@ofrobots we have two breakouts free during the Governance session. Will you be ok in missing that?

**Comment by ofrobots** [comment]
@mcollina hmm.. I wouldn't want to miss the Governance session. Any chance of a third breakout room in one of the timeslots?

**Comment by obensource** [comment]
@mcollina yes! That's great–we'll take the 11am spot on day 2 for i18n. Super stoked! 🙌

**Comment by ladyleet** [comment]
Collaborators - Please register for this party!

Telus is sponsoring a party after Node + JS Interactive (@ahmadnassri  has been the one helping facilitate a lot of this) and while it's open to the public, the main reason they wanted to sponsor was to throw a party for the Node.js collaborators.

That being said, I highly recommend everyone RSVP asap as it it is limited to ~200 folks and will be mentioned in the general conference announcements! Would hate for anyone not to get in!

https://www.eventbrite.ca/e/node-js-happy-hour-with-telus-digital-tickets-50099526031

The event will be Thursday October 11th at 6:30pm to celebrate the end of the conference and the start to an awesome Code & Learn + Collaborator's Summit.

**Comment by SMotaal** [comment]
Can individual (non-collaborating) members get free access to all events? And also to clarify, sorry I am lost in the details, collaborators can attend JSI for free but need to register.

**Comment by joyeecheung** [comment]
The event is about a month away from now. I am thinking maybe we can put the agenda into a document in this repo and have people sending PRs (preferably adding links to slides before the event started) instead of responding here? That way it's easier to track the progress before the event and look up in the future.

BTW we had a placeholder for the agenda in Berlin but never managed to fill it out https://github.com/nodejs/summit/blob/master/2018-05-Berlin/agenda.md

**Comment by joyeecheung** [comment]
> And also to clarify, sorry I am lost in the details, collaborators can attend JSI for free but need to register.

Node.js foundation individual members can request tickets funded by the foundation by sending PRs to https://github.com/nodejs/admin/blob/master/TravelFunds/2018.md (the process is described in https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md) but I think the deadline for JSI has already passed? (I vaguely remember that we have set a one-month-ahead deadline somewhere...)

**Comment by chowdhurian** [comment]
> we can put the agenda into a document in this repo and have people sending PRs
> we had a placeholder for the agenda in Berlin but never managed to fill it out 

Good suggestion @joyeecheung.

PTAL at #104.

**Comment by apapirovski** [comment]
@joyeecheung I don't think there's a time limit other than the min 72 hours for review and the request having to be made prior to the event. I for one am extremely behind and have not submitted mine yet. (Will do tonight.)

If we want to have a time limit then it should be explicit in our documentation.

**Comment by chowdhurian** [comment]
## Update: Per [suggestion](https://github.com/nodejs/summit/issues/100#issuecomment-422465874) and related #104, the agenda is being [maintained here](https://github.com/nodejs/summit/blob/master/2018-10-Vancouver/agenda.md) now. Please make a PR to it for changes 🙌🏽

**Comment by misterdjules** [comment]
The promises and diagnostics breakouts are happening at the same time on the same day. Since there is overlap in the topics that will be covered and in the people who may want to attend (e.g. those are the two breakouts I'd like to attend, and I think that @yunong, @hekike and @mmarchini may want to attend both of those as well), can we move one of them to another time slot?

/cc @kjin @BridgeAR @yunong

**Comment by misterdjules** [comment]
@mcollina I would not have the "promises" and the "diagnostics" session happening at the same time. One of them could be moved to either earlier on the same day or to the second day. The former would probably be better for @yunong.

**Comment by Qard** [comment]
I would selfishly suggest moving the diag breakout to the next day, as I'll be flying back from Dublin that morning and probably be _very_ tired. 😅

**Comment by mcollina** [comment]
@yunong is not planned to attend on Day 2. He asked for diag to be on Day 1.

@misterdjules which session would you replace?
