### ISSUE TITLE
Copy for Collaboration Summit for JS Interactive website

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/summit#101]
I've pulled together some copy for the Collaboration Summit happening after JS Interactive. I wanted to share with this group in case you have any suggested copy changes. If folks could provide their feedback asap, that would be much appreciated. I would like to get this posted by Wednesday (August 1) as I am pushing out a JS Interactive add-ons blog post to try to continue the momentum of getting folks to register for the event. 

To note, we can always slightly edit this copy if anything changes during planning.

**_Collaboration Summit**
Date: October 12 - October 13, 2018
Time: October 12, 1:00-5:00 pm; October 13, 9:00 am-5:00 pm
Location: Vancouver Convention Centre West Building (multiple rooms)
Cost: Complimentary; Pre-registration required.
The Collaboration Summit is a day and a half event that follows the JS Interactive conference. This is a community-organized event where different JavaScript communities have the opportunity to collaborate on the different subject matter that is important to them. This event moves quickly, and there will be no onboarding with topic discussions. 
**EVENT DETAILS** 
Date: October 12 - 13, 2018
Time: October 12, 1:00-5:00 pm; October 13, 9:00 am-5:00 pm
Location: Vancouver Convention Centre West Building (multiple rooms)
Registration Cost: Complimentary; Pre-registration required.
**How to Register:**
Pre-registration for this summit is required. When you register, you will be given the option to register for this during check out._ 

cc: @dshaw @chowdhurian @mcollina @ladyleet

**Comment by mcollina** [comment]
> The Collaboration Summit is a day and a half event that follows the JS Interactive conference. This is a community-organized event where different JavaScript communities have the opportunity to collaborate on the different subject matter that is important to them. This event moves quickly, and there will be no onboarding with topic discussions.

I do not think this is correct. This is the **Node.js project** Collaborator Summit, there are _no_ other communities involved in the discussion. It is not for general JavaScript community. It is a working session where the Node.js project collaborators get together.

**Comment by mhdawson** [comment]
While I understand the attempt to be broadly inclusive, I agree with @mcollina that its the Node.js Collaborator Summit and that the topics are being organized and are focussed on the Node.js community.

**Comment by ladyleet** [comment]
this looks pretty good to me! thanks @ZibbyKeaton for helping promote this.

**Comment by mhdawson** [comment]
+1 from me.

**Comment by dshaw** [comment]
@ZibbyKeaton Thank you for reaching out. Is there another section of the site which covers Code and Learn in the morning? We need a lot of Node.js collaborators in attendance to manage the size of crowds we see there. It would be good to make sure Node.js Collaborators know they need to show up in the morning too.

**Comment by ladyleet** [comment]
@dshaw yes there is - i spoke with @Trott about it I believe at node summit and it sounded like we didn't need to explicitly ask as it's generally assumed but what we can do is send out a reminder a few days before to make sure folks show up?

**Comment by ZibbyKeaton** [comment]
Yes, @dshaw. I shared the copy via this thread: https://github.com/nodejs/code-and-learn/issues/83. I'm confirming if we will have a place for Node.js Collaborators to sign up to help out. To note, I would recommend that we organize volunteers via GitHub vs the JS Interactive website.

**Comment by mcollina** [comment]
I would change the copy of the last sentence from:

> Friday, October 12th will be open to the public, while Saturday, October 13th is reserved for official collaborators only.

to

> Both days are open to the public, but the discussions will be highly focused on the Node.js project and its community, and non-collaborators are expected to participate as observers.

This is definitely not perfect, but it matches the spirit of the Collaborators Summit. Feel free to edit / flag problems if you see some in this approach.

**Comment by ZibbyKeaton** [comment]
Great! And thank you for the edits @mcollina!

**Comment by ZibbyKeaton** [comment]
I change the description to:

The Node.js Collaboration Summit is a day and a half event that follows the JS Interactive conference. This is a Node.js community-organized event where individuals involved in the Node.js project will collaborate and discuss subject matters important to them, whether it’s next steps with HTTP/2, diagnostics, modules, website redesign, mentor initiatives, etc. 
Both days are open to the public, but the discussions will be highly focused on the Node.js project and its community. This event moves quickly and there will be no onboarding with topic discussions. Non-collaborators often participate as observers.

**Comment by mcollina** [comment]
SGTM

**Comment by ZibbyKeaton** [comment]
Background on why we included this: We discussed including this content during our last CommComm committee meeting to set expectations to those interested in attending. In the past, a few people who attended thought that there was going to be more onboarding and felt a bit lost.

I tend to lean towards overcommunicating vs. under-communicating, but if this feels a little bit too "inside baseball," we can take it out.

**Comment by ZibbyKeaton** [comment]
I want to confirm with the Collab Organizers that you are okay with the copy we have on the JS Interactive website: https://events.linuxfoundation.org/events/js-interactive-2018/agenda/add-on-events/

cc: @dshaw @chowdhurian @mcollina @ladyleet

Currently the public can register for October 13. If we want to keep this part closed, then we can make it so folks can only register for October 12 and we would only advertise this day. 

We had a discussion that we would make October 13 open to the public, emphasizing that it would move quickly, but I'm hearing different "takes" from people, so I want to make sure we are all on the same page.

**Comment by dshaw** [comment]
@ZibbyKeaton The copy looks good.

How do folks pre-register if they aren't attending the full event?

Technical detail: Is it possible to have something that links directly to this section? I poked at it and couldn't make it work.

From a project perspective, I haven't heard any pushback on inviting the general public to engage with the Node.js project. Where I have heard feedback has come from the event side where folks were unaware of what they had signed up for and didn't feel like meetings provided the value they were expecting, thus creating burden on the events team.

**Comment by ZibbyKeaton** [comment]
@dshaw collaborators have a separate link to register for the event if they are not attending JSI.

If you are not a collaborator, then you need to be attending JSI to sign up. We can change this closer to the conference, but given we are providing food and have limited space, this has been the best way for us to manage the logistics for this. We've had folks bail last minute or just sign up because it says free, and we want to try to limit this as much as possible. 

We are hoping that the copy we provided above will give folks a better sense on whether or not Collab Summit is right for them. We can provide further details in email for those who register as well if folks think that would be worth the cycles.
