### ISSUE TITLE
Call for topics and speaker volunteers - Node Community Corner at Node+JS Interactive!

### ISSUE THREAD

**Issue by ladyleet** [nodejs/summit#103]
Exciting stuff - JS Interactive has offered a special community corner dedicated to Node for Node specific content that may not be covered at the conference. Huge thanks to @bnb for driving this and @gtewallace, Lara Taback and team for helping make it happen.

I'll be helping coordinate the Node Community Corner on behalf of the Node Foundation.

The community corner will be active during both days of the conference (Oct 10-11) - programmed with fun stuff and content - in the form of 5, 15, and 30 minute talks/panels, and or just open office hours/space and time for folks. 

First things first, we want to hear from you on what topics you'd like to talk about or cover. 

To make a suggestion on topics or to submit a talk or panel, etc, please visit this form.
https://goo.gl/forms/nIy5qnDEHjafdjmm1

The deadline for this is Monday August 20th at 5pm EST.

**Action Items for all of you:**
1.  Please provide feedback on the form - do I need to add anything?
2. What is the best way to "review" the content? I was thinking about scheduling 2 "review" meetings in which anyone can attend. We can also elect 2-3 folks from CommComm/TSC to represent if this makes more sense. Open to ideas.
3. What are some other cool things we can do with this space for the community? If someone wants to sponsor a nail table and we can do node.js nail decals. Of course - we'll need a sponsor for this. :P
4. Did I miss anything? Do you have any questions?

**Comment by mcollina** [comment]
Some questions:

- Would speaking at this community corner grant a ticket?
- Is it open to just collaborators (and members)?
- what's the deadline?
- how long will we have the corner?
- how big is the space? Is it a room or is it in the main hall?

Other ideas:

- Node School session
- NodeBots / IoT (requires a sponsor) - if it's not covered by the main tracks.
- Node.js CI hackathon

I think the best way would be to pick a small team to select this.

**Comment by ladyleet** [comment]
- No - speaking will not grant a ticket. This is an extra added bonus for our community that is not funded by JSI except for the space and A/V.
- I don't know who it is open to! I would assume everyone?
- The deadline for this is Monday August 20th at 5pm EST.
- Corner will be for the duration of the conference while other programming is going on, both days. If we can fill the entire time, great. If not, then we'll space things out 
- The space will be a booth like space.. I don't have exact measurements yet but I will check.

Thank you for your input on other ideas - I think this will be dependent on space but. 

I'll wait to hear from others re: how to go about selecting content for programming.

**Comment by mcollina** [comment]
> The space will be a booth like space.. I don't have exact measurements yet but I will check.

Will there be chairs/tables?

**Comment by Trott** [comment]
What's the approximate attendance capacity of the space? (I guess another way to ask: If there will be chairs as Matteo asks, how many?)

**Comment by Trott** [comment]
In the form: Can we make "Type of Talk" a radio button selection rather than a text box? I assume it's supposed to indicate whether someone is looking for the 5-minute, 15-minute, or half-hour slot?

**Comment by ladyleet** [comment]
@Trott yeah i'd love to leave it completely open to anything and not box it into one of those three. thoughts?

**Comment by ladyleet** [comment]
@mcollina @Trott asking about tables/chairs and spae

**Comment by dshaw** [comment]
@ladyleet It would be useful to put the dates when this will happen. I assume we're talking about. 10/10-11.

Since some of us already have regular session talks, will the selection committee take the existing schedule into consideration when they are lining up the sessions? If not, will folks have any recourse to adjust they're talk timing?

**Comment by bnb** [comment]
Would love to hear from @zeke, @obensource, @amiller-gh, and @chowdhurian on i18n and the website redesign initiative.

For @zeke, @obensource, @amiller-gh, and @chowdhurian, note that this is separate from the Collaborator Summit and any context you may be sharing there 😄

**Comment by ladyleet** [comment]
We are unable to do workshops or have tables there but there will be a small area for people to stand "stage".

**Comment by ladyleet** [comment]
Thx @bnb!

@dshaw yeah - we'll have to figure this out but we will make sure things do not overlap.

**Comment by ladyleet** [comment]
We are thinking the community corner will be against this wall, but still unsure yet of final place.

<img width="1111" alt="community corner" src="https://user-images.githubusercontent.com/8270563/44054503-992f7546-9ef7-11e8-8972-d82155f805ee.png">

**Comment by zeke** [comment]
> Would love to hear from @zeke, @obensource, @amiller-gh, and @chowdhurian on i18n and the website redesign initiative.

Here's some high-level stuff:

- Translations are in progress! Over 120 folks have translated content already.
- Over a million words, so progress numbers are still pretty low.
- I've proposed an API for the `nodejs-i18n` module to be consumed by the new website. Seeking feedback from website folks here: https://github.com/nodejs/website-redesign/issues/76 -- cc @chowdhurian who said this will be discussed at the next website meeting (this week)

**Comment by amiller-gh** [comment]
@chowdhurian, @bnb, proposal form filled out 👍

**Comment by obensource** [comment]
@zeke, @obensource, @amiller-gh, @chowdhurian, and @ladyleet I've been on paternity leave for 6 weeks until today and will take a look asap. On a verbal commitment level tho–you can count me in absolutely! More communication coming asap! 🙌

**Comment by codeekage** [comment]
Can I Veblen counted in, to help with the community corner? 😊

**Comment by zeke** [comment]
>  paternity leave

congratulations, @obensource! 🐣

**Comment by obensource** [comment]
Thanks @zeke! 🍻

🙌👶🙌

**Comment by ladyleet** [comment]
Pinging folks as a reminder to submit things to the google form as the deadline was last Monday. :P We are gathering a committee to speak about the agenda - so if you want to participate please comment on issue https://github.com/nodejs/admin/issues/219

**Comment by medinadavis** [comment]
Hi all!

I’m excited for Node + JS Interactive next week!

However, we are short on volunteers for the Node Community Corner Office hours, so we created [this google form](https://docs.google.com/forms/d/e/1FAIpQLScJUxOv0BMYljB4hJ2oIfJaXDZaB6qCw8tSrLuBNSYrLGI1Tg/viewform) and we’d really appreciate it if you all could pick the day & times you’d be available to volunteer. 

Let me know if you have any questions!
