### ISSUE TITLE
Local events happening in Vancouver for N+JS Interactive

### ISSUE THREAD

**Issue by chowdhurian** [nodejs/summit#105]
Creating this issue for visibility to out-of-towners for the two local events happening in Vancouver for Node+JS Interactive 👀

Would recommend everyone RSVP to the events because the spaces are capped and the events are all open to the public!

No conf ticket required for any of the events here.

----

## Node&JS Community Hangouts, N+JSI Kickoff Edition with Microsoft (17:00, 9th October)
Microsoft is sponsoring and hosting a kickoff event. It'll be part of a new local meetup. (@anthonychu  @lucamaraschi have been doing a lot to get this local Node.js meetup running)

* It's open to the public
* If you're in Vancouver the night before the conf begins, catch up with old friends, and make new ones for the conf over food and talks! 🧀🍕

### Register

https://www.meetup.com/Node-JS-Community-Hangouts/events/254588228/

----

## Node + JS Happy Hour with TELUS Digital (18:30, 11th October)
Telus is sponsoring a party after Node + JS Interactive (@ahmadnassri has been the one helping facilitate a lot of this)

* It's open to the public
* Celebrate the end of the conference and the start to an awesome Code & Learn + Collaborator's Summit! 🎉🎉🎉

### Register

https://www.eventbrite.ca/e/node-js-happy-hour-with-telus-digital-tickets-50099526031

**Comment by maharrg** [comment]
### experts’ dinner — npm and friends

Join us for cocktails and supper before the start of the Node+JS Interactive conference with npm, Inc. co-founder Laurie Voss, Head of Security Adam Baldwin, and Head of Enterprise Product Ben Coe.

The invitation-only event will facilitate discussion and forge connections among fellow executive and senior management leaders in development, developer operations, security, and digital strategy.

5:30 pm cocktails 
6:30 pm supper 
venue TBA, within walking distance of the Vancouver Convention Centre

_Due to space constraints, if you wish to bring a colleague or recommend other invitations, please [get in touch](mailto:jec@npmjs.com)._

**Can’t make it?**
If you’ll be around Vancouver during the conference, [let’s grab a cup of coffee](https://calendly.com/npm-inc/30min/10-09-2018).

Not coming to Vancouver? [Let’s chat](https://calendly.com/npm-inc/15-minute-call).

Feel free to copy-paste this into the initial issue.

**Comment by Bamieh** [comment]
Awesome!! Thanks for sharing this

**Comment by bnb** [comment]
## Node.js Best Practices training with NodeSource and Snyk

We're going to be doing a [full-day Node.js Best Practices](https://www.eventbrite.com/e/nodejs-best-practices-training-tickets-49750292464) training on October 9th, if you'd like to get some learning in before the festivities start!

Going to be going over the full spectrum of topics, which will help prepare you for the wide variety of talks at the conference: 

* Code and Organization standards
* Testing and Test Coverage
* Node.js Modules and Dependency management
* Error Handling
* Microservices and API Design
* Security
* Deployment and Monitoring

### Free tickets for y'all 
I've gone ahead and reserved 5 tickets a 100% discount for community members who discover the event through this issue. You can use the code `NODEJSCOMMUNITY` a comped ticket. Looking forward to seeing y'all in Vancouver! 💖

**Comment by NickNaso** [comment]
@bnb Thanks it will be great!

**Comment by trivikr** [comment]
I'd great time at the Node+JS Interactive fun-run today:
* Pics https://twitter.com/trivikram/status/1050058559541587969
* Views from Harbour Green Park https://twitter.com/trivikram/status/1050060196288942081

There's a ghost race on Friday morning organized by Lululemon and Strava ([link](https://theghostrace.lululemon.com/cities/van))
I've registered already. Do join if you're interested!
