### ISSUE TITLE
Summit Topic: Open standards & Web compatibility

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/summit#106]
Just noticed that we don't have a slot assigned to this topic, since we just started the open standards team recently, it seems to be a good idea to start a discussion at the summit around this topic.

I propose that for this summit, we focus on discussing around the **process** that we wish to implement in **Node.js core** regarding standards participation, implementation, and compatibility with the Web - try to start small and not to extend to the broader Node.js ecosystem, 
 and not to dive into the implementation details this time, because we will only have one and a half hour for this session in a room with many people. Of course there will be plenty of opportunities to talk about topics outside of core in the hallway and online in smaller groups.

#### Proposed agenda && Minutes

https://docs.google.com/document/d/1HmhBOIYydVQQ1YCsVASuS2gv6vfYv59ws6_xj86Lsi8/edit

cc @nodejs/open-standards

**Comment by SMotaal** [comment]
Can I also add **better practices for interoperability** for all developers… I am really aiming more at the common patterns which can **needlessly** locks code to a platform.

**Comment by joyeecheung** [comment]
@SMotaal Do you think this falls more into the “current state” topic or the “implementation” topic? Correct me if I am wrong but this seems to be a topic that has less to do with process but more with details in code? I would prefer to leave topics that may involve code examples to GitHub because it would be very hard to talk about concrete code verbally.

**Comment by joyeecheung** [comment]
@SMtaal Or if you can have slides prepared upfront to present so we could include them in the session? (I still have doubts about diving into code details in a room with a lot of people and talk about it synchronously but we can try to make it work)

**Comment by benjamingr** [comment]
Just a request - if someone could take (and post) notes at the end of this I would appreciate it since I am unable to attend.

**Comment by SMotaal** [comment]
@joyeecheung I like it more as a GitHub thing. So, maybe a discussion item would be to consider collating together code examples with emphasis on code portability between Node.js and other conforming environments.

**Comment by joyeecheung** [comment]
@SMotaal So if I understand correctly, you meant that we need to discuss about having code examples to demonstrate interoperability (i.e. we need documentation, and how to start an effort towards that direction, .etc), but not actually discussing about concrete code examples? That sounds doable to me (in mean, in a physical room)!

**Comment by joyeecheung** [comment]
Just a request - if someone could take (and post) notes at the end of this I would appreciate it since I am unable to attend.

> @benjamingr 

If I understand correctly, we will use Zoom if possible so there should be recordings. I'd appreciate help for note taking (I guess I will sora-kinda chair the discussion, I want to use https://tcq.app/ so there will be a queue to keep track of the items/questions). In any cases I opened https://github.com/nodejs/summit/issues/111 for suggestions about how we should go about it (and I hope we can do what I suggested in every session, if people feel like it)

**Comment by littledan** [comment]
If you'll be using Zoom, I would love to call into this discussion.

**Comment by benjamingr** [comment]
Thanks Joyee that clarifies things. To be clear I absolutely understand if you don't record it knowing that it requires work and reduces momentum in sessions.

(That said, I think using Zoom makes sense and Daniel can contribute to the meeting)

TCQ doesn't save notes yet - this is actually something I intend to work on in the next few months now that my life is a bit more stable and as a Vue.js project to work on :)

**Comment by joyeecheung** [comment]
> To be clear I absolutely understand if you don't record it knowing that it requires work and reduces momentum in sessions.

Thanks for understanding, but I actually really want to make sure we record them :D (I want to make sure we record and take notes for all of our sessions, to be honest). It may take a few minutes to set the stuff up but if we don't do that, we are very likely to walk out of the room without anything actionable/any consensus and will forget what we talk about in a few weeks, then the session may as well never happen.

> TCQ doesn't save notes yet - this is actually something I intend to work on in the next few months now that my life is a bit more stable and as a Vue.js project to work on :)

Awesome! Yes please!

**Comment by joyeecheung** [comment]
Hi all, I attended the [Web Engines Hackfest](https://webengineshackfest.org/2018/) this week where there are many Web engine developers present. Based on some feedbacks I got from the event, I modified the proposed agenda a bit in the hope of making the upcoming session more productive.

<quote>
I propose that for this summit, we focus on discussing around the **process** that we wish to implement in **Node.js core** regarding standards participation, implementation, and compatibility with the Web - that is, try to start small and not to extend to the broader Node.js ecosystem this time, because we will only have 1:30 for this session. Of course there will be plenty of opportunities to talk about topics outside of core in the hallway and online in smaller groups.

Proposed agenda:

- State of web compatibility in Node.js
  - APIs implemented with existing Web APIs in mind, but without conformance tests
  - APIs implemented per the specification and covered with Web Platform Tests
  - Current status of interoperability between Node.js APIs and Web APIs
- Implementing existing standards in core
  - The process for proposing to implement, implementing and shipping standards in core
  - How do we seek consensus on whether to implement a standard in core
  - How to integrate upstream tests (e.g. Web Platform Tests)  into core and report about conformance
  - How to improve documentation for interoperability between existing APIs and Web APIs
- Standards that we may be interested in implementing
- Participation in standards bodies for future standards
  - How we can provide constructive feedback to standards body that represents the spectrum of opinions in core
</quote>

If you have any suggestions or opinions, feel free to reply in this issue and we will try to iterate on the agenda before the session starts, thanks!

**Comment by mhdawson** [comment]
@joyeecheung looks like a great agenda.

**Comment by nomadtechie** [comment]
@joyeecheung will there be an option to remote dial-in to this portion of the meeting?

Some of our[ _Reliability, Standards & Testing_](https://bocoup.com/services/reliability-standards-and-testing) team at Bocoup who help maintain Web Platform Tests may be interested in participating cc @jugglinmike @zcorpan @rwaldron @boazsender

**Comment by joyeecheung** [comment]
@nomadtechie Based on the discussion in https://github.com/nodejs/summit/issues/111 (assuming no one is against my idea in https://github.com/nodejs/summit/issues/111#issuecomment-426457995) If this session ends up in the main room we will use Zoom for the session so will probably paste a Zoom link here before the session starts, also the main room sessions will be broadcasted on Youtube if we manage to set it up properly.  If the session ends up in a breakout room, we will try to use Google Hanghout and there probably won't be broadcasts (since there is only one Node.js Youtube account) but we will try to set up remote participation as well.

(Just a fair warning, we didn't get the remote participation set up very well the last time in Berlin, there were camera being blocked and remote participants who didn't get a chance to talk, but we will try to improve this time!)

**Comment by nomadtechie** [comment]
That sounds great. Thank you @joyeecheung!

**Comment by joyeecheung** [comment]
I have created a google doc that we can use as basis to take notes for the meeting.

https://docs.google.com/document/d/1HmhBOIYydVQQ1YCsVASuS2gv6vfYv59ws6_xj86Lsi8/edit?usp=sharing

I also added a section to the top of the agenda, which I think makes sense given our session is limited.

> ### Goals of this session
> - To review the current status of Web compatibility in Node.js
> - To discuss around the **process** that we wish to implement in **Node.js core** regarding standards participation, implementation, and compatibility with the Web
> - To discuss about the organization of the open standards effort
> - To come up with actionable items that we can follow up on after this session

Feel free to edit the doc prior to the session, but please leave a note here after you do so so we can keep track of the iterations.

**Comment by SMotaal** [comment]
@joyeecheung I'm so sorry for not returning back to you:

> @SMotaal So if I understand correctly, you meant that we need to discuss about having code examples to demonstrate interoperability (i.e. we need documentation, and how to start an effort towards that direction, .etc), but not actually discussing about concrete code examples? That sounds doable to me (I mean, in a physical room)!

This is exactly my hope. Coming from the Modules group and my own experimentations with isomorphic code patterns in unbundled ESM, I find that interoperability has largely depended on bundler magic — from the perspective of users of those tools without really knowing what happens to their code.

Complex shimming aside, genuine understanding of writing adaptive code, graceful fallback, effective and efficient platform utilization... etc., in my opinion those are inseparable basic aspects of the JavaScript language. If JavaScript developers will be encouraged to avoid understanding them because tools will do it for them, then sadly we are helping perpetuate the false sentiments that we are all working hard to change about the JavaScript developer community.

Sorry for being a little passionate here.

**Comment by SMotaal** [comment]
I was not sure where this best fits in the agenda so I simply added that as a comment.

**Comment by joyeecheung** [comment]
@SMotaal If I understand correctly https://github.com/nodejs/summit/issues/106#issuecomment-429541174 can be summarized as bullet point "Recipes for migration v.s. Tools that automate migration"?

**Comment by joyeecheung** [comment]
Also a few alterations to the agenda after talking to a few people at the summit yesterday

- Add time boxes (there should be plenty of time to chat casually after the whole thing, according to my experience yesterday, provided not everybody is rushing to the airport)
- Add 

> ### Organization (5min)
> - Setting up Zoom
> - Find note takers

- Revamp the last item a bit, it now looks like

### Participation in standards bodies for future standards (30min)

> - How we can provide constructive feedback to standards bodies and represent the spectrum of opinions in core
>   - Representatives? Pre-meetings?
> - What communication channel (e.g. meetings, conferences, IMs, GitHub) we can use to
>   - Synchronize about our work
>   - Report to other collaborators/the community about the status of our work
>   - Get feedback from the community and to improve inclusivity
> - Partnership opportunities between standards bodies
>   - Specify node-related things
>   - Help standard bodies with organizational work (meetings, participation process, documentation)
>   - What our image should be in standards bodies? What are our values? Visions?

**Comment by joyeecheung** [comment]
BTW I minimized some previous comments about agenda bashing to make this thread smaller

**Comment by joyeecheung** [comment]
So, there seems to be some miscommunication. IIRC, we will only have 1 hour (2:30-3:30) for this session after https://github.com/nodejs/summit/pull/118 but there is another free slot before the session starts. @mcollina Can we move this to the slot (1:30) for the previous breakout (free) and extend to 1 hour and a half?

**Comment by mcollina** [comment]
Sure send a PR

**Comment by joyeecheung** [comment]
Update: the session will be at 1:30 - 2:45 in Main Room (121)

After observing a few sessions I don't think it's feasible to use TCQ in a tight schedule like this - too much overhead.

**Comment by joyeecheung** [comment]
Zoom link: https://zoom.us/j/383984667
