### ISSUE TITLE
Summit Notes - Aug 2015

### ISSUE THREAD

**Issue by snostorm** [nodejs/summit#11]
See https://tiny.cc/2015-node-summit (editable)

**Comment by chrisdickinson** [comment]
Attaching topography of WGs:

```dot
digraph {
        build -> TSC [color="green"]
        build -> smoketest
        build -> LTS [color="green"]
        build -> addons
        build -> hardware [color="red"]
        build -> docker [color="green"]
        build -> website [color="green"]
        build -> benchmarking
        hardware -> addons [color="red"]
        diversity -> evangelism
        diversity -> documentation
        documentation -> postmortem
        documentation -> website
        addons -> TSC
        addons -> API
        addons -> LTS
        LTS -> TSC [color="red", style="dotted"]
        LTS -> smoketest
        LTS -> postmortem
        TSC -> streams
        TSC -> intl
        benchmarking -> tracing
        evangelism -> locales
        intl -> website
        website -> locales
}
```

![wgs](https://cloud.githubusercontent.com/assets/37303/9119962/73dcd772-3c2e-11e5-8410-a2a2efd5502e.png)

**Comment by srl295** [comment]
@chrisdickinson intl should go to locales not website

**Comment by snostorm** [comment]
I've locked down write access to the folder, so let me know if you need it. Ideally we would have had some whiteboard photos uploaded to fill in for possible gaps, but generally most points did get covered.

This issue should stay open until all of the sessions are converted in to markdown and submitted to the repo.

Thanks to everyone who helped put together the live notes over the last few days!

**Comment by mikeal** [comment]
@snostorm have you already started converting these notes to markdown or should I do it?

**Comment by snostorm** [comment]
@mikeal nope, not yet. Feel free. Incase you want to work in the original docs I'll fix that now (or feel free to "fork" them.)

If you think it makes sense I can also make them publicly editable again (I locked it down after the event.) That way working in the same docs might make it easier for myself or another volunteer to jump in to a doc you haven't started yet?

**Comment by mikeal** [comment]
I got the agenda and the first 2 sessions migrated. https://github.com/nodejs/summit/commit/f0354058aafdbc99b15034332d473f4a048b8b1d

It's more work than I initially thought. Does anyone have a quicker way to convert from a Google Doc to markdown?
