### ISSUE TITLE
Summit Topic: Streams

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#110]
Proposed agenda:

1. always call `.destroy()` - @mafintosh 
2. BOB - @Fishrock123 
3. WHATWG Stream discussion - @mcollina

cc @nodejs/streams

**Comment by SMotaal** [comment]
Would (could) this also touch upon how to work with Streams in code also intended for the browsers?

**Comment by mcollina** [comment]
Yes, definitely. Node.js streams or WHATWG streams?

**Comment by mcollina** [comment]
Zoom https://nearform.zoom.us/j/250475295

**Comment by mcollina** [comment]
Here are my slides on WhatWG Streams: https://mcollina.github.io/node-whatwg-streams-proposal

**Comment by Fishrock123** [comment]
Here are my slides on BOB: https://fishrock123.github.io/nodejs-collab-summit-2018

The primary repo is at https://github.com/Fishrock123/bob and contains a bunch of docs & references.

**Comment by yoshuawuyts** [comment]
Here's the notes I took from the meeting. Had some technical difficulties; started documenting around the time Matteo's talk started https://paper.dropbox.com/doc/2018-10-13-Node-Streams--APY3X9xtarKpc0hngJpYn4NPAQ-Vz89KhTgKJgcx0yCIE4y0
