### ISSUE TITLE
Resolve diagnostic group & promise group agenda times

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/summit#117]
Currently the diagnostic group and the promise group are both scheduled for 3:30 on day one. This came up in the diagnostic wg and it would be great if that could be rescheduled since the participants and topics overlap.

**Comment by mmarchini** [comment]
FYI, this is also being discussed in https://github.com/nodejs/summit/issues/100#issuecomment-425981025

**Comment by mcollina** [comment]
Can you make a proposal for a swap between two sessions?

Il giorno mer 3 ott 2018 alle 21:05 Matheus Marchini <
notifications@github.com> ha scritto:

**Comment by BridgeAR** [comment]
Looking at the schedule it does not seem to be possible to find any alternative on day one. On day two it seems like either the 9:15 or 11:00 time slot would be best.

**Comment by mcollina** [comment]
which one are you proposing to swap?

Il giorno mer 3 ott 2018 alle 21:28 Ruben Bridgewater <
notifications@github.com> ha scritto:

**Comment by BridgeAR** [comment]
I suggest to move the promise one to day two since it was explicitly asked that the diagnostic one should be on day one. I do not know who wants to attend what slots on day two, so it's difficult to give a specific alternative.

@MylesBorins @amiller-gh @mhdawson @obensource if any one of you would be willing to switch the your slot with the promise slot to day one, that would be great.

**Comment by benjamingr** [comment]
@nodejs/promises-debugging

**Comment by mhdawson** [comment]
The challenge I have is that I want to be in the diagnostics session as well as the ones with my name against them.  Swapping would put them in conflict.

I wonder if we can cover the promises debugging portion at the end diagnostic session or promises sessions (say last half hour) so people could migrate for that part?

**Comment by mcollina** [comment]
I currently have a 60 minutes slot allocates for a brief recap of the 2 days. We could potentially skip that, and use that hour for promises, maybe shifting a bit the times of the other sessions as well.
