### ISSUE TITLE
Summit Topic: Promises

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/summit#119]
__Abstract__

Last summit the promise debugging group was very valuable and it's time to recap and continue the ongoing efforts.
To do so here's a rough agenda for the meeting. Please feel encouraged to suggest further topics.

__Proposed agenda__

- Current status / what has happened since out last meeting?
- New promise events to debug code ([multiple resolves](https://github.com/nodejs/node/pull/22218))
- Discuss the proposed default behavior for unhandled rejections in Node core (Refs: https://github.com/nodejs/node/pull/20097)
- The [Netflix survey](https://github.com/nodejs/promises-debugging/pull/12) and it's conclusions
- Zero cost async stack traces with [`async / await`](https://chromium.googlesource.com/v8/v8.git/+/f537d77845c666240c8d13466e224a520612f7c5) (thanks a million @bmeurer)
- New promise APIs in core ([DNS](https://github.com/nodejs/node/pull/21264), [streams async iterators](https://github.com/nodejs/node/pull/17755), ...)
- Next steps

@nodejs/promises-debugging for visibility.

**Comment by BridgeAR** [comment]
One more point that we should talk about:

`util.promisify` likely becomes an anti-pattern soon due to loosing the stack trace compared to `async / await`.

Some raw takes for me on this:

- we should make sure that Node internal code always uses `async / await` and not regular promises.
- we should discourage usage of that function and recommend to use `async / await` everywhere throughout the ecosystem, if possible.

**Comment by bmeurer** [comment]
You'll loose the stack trace with any callback based API. I was already thinking that we could introduce some kind of zone mechanism in Node to provide V8 with context information necessary to rebuild the stack trace.

**Comment by benjamingr** [comment]
> `util.promisify` likely becomes an anti-pattern soon due to loosing the stack trace compared to `async / await`.

Can you explain this to me? Isn't the stack trace lost only after the promisifed functions?

I think this is more of a promises-guide concern (tell people to always promisify at the lowest level)

**Comment by benjamingr** [comment]
Would also love it if the sinon issue was discussed (testing fake timers with async functions)

**Comment by devsnek** [comment]
will remote participation be available?

**Comment by BridgeAR** [comment]
To join the meeting please use zoom: https://zoom.us/j/327915725

**Comment by BridgeAR** [comment]
Here we go https://zoom.us/j/756090104

**Comment by mmarchini** [comment]
Link for minutes: https://docs.google.com/document/d/11Wk39aseOsMEq0T9Hz9wDadSxZucIzSgqWo7QgpIWjc/edit?usp=sharing
