### ISSUE TITLE
Followup action - setup collaboration WG

### ISSUE THREAD

**Issue by snostorm** [nodejs/summit#12]
It was agreed that there is a desire to have WG-of-WGs, which I've been referring to as the "Collaboration WG" the last few days.

As a reminder some of the possible scope discussed included:
- Having the WG act as a switchboard for connecting people or groups together who might not otherwise know where to go
- Acting as a hub for the collection and dissemination of best practices among WGs. This could both be proactive research on how various WGs are operating and also a general dumping ground for ideas when members see things are working well within their groups.
- Networking among some reps from any interested WGs (ideally *all* WGs) to occasionally met or async. discuss what is working well (or not so well) for them
- Identifying shared needs or tooling among groups to try and reduce overlapping efforts. Relevant successful tooling could be shared; new tooling could be built in coordination with other groups like Website, Build, etc.

Regardless of the name, it would be great to get a repo spun up. I'm happy to get the ball rolling on the "paperwork" (initial repo files, proper proposal on scope, recruiting, etc.)

Edit: I would have just spun up the repo but I do not have access ;)

**Comment by jasnell** [comment]
The scope of the WG needs to be carefully planned out. The role of this new WG would be to facilitate communication between the various WGs and to ensure that they have access to the resources needed to complete their goals. This may involve things like working with the TSC and the Foundation board to ensure that the necessary resources are even available, ensure that communications channels are open, and ensure that issues are being dealt with. The role is similar to those found in other organizations such as the W3C Team Liaison's that participate in W3C Working Groups. To be certain, the liaison does not have the authority to speak on behalf of either the TSC or Foundation board but do enable collaboration.

**Comment by jasnell** [comment]
Set up: https://github.com/nodejs/collaboration
Also created the @nodejs/collaboration team... although we may want to rename that later to avoid confusion ;-)

**Comment by thefourtheye** [comment]
If possible I would like to join the WG. As I am new I'll get to learn a lot about other WGs as well

**Comment by snostorm** [comment]
@thefourtheye please put a request through at https://github.com/orgs/nodejs/teams/collaboration -- I can't invite you as I am still pending access as well.

**Comment by snostorm** [comment]
Thanks for getting the ball rolling @jasnell - I agree the first step (possibly after getting some representation in) should be to determine the intended scope of the WG. A good conversation to carry on over there :)

**Comment by mikeal** [comment]
@snostorm you are now in the team and a team maintainer so you can add people.

**Comment by snostorm** [comment]
Added @thefourtheye. Anybody else seeing this should join and/or apply. Already have opened a few issues (more to come) to discuss the various aspects, including scope.

**Comment by thefourtheye** [comment]
Thanks @snostorm :-)
