### ISSUE TITLE
Summary article(s) on (Aug 2015) summit?

### ISSUE THREAD

**Issue by snostorm** [nodejs/summit#13]
For inclusion in the weekly update, or perhaps as a post on its own to publish elsewhere, it might be good to publish a summary of the summit for the wider community.

At minimum, for the update, we could along some stats (# attendance, parts of the world, etc.) along with the topics discussed - easy to pull from the agenda and notes - and some of the outcomes.

relates to nodejs/evangelism#133

**Comment by snostorm** [comment]
FYI I'll try to help with this over the next few days, but I don't have some of the stats, etc. to work from. I can more easily speak to what was discussed based on how the agenda and goals evolved.

@mikeal do you have any quick/interesting bullet points to pass along?

If somebody knows 100% they have time to help write this, even better. I can do it in a day or two -- but it'll be a more rushed effort.

**Comment by diagramatics** [comment]
If any, probably the weekly update would need only a paragraph of what has happened in the summit. The rest might just be published outside of the weekly update if necessary.

**Comment by mikeal** [comment]
I'm going to make my way through the notes and then write a few pieces.

**Comment by diagramatics** [comment]
@mikeal Any update for this?

**Comment by mikeal** [comment]
Working on an artcile about v3 and v4, then I’ll move on to a few articles about the summit.

**Comment by diagramatics** [comment]
Ah, full articles? Any key takeaways from the summit that I can include on the weekly update?

**Comment by mikeal** [comment]
The articles are more about promoting some of the shared understanding we created in some of the sessions. If you’re looking for something in the weekly update I would just go with posting the notes.

**Comment by diagramatics** [comment]
Right, will do. Thanks!
