### ISSUE TITLE
Collaboration Summit - Presentation Slides on Agenda

### ISSUE THREAD

**Issue by ErickWendel** [nodejs/summit#132]
Hey guys. Could you add one section on agenda with the presentation slides links to each talk?

**Comment by joyeecheung** [comment]
(trying to cc everyone that I can remember who have presented slides )@hashseed @codebytere @ MylesBorins @kjin @mmarchini @apapirovski @davisjam @hekike  @addaleax 

(also myself)

**Comment by addaleax** [comment]
Slides @ https://addaleax.net/node-cpp-vancouver/

**Comment by joyeecheung** [comment]
Automation of Node.js core workflows https://docs.google.com/presentation/d/1SZwEOoBxUgaYQLiNk7OAmtvgZ8tFUgdq0IRM6rEAJho/edit?usp=sharing

**Comment by codebytere** [comment]
[The Embedder's POV](https://github.com/codebytere/gives-talks/blob/master/node-collab-summit-2018/the_embedders_pov.pdf)

**Comment by davisjam** [comment]
- [Academic perspectives on Node.js](http://people.cs.vt.edu/~davisjam/downloads/misc/Davis-NodeJSInteractive-AcademicPerspectivesOnNode.pptx)
- [Benchmarking and Performance WG](http://people.cs.vt.edu/~davisjam/downloads/misc/Davis-NodeJSInteractive-BenchmarkingAndPerformanceBreakout.pptx)

**Comment by kjin** [comment]
[Diagnostics WG Agenda 2018-10-12](https://docs.google.com/a/google.com/presentation/d/e/2PACX-1vS19WYtuxxx6I7_Y7Qy7c4wLARbKEcveYsY-8XgBes0YTVw70j3x22KBltaUGGTNa73TIET6Vvx7Cw7/pub?start=false&loop=false&delayms=3000)

**Comment by ErickWendel** [comment]
> The Embedder's POV

On agenda, you have another talk at `3:30- main- Embbeding`. Is it the same?

**Comment by ErickWendel** [comment]
> Gist with examples of Postmortem with Promises: https://gist.github.com/mmarchini/1f7476e0ee21a1f17832971289c3f4b5

I didn't find this talk on the agenda. What is the day and hour of this presentation?

**Comment by ErickWendel** [comment]
Talks that are missing:

@hashseed 
@ssuresh
@uttampawar
@MylesBorins 
@amiller-gh
@BridgeAR 
@joyeecheung 
@mhdawson
@apapirovski
@Fishrock123 
@mafintosh

Thank you guys!!

**Comment by codebytere** [comment]
@ErickWendel the 3:30 was a breakout, not a talk :)

**Comment by amiller-gh** [comment]
Website Redesign: https://docs.google.com/presentation/d/1kHsqeQxg1lxWUvz4pVENsK9wY4FFFzeUORD-UwYfrNo
