### ISSUE TITLE
Make Collaborator Summit for $Foundation, not just Node.js

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#136]
I was chatting with @MylesBorins the other day, and we thought it might be a very good idea to hold Collaborator's summit for the whole joined $FOUNDATION instead of just Node.js.
I think having the broad collaborators spectrum at Node+JS interactive was well received.

What do you think?

cc @nodejs/bootstrap for awareness.

**Comment by benjamingr** [comment]
I think it really depends on the agenda. There were some sessions in Berlin last year that could have used contributors external to core while there were others where it didn't make sense.

I think it really depends on the goals.

**Comment by joyeecheung** [comment]
If we are planning agenda beforehand and wish to stick to that, having more people in sessions (who probably don't work on the same piece of code) can make it more challenging to come out with anything actionable, and it may be less productive than discussing the matters on GitHub asynchronously.

However if we are making the summit more casual and creating more slots for hallway chats then this could enable conversations that are otherwise not likely to happen on GitHub (as there are too many issue trackers and some of them are too noisy)

**Comment by ljharb** [comment]
Shouldn’t that wait until the joined foundation is named, exists, and has all its processes fully finalized?

**Comment by boneskull** [comment]
:+1: would love this, and could use it as an opportunity to work with other contributors to not-Node.js $foundation projects (including my own).

**Comment by jorydotcom** [comment]
@ljharb not necessarily - we need to work on a rough plan for the summit so we can request budget from our respective boards; also I think we can use the Summit to collaboratively work on "finishing the bake" of some of the programs we're cooking up via the bootstrap process. If the summit is in later spring, I expect the bylaws for the new foundation to be done by then but there will still be a lot of other projects we can work on across the communities!

**Comment by joyeecheung** [comment]
The next summit will probably be in June: https://github.com/nodejs/summit/issues/135

Although I believe for the Berlin summits adjacent to JSConf EU, we had never been limiting the attendance to Node.js collaborators in any way, and in practice we welcomed everyone to join if they are interested even if they don't work on Node.js - we just don't explicitly promote the event that way, nor were we deliberately boardening the topics to anything other than Node.js .

**Comment by ljharb** [comment]
@jorydotcom Totally makes sense that planning needs to be started early. It does seem to me like marketing an event without a clear name, and asking for expensing approval for an unnamed event for a foundation one's company can't yet join, would be more difficult than if it had a name.

**Comment by mcollina** [comment]
If we decide to do this, we should do:

a. ask which projects in JSF would like to participate - some might not.
a. a call for proposals for sessions.
b. ask the community to up/down vote the sessions, and use the tool @joyeecheung created for Vancouver to reduce the amount of overlap.

As an example, in Vancouver the Modules team did not have quorum. So, each project/team/wg should decide if they would like to participate and in what numbers. Then, we create a shared agenda.

IMHO there should be some space for an "hallway chat".

**Comment by jorydotcom** [comment]
@mcollina I think there will be different levels of interest based on project (from the JSF side) - I think they will almost all be interested at some level, though. It would be good to get a sense of how the collab summit has proceeded in the past (I have never been able to attend a whole summit!) so we can do some brainstorming on our side.

**Comment by joyeecheung** [comment]
@jorydotcom This is the agenda of the last summit: https://github.com/nodejs/summit/blob/master/2018-10-Vancouver/agenda.md
And this is the agend of the last one near JSConf EU: https://github.com/nodejs/summit/issues/60

Though we are always trying to improve the format of these events, and the one near JSConf EU is usually a bit different from the one near JS/Node Interactive. AFAIR, Berlin 2018 was quite different from Berlin 2017 and so was Vancouver 2018 from Vancouver 2017.

**Comment by mcollina** [comment]
I think we are improving at each iteration :).

**Comment by mcollina** [comment]
This can be closed! We have OpenJS Foundation now.
