### ISSUE TITLE
Post Mortem - 3 Months Later

### ISSUE THREAD

**Issue by mikeal** [nodejs/summit#14]
What has been the most obvious and lasting effects of the last summit?

What are we lacking and would want to see from a future summit?

**Comment by jasnell** [comment]
We had a number of follow up actions generated at the summit but it's not clear now what those were and how we're doing on them. We likely need to make sure we have a solid follow up plan in place for the next one.

**Comment by rvagg** [comment]
> What has been the most obvious and lasting effects of the last summit?

1. Improved personal relationships between team members who were able to meet in-person for the first time at the summit. I've felt this and believe I've seen impact of it across the team.
2. Improved sense of ownership of the project by some attendees; this is purely a gut-feel thing and I can't point to anything specific but I believe I've seen some members become much more attached to what we're doing and throw themselves in even further, particularly those not already in the _inner circle_.

**Comment by Fishrock123** [comment]
lol I didn't even know this existed..
