### ISSUE TITLE
Agenda for Berlin 2019 needs a Code of Conduct section plus enforcement contacts

### ISSUE THREAD

**Issue by keywordnew** [nodejs/summit#140]
See: https://github.com/nodejs/summit/pull/139#discussion_r247055587

The agenda available through #139 needs a new section for a Code of Conduct. We're also making the enforcement contacts available ahead of time instead of letting participants know on the day of.

**Comment by ladyleet** [comment]
I'll take care of this! :)

**Comment by ladyleet** [comment]
@keywordnew how does this look? https://www.eventbrite.com/e/openjs-collaborator-summit-tickets-55985971548

**Comment by keywordnew** [comment]
@ladyleet reads as super thorough! Thank you for pulling this together 🙏🏽

**Comment by LaRuaNa** [comment]
> @ladyleet reads as super thorough! Thank you for pulling this together 🙏🏽

+1 super cool :] 👍

**Comment by ladyleet** [comment]
Great! Credit to @evahowe as well for facilitating.

**Comment by leahecole** [comment]
@ladyleet could this also be added to the agenda.md for easier during conference access?

**Comment by mcollina** [comment]
Definitely, would you like to send a PR?

**Comment by leahecole** [comment]
@mcollina #176

**Comment by ryzokuken** [comment]
Merged! 🎉
