### ISSUE TITLE
Berlin 2019 - Workers

### ISSUE THREAD

**Issue by benjamingr** [nodejs/summit#141]
@addaleax @nodejs/workers 

I think it could be great if we had a session about `worker_threads`, discuss graduating them and look at what people are building with them. 

Assuming @addaleax is attending it could be a great chance to look at where we are.

**Comment by addaleax** [comment]
Sounds good!

Personally, I would like to see Workers graduate from experimental status as part of the Node 12 release. At this point I still think that that’s realistic :)

**Comment by jorydotcom** [comment]
just documenting that this session has been added to the working agenda, thanks!

**Comment by trivikr** [comment]
Do share the zoom link (if available) here when the session starts at **CEST Thu 30-May-2019 17:00 (05:00 PM)**

**Comment by trivikr** [comment]
Time: **CEST Thu 30-May-2019 17:00 (05:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by keywordnew** [comment]
Closing as this event is complete :)
