### ISSUE TITLE
Sponsorship Prospectus for Node + JS Collab Summit 2019 - Who wants to create?

### ISSUE THREAD

**Issue by ladyleet** [nodejs/summit#142]
Putting this out there that it would be great to have this completed this week if possible. Getting inquiries!

**Comment by ladyleet** [comment]
@tzmanics if you're interested :P

**Comment by tzmanics** [comment]
I can definitely get on this. Are there any existing prospectuses that should be based off/similar to? Like Node Interactives : https://storage.pardot.com/6342/196060/sponsor_js_interactive18_101218.pdf

**Comment by ladyleet** [comment]
i feel like maybe we created one before? but really we are just looking for dinner and food sponsors and a simple one pager. i'm not 100% sure if we are looking for cash sponsorships, but i'm thinking no as there is no good way to collect the $. maybe @jorydotcom @keywordnew @mcollina can chime in here.

**Comment by ladyleet** [comment]
@tzmanics we are trying to have something soon as we have people interested! we can continue reqs and thread here.

**Comment by mcollina** [comment]
We have a couple of things that would be nice to cover

* a party/reception for one of the nights
* boost of the travel fund
* the venue itself, even if money for it is available through the Foundation

IMHO we should look for either cash sponsorship, or a few reception/party sponsorship. Accepting cash is typically easier to coordinate.

**Comment by tzmanics** [comment]
Are there any resources for stats or information on summit audience that I can use to put this together? Or is there someone I should reach out to that has the info?

**Comment by mcollina** [comment]
Here are the attendees for last year: https://github.com/nodejs/summit/blob/master/2018-05-Berlin/attendee-rsvp.md#attendees-in-person.

**Comment by tzmanics** [comment]
@mcollina is there a simple, straight-forward way to just ask for cash sponsorship that you've done in the past?

I put together some main text and a few options. I'm completely open to any changes, ideas or comments. Thanks in advance!

> The Collaborator Summit brings together developers who work to advance and build the Node code base and its community. In its fifth year the summit will be connecting collaborators from the Node + JS Foundations in a mix of presentations and interactive sessions lead by some of the most well-known developers in the Node and JavaScript ecosystem.
> 
> We have a few sponsorship opportunities available for this influential summit. 
> 

Options (we can do a combo of these):

**A (Tiered):**
Bronze - $1000
Silver - $5000
Gold - $10000
Platinum - $20000

**B (Event Driven):**
Sponsor the Collaborator Summit Reception - $TBD
Travel Sponsors - $500-1000
Venue Sponsors - $TBD

**C (Form):**

> If you’re interested in collaborating with The Collaborator Summit as a sponsor please fill out our sponsor form or contact us at this@email.com.

(a form like → https://docs.google.com/forms/d/e/1FAIpQLSeSDCFHJQ5AoBbgVillvOlVtHtWOnIPggopeO2eZy086xuwuQ/viewform)

**D (Item-based):**
Lanyard - $1000
Charging Station - $1000
Summit T-Shirt - $5000

I also have a few questions:
- Do we have any incentives/marketing opportunities we're exchanging for sponsorship?
- What format do you want this in?
- Are there any pictures from past Summits we can use?
- Is there a budget or amount of funds we're trying to reach?

**Comment by mcollina** [comment]
I think we are going for event-driven. (B)

> * Do we have any incentives/marketing opportunities we're exchanging for sponsorship?

I'm happy whatever they would like. If they would like to have a small booth or a 5min talk, I'm good for both.

> * What format do you want this in?

what do you mean? Maybe a slide deck on google presentation?

> * Are there any pictures from past Summits we can use?

I might have some pictures from last year. Where should I send it?

---

@ladyleet do we still need this? I think we have one sponsor lined up for the reception.

**Comment by tzmanics** [comment]
Thanks, @mcollina! Format-wise I wasn't sure if you wanted a PDF or like .md, etc.
If you could just send pics to tzmanics@gmail.com, that would be great 👍

**Comment by mcollina** [comment]
I can't seem to be able to find the pictures :/. I also sent them to somebody, but I can't remember who :/.

**Comment by thekaeway** [comment]
Hey @tzmanics, I know you were looking forward to images, other than that were you able to finish the sponsorship tiers? We currently have someone waiting to read the sponsorship packages. LMK if there is anything @ladyleet or I can do on our side. Thanks in advance :)

**Comment by tzmanics** [comment]
I pressed pause on this after this comment:
> @ladyleet do we still need this? I think we have one sponsor lined up for the reception.
But I can definitely resume now  👍

**Comment by ladyleet** [comment]
@tzmanics yes something super simple really with just tiers of what people get.

**Comment by tzmanics** [comment]
@ladyleet Will do. Is there a list of what we want to offer sponsors for each tier?

Here are a few suggestions @mcollina wrote a few days ago:
> I think we are going for event-driven. (B)

>> Do we have any incentives/marketing opportunities we're exchanging for sponsorship?

>I'm happy whatever they would like. If they would like to have a small booth or a 5min talk, I'm good for both.

**Comment by ladyleet** [comment]
all those seem completely fine! :)

**Comment by ladyleet** [comment]
@tzmanics we don't have a specific list so you can just make stuff up that seems simple enough to offer

**Comment by tzmanics** [comment]
@ladyleet @thekaeway here's a google doc of what I have so far:
https://docs.google.com/document/d/16knTEy7qYhSiZv00fcZqFKKrqOOj4KWS-o5OrDbra6I/edit?usp=sharing

I wasn't sure about numbers and made up a few items. I also started on the 'Event Driven' section but can leave that out if we just want to stick to tiered.

Feel free to make changes or add comments of things for me to change.

**Comment by ladyleet** [comment]
@tzmanics made edits! :) @keywordnew @mcollina we should review tomorrow! :) 

https://docs.google.com/document/d/16knTEy7qYhSiZv00fcZqFKKrqOOj4KWS-o5OrDbra6I/edit // @thekaeway

**Comment by trivikr** [comment]
@tzmanics I'd twitted some pics from Vancouver Collab Summit in October 2018 (if they can be of some help) https://twitter.com/search?q=from%3Atrivikram%20%23CollabSummit

**Comment by WaleedAshraf** [comment]
closing as the summit is over. 👍
