### ISSUE TITLE
Calendaring Dates, Berlin 2019

### ISSUE THREAD

**Issue by jorydotcom** [nodejs/summit#143]
At our meeting today we talked about putting deadlines in calendars for key points, but we ran out of time to do this synchronously. We need dates for:

* CFP Opens: ASAP!
* CFP Closes: April 20?
* Registration Opens: ASAP!
* Sessions Selected: April 30?

(Edited as comments come in)

**Comment by mcollina** [comment]
I think we should keep a more un-conference style, so I would not have an "Agenda Set" date, but the agenda would be a living document that we will adapt during the course of the two days.

I would have a "session selected" 1 month before the event, leaving some slots free for last minute topics.

I would not have a "registration closes" date.

Based on that, I would open the CFP as soon as possible, and close it mid-april. What do you think?

**Comment by jorydotcom** [comment]
That sounds fine to me - I added April 20 and April 30 as some guidelines for closing the CFP and selecting sessions... does that sound doable?

Also cc'ing @keywordnew on this!

**Comment by keywordnew** [comment]
Rad, rad, rad @jorydotcom @mcollina!! 💯 Posted the [cal](https://docs.google.com/spreadsheets/d/1r5am7B7eczC5OpkpZsyoU71LHrWS6fUS1gvDFfR1ifw/edit#gid=1481053507) in the [other thread](https://github.com/nodejs/summit/issues/135#issuecomment-465655865). Updating with these dates.

**Comment by keywordnew** [comment]
CFP is tentatively (denoted by preceding `?`) set to open March 1.

**Comment by keywordnew** [comment]
Seems like some people will need to put in their travel fund submission after their session is selected. But being approved for funds less than 4 weeks before arrival dates seems like too short a time for people to sort logistics.

Can we commit to having sessions announced sooner so that people have more breathing room to get book time away, their flights, their accommodations, and their visas?

**Comment by mcollina** [comment]
IMHO the collaborator summit is about collaboration. If you plan to come only if your session is selected, it would leave me puzzled.

Most years we didn’t have an agenda at all, and people came. The overall point is to get together: what we will be talking to depends on the interests of those who are coming ;). 

It should be the other way around: it’s time to book travel folks, let’s meet in Berlin!

**Comment by keywordnew** [comment]
Well said, Matteo! 👍🏽

**Comment by Trott** [comment]
Is this issue closable at this point?

**Comment by keywordnew** [comment]
Yes, we seem well past this point.
