### ISSUE TITLE
Summit topic: Build with GN

### ISSUE THREAD

**Issue by hashseed** [nodejs/summit#144]
Chromium and V8 have departed from GYP and switched to GN three years ago. Node.js however still heavily relies on GYP. This topic has been [discussed](https://docs.google.com/document/d/1gvHuesiuvLzD6X6ONddxXRxhODlOJlxgfoTNZTlKLGA/edit) time and again, without a satisfying solution.

To be able to test V8 against node in continuous integration, the V8 team relied on a hybrid build that frequently breaks. So we spent some time to port all of Node.js to GN. It took a lot less time than expected, and also comes with nicer dependency management.

I'd like to present the background, the results, and how we got there, to incite some discussions on whether this is a viable solution for upstream Node.js.

**Comment by jorydotcom** [comment]
just documenting that this has been added to the working agenda, thank you!

**Comment by trivikr** [comment]
Time: **CEST Fri 31-May-2019 15:00 (03:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by hashseed** [comment]
Slides: https://docs.google.com/presentation/d/1CzFStQ844CeGbQz7u4BtWG0JHn-EOyhz4EqNXwVWhgg/edit

**Comment by keywordnew** [comment]
Closing as this event is complete :)
