### ISSUE TITLE
Summit topic: Bootstrap of Node.js Core

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/summit#147]
The bootstrap of Node.js had grown organically over the past few years, interleaving setup of globals, processing of CLI options and environment variables, and selection of execution mode across multiple files, both in JavaScript and in C++. This introduces difficulties for several efforts, e.g. [V8 snapshot integration](https://github.com/nodejs/node/issues/17058), [better embedder API](https://github.com/nodejs/node/issues/23265).

We recently started to refactor the bootstrap process with at least two goals in mind:

1. Create a point where an environment-independent V8 snapshot can be captured.
2. Makes it possible to execute JS scripts with a properly bootstrapped Node.js context from C++, so that we can create cctests for this kind of execution, and eventually deprecate `_third_party_main` (https://github.com/nodejs/node/issues/24017).

In this session we will look into the general ideas behind the recent refactor, the current state of the bootstrap process, and discuss about work that needs to be done to achieve the goals mentioned above (or, if they are done by the time of the summit, just give an introduction about the internals and the principles that need to be followed when growing the bootstrap process).

**Comment by suresh-srinivas** [comment]
https://github.com/nodejs/node/issues/27196

**Comment by jorydotcom** [comment]
just documenting that this has been added to the working agenda, thank you!

**Comment by trivikr** [comment]
Time: **CEST Fri 31-May-2019 16:00 (04:00 PM)**
Zoom link: https://zoom.us/j/372142646

**Comment by joyeecheung** [comment]
I've uploaded the slides in [here](https://github.com/joyeecheung/talks/blob/master/openjs_collab_summit_201905/bootstrap-of-node-core.pdf) (there may still be changes before I actually give the talk tomorrow)

**Comment by benjamingr** [comment]
@joyeecheung very good session and slides! It was an interesting and succinct overview.

**Comment by zackschuster** [comment]
@joyeecheung thank you for posting the slides here -- gives me a nice high-level overview of what the effort/blockers are :)
