### ISSUE TITLE
Summit Topic - Module ecosystem and Package maintenance effort

### ISSUE THREAD

**Issue by mhdawson** [nodejs/summit#148]
Use the summit as an in-person opportunity to discuss the work by the https://github.com/nodejs/package-maintenance team.

@mcollina

**Comment by jorydotcom** [comment]
just a note that this session has been documented in our agenda planning - thank you!

**Comment by trivikr** [comment]
Time: **CEST Fri 31-May-2019 16:00 (04:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by Eomm** [comment]
I'm coping the main post from https://github.com/nodejs/summit/issues/159

> Session Name: Package maintenance
> Format: Round table discussion
> Goals: Evanglise the efforts of the package maintenance team, discuss key work items, and connect with and get feedback from package maintainers.
> Who should attend: Members of the package maintenance group, Node.js collaborators concerned with the use of packages with Node.js, JS package maintainers, JS project collaborators concerned with how modules are supported by their projects.
> Agenda/session outline:
> 
> outline of approach, current work and status
> agenda bashing
> follow agenda

As track I would propose:
- guidelines
  - docs
  - `support` tag
- pilots packages
- what packages we should help? - definitions of high impact https://github.com/nodejs/package-maintenance/issues/143
- tools
  - `support` validator
  - `support` appender (cooming soon)
  - badges
  - helper (from pilots packages

**Comment by craftninja** [comment]
🍝 Copy pasta-ed here: https://slides.com/emilyplatzer-1/openjscollabsummitberlin2019

**Comment by zackschuster** [comment]
is the `support` proposal stable enough for library authors to use? i would like to include this in one of my repos, but i'm not sure/i don't think i can keep track if there are going to be many changes.

**Comment by Eomm** [comment]
That spec is still in draft, and after the feedback received at the summit, we will apply some changes for sure.

So I would suggest to don't use it right now.

**Comment by zackschuster** [comment]
@Eomm thanks!

**Comment by keywordnew** [comment]
Closing as this event is complete :)

**Comment by WaleedAshraf** [comment]
closing as the summit is over. 👍
