### ISSUE TITLE
Call for Sessions: Berlin Collab Summit

### ISSUE THREAD

**Issue by jorydotcom** [nodejs/summit#149]
We're experimenting with a [Google Form for session submissions](https://goo.gl/forms/am0v5njskQnABQMO2) this year - we're hoping that this will help us reach more into the JS Foundation project communities and provide an easier view of all the potential sessions. As with previous years, you welcome and encouraged to use GH issues on this repo to organize your session, and you are able to [view all submissions](https://docs.google.com/forms/d/1GCVcmMKplbhbn1qlESg7fwsxdmP3qHTvW3J2ZTmwCFs/edit#responses).

The summit will be May 30-31 at Courtyard by Marriot, Berlin City Center. The call will be open until at least April 20 (per #143) but we may extend that as needed. As @mcollina says, this is about collaboration so we are inclined to be flexible... _"it’s time to book travel folks, let’s meet in Berlin!"_

**CFP Link**
[https://goo.gl/forms/am0v5njskQnABQMO2](https://goo.gl/forms/am0v5njskQnABQMO2)

*Venue updated with confirmed info from #157*

**Comment by mhdawson** [comment]
If we already opened a GH issue with a suggestion do we need to submit through the form as well?

**Comment by jorydotcom** [comment]
@mhdawson if you don't mind, otherwise I am happy to add it for you!

**Comment by mhdawson** [comment]
@jorydotcom thanks for the response.  I think there may be more suggestion so I'll try to add it in the tool when I do those as well.

**Comment by Trott** [comment]
@keywordnew Is the `tsc-agenda` label on this for visibility (that is, to make sure the TSC knows about this) or is there something that TSC needs to do or decide?

**Comment by keywordnew** [comment]
@Trott thank you for pinging to clarify. It's for visibility. So people see it sooner then have plenty of time to submit and/or make travel fund requests in these 2 months leading up to the next Collab Summit.

**Comment by Fishrock123** [comment]
I'd like to be clear that if this is a _collaborator summit_ there should **not** be conference-like workshops aimed at non-collaborators.

As such I would strongly object to running stuff like this at the event:

> We have a ~3-4 hour workshop for how to get started with modern Dojo. We have a lot of users in Germany and it would be a great opportunity to get them to the event to learn more about the foundation and to get them up to speed with the new Dojo.

**Comment by Trott** [comment]
Mentioned at TSC meeting today, removing `tsc-agenda` label. Feel free to re-add it if there's more for the TSC to do, of course.

**Comment by keywordnew** [comment]
Removing this from the CommComm agenda. There is an existing Collab Summit update issue that remains open for regular discussion.

**Comment by keywordnew** [comment]
Anyone who wants to can still submit a session proposal for the Collab Summit using [this issue template](https://github.com/nodejs/summit/issues/new?template=summit-topic-proposal.md).

**Comment by joyeecheung** [comment]
Where is the source of truth for a list of proposals? The issues here or the Google form? There seem to be some proposals that only live in one of them.

**Comment by jorydotcom** [comment]
@joyeecheung we are periodically moving proposals from GH into the response sheet [here](https://docs.google.com/spreadsheets/d/12T4VcSW5dW7whAB2pEnqHhUts-s2Bczv8gLvtsOeI24/edit#gid=1638211295). It's the source of truth we'll use to make sure all the proposals are evaluated and added to the agenda!

**Comment by boneskull** [comment]
I wanted to lead a meeting for the [tooling group](/nodejs/tooling) and have submitted a proposal to that effect.  Should I be worried about not getting a slot for this?

**Comment by benjamingr** [comment]
> Should I be worried about not getting a slot for this?

In the past, slots were never a problem and we just split into more groups when we needed to do several things.

**Comment by obensource** [comment]
@mcollina awesome! I'd love to lead a breakout session for members of the [i18n](https://github.com/nodejs/i18n) WG, to cover how we can continue to push forward efforts like:

* l10n: CommComm Initiatives for internationalizing the API docs, and the website redesign project.
* Intl in Node.js: How the i18n WG can focus on supporting current [Intl development](https://github.com/nodejs/node/tree/c80c414027307da5b3135d3452f8e6f792a121c0/deps/icu-small/source/i18n) in node core, and get more folks to help out with the [core WG](https://github.com/orgs/nodejs/teams/intl).
* The i18n WG's role in [ECMA 402](https://github.com/tc39/ecma402): How we can scale the i18n WG's involvement and support for tc39 in ECMA 402, and what the current needs are that Node.js representatives can fulfill for pushing JavaScript's [Intl specification](https://tc39.github.io/ecma402/) forward.

cc @nodejs/i18n @nodejs/intl @zeke @vanessayuenn @srl295 @littledan @watilde @RichardLitt @TiagoDanin @JCMais @maddhruv @lukaszewczak

**Comment by evahowe** [comment]
Hello all!  I work with Tracy and I am in the process of updating the agenda and pulling in the topics that I currently have.  @joyeecheung and @boneskull I have both of your proposals on the draft agenda.  @obensource what would you like to call yours and how much time would you like?

**Comment by obensource** [comment]
@evahowe I believe we've covered all the bases in our convo in https://github.com/nodejs/summit/issues/164. 🎉

Re amount of time: We'd love to have enough time to make headway on a few things, I'm guessing the typical amount of time allocated for other standard meetings would probably work for us? Thoughts? Thanks a million! 🙌

**Comment by keywordnew** [comment]
We'll do our utmost to get everyone a slot and as much time as possible. 

There's also a room specifically allocated for unscheduled discussions, which if available could also be used for discussions that are overflowing their time.

**Comment by littledan** [comment]
Where can we find the draft agenda?

**Comment by mcollina** [comment]
@littledan our draft is in: https://docs.google.com/spreadsheets/d/14NvqXdtcQkh21U3mdqQuR24oQeUmGDWHer373swQGvg/edit#gid=674659463

---

The cfp *will close* on Monday 20th of May.

**Comment by hekike** [comment]
@mcollina the User journeys session and @mhdawson's session are at the same time, can we swap around to avoid conflict? Micheal is involved in the User journeys Initiative and Best Practices which are related to each other.

**Comment by gireeshpunathil** [comment]
@mcollina - also, my second session (30/05 4 PM main hall - Discuss pain points of Node.js users)
is redundant to first one (30/05 10 AM munich1 - insights from nodejs/help repo) - not sure how I ended up submitting twice! You may please retain the 10AM one and release the 4PM one for some other topics, thanks!

**Comment by keywordnew** [comment]
@hekike done. 👍🏽

@gireeshpunathil thank you for the specifics! Done.

**Comment by WaleedAshraf** [comment]
@keywordnew I think it'd be good to avoid as many conflicts as we can. And only squeeze when there are more sessions.

**Comment by hekike** [comment]
@keywordnew Thanks!
