### ISSUE TITLE
Collaborator Summit at Node.js Interactive 2016

### ISSUE THREAD

**Issue by mikeal** [nodejs/summit#15]
Heya, I'd like to resurrect the Collaborator Summit to run either before or after Node.js Interactive in Amsterdam and Austin.

This was an un-conference for Node.js Contributors that I think we should try to run again.

We'll need to figure out how we are structuring this and what the criteria for admission because what we did last time won't scale the size the collaborator base is now.

We also have some budget for sending people if you need it. We'll want to figure out how many people need it and then design a criteria for accepting. We also need to figure out how many rooms and what size for budgetting as well.

**Comment by jasnell** [comment]
SGTM. Let's do it. Either venue should work for me.

**Comment by mikeal** [comment]
We should probably do this at both events.

**Comment by iancrowther** [comment]
sweet

**Comment by mcollina** [comment]
this is an awesome idea!

How about we do something at both? Maybe one is more official, but there should be a collaborators moment in the other as well (just because there will be someone that couldn't attend both).

**Comment by jasnell** [comment]
@mikeal ... thinking more about the working group / subsystem specific meetings... would it make sense to actually begin baking the collaborator summit stuff directly into the Interactive events moving forward? In other words, make it part of the official agenda of the Interactive event as working sessions for Node collaborators.

**Comment by mikeal** [comment]
@jasnell so, we can definitely bake it in going forward, but we probably want to separate it a little bit just so that having a ticket to Interactive isn't a barrier to being involved in the summit stuff.

**Comment by jasnell** [comment]
Agreed.

**Comment by mcollina** [comment]
@mikeal I think it would not be nice if someone flies in to join the collaborator summit (funded by the foundation, maybe) and then he couldn't afford the interactive ticket. Most conferences allows volunteers to help, maybe something similar could be arranged for collaborators as well. Or a limited number of "sponsored" tickets. However, I'm not sure if this is feasible budget-wise.
