### ISSUE TITLE
OpenJS Collab Summit 5/30-31 - Venue - Registration 

### ISSUE THREAD

**Issue by ladyleet** [nodejs/summit#152]
OpenJS Collab Summit officially has a venue and is open for registration!

Please socialize and register immediately if you know you are going so we can get an accurate headcount!

Venue: [Marriott Courtyard Berlin City Centre](https://www.marriott.com/hotels/travel/bermt-courtyard-berlin-city-center/?scid=bb1a189a-fec3-4d19-a255-54ba596febe2
).
Registration: https://www.eventbrite.com/e/openjs-collaborator-summit-tickets-55985971548
Password: collabsummit
Call for Papers: https://goo.gl/forms/NAfsjm3O2CYxmKvc2

Volunteers: We will work publicly on the agenda: if you are interested, we meet every week. Follow along or join us! https://github.com/nodejs/summit/issues/135

To get your visa for this event: Email visainfo@nodejs.org and cc ladyleet@nodejs.org after registration!

**Comment by ladyleet** [comment]
@keywordnew @mcollina @LaRuaNa @MylesBorins @hackygolucky @dshaw @bnb please socialize! :)

**Comment by mcollina** [comment]
cc @nodejs/collaborators do you plan to come and/or present to the Collaborator Summit? Sign up!
