### ISSUE TITLE
Summit topic: Deprecations future

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/summit#153]
So far our user experience was partially meh, when it comes to deprecation warnings. We often struggle with deprecations due to our very heterogeneous users. There is often a gap in the requirements for e.g., CLI users, big companies that want the most reliable and safe way doing things, individuals who e.g., write a small script and so on. Most important though: we mainly reach the wrong people when printing our deprecation warnings. In general there are lots of pros and cons with deprecations.

That's why I would like to brainstorm what we could do to:

* reach the right people
* improve the average experience for all users
* still have a good way to improve the Node.js code base 

So far I already thought about e.g., using a Node.js survey to gather further data and to figure out what our users actually believe and also about add an option to opt-into providing data when it comes to deprecations or other usage data.

This is very likely not an easy task and I ask not only Node.js collaborators to join but people who e.g., have run into deprecation warnings before, who found them distracting, great, weird and people who have e.g., strict requirements in companies. I believe we need a lot more feedback on this topic! If anyone has a lot of experience in this field, great, please join this session!

**Comment by BridgeAR** [comment]
One thing I would like to also do in this session is going through all our current deprecations and determine if the deprecation really makes sense or not or if we want to remove the feature or not including a short risk summary by using https://gzemnid.nodejs.org.

One thing we might be more careful about in the future are non-underscore aliases, e.g., `os.tmpDir()`. Those are pretty cheap to maintain and removing them might not be worth it.

**Comment by mhdawson** [comment]
+1 the key thing for me is what can we do to reach the right people without impacting end users.

**Comment by BridgeAR** [comment]
@nodejs/package-maintenance this should likely be important to you and it would be great if people active in that working group could join this session :)

**Comment by ghinks** [comment]
Hello @BridgeAR indeed you are correct. It would be good to talk. I think you would like to hear what actually happens at some of the larger organizations at the summit. I'm going to reach out to a couple of people.

**Comment by BridgeAR** [comment]
Here is a rough agenda: https://docs.google.com/document/d/1aBlgJRkvokGcALUCQqiUQ4SRcJ_ivHN0JhiI7u208Uc/edit?usp=sharing

Please add suggestions / comments in case anyone misses something or thinks something should be changed / reworded.

**Comment by jorydotcom** [comment]
Just documenting here that this topic has been added to the working agenda! Thank you!

**Comment by trivikr** [comment]
Is this session going to be recorded for viewing later?
If yes, please share the link once it's complete

**Comment by trivikr** [comment]
Time: **CEST Thu 30-May-2019 12:00 (12:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by benjamingr** [comment]
https://docs.google.com/document/d/1VzK4N_4v55d-tLIUu0XxLAH5ixD0YCEDp-RA3Crnsn4/edit cc @joyeecheung

**Comment by bnb** [comment]
Going to close since this is for a past event 👍
