### ISSUE TITLE
Summit topic (?): AMA on core subsystems

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/summit#154]
I am not sure if I can lead a session like this so I did not submit a proposal to the google form, but anyway here is an idea I just randomly come up with:

1. Before the session, we go over the subsystem teams in Node.js core, and count attendance from the team members (or, we could just estimate based on...personal instincts)
2. For each subsystem that we have sufficient number of (>=2?) team members present, we ask them to go on stage (or wherever it's easy for them to grab the mic), and do an AMA (Ask Me Anything) for the subsystem. They should be free to open their laptop to find answers (maybe that would lead to some awkward silence, IDK, this is just a rough imagination in my head). If they are not sure about the answer, anyone is free to speak up.

If it feels too stressful, we could just be more casual somehow. The point is that we can learn from each other on subsystems in Node.js core and share knowledge. Also we could try to make it fun and chill and interesting for even non-collaborators.

**Comment by mcollina** [comment]
I’m in! It’s a nice one

**Comment by keywordnew** [comment]
Excellent!

**Comment by tniessen** [comment]
Love the idea.

**Comment by sagirk** [comment]
Brilliant idea! ❤️ 

Would love for this to happen. 👍

**Comment by jorydotcom** [comment]
recorded this topic idea in the Agenda planning doc; lmk if someone plans to lead/facilitate!

**Comment by keywordnew** [comment]
Please message me if you read this and want to participate in the AMA! 

It could be one person, it could be a couple of folks together, answering questions from the audience casually about your subsystem. You could def have your machines open.

I'm collecting a list of folks who want to share knowledge. Like Joyee said earlier, the point is **to learn from each other on subsystems in Node.js core**.

**Comment by mcollina** [comment]
I'm happy to participate for streams, http, and http2.

**Comment by apapirovski** [comment]
@keywordnew happy to participate for `events`, `http2` & `timers`. (and I guess `process`, mostly as pertaining to the task queues and the event loop.)

**Comment by gireeshpunathil** [comment]
`report`, `embedding`, `child_process`, `shared_lib`, `libuv`

**Comment by joyeecheung** [comment]
Maybe we can go the other way around and organize the session based on questions being asked instead of people who can answer them?

**Comment by keywordnew** [comment]
To confirm, the AMA is scheduled for [11:30 in the Main room](https://docs.google.com/spreadsheets/d/14NvqXdtcQkh21U3mdqQuR24oQeUmGDWHer373swQGvg/edit#gid=674659463&range=B9) :)

**Comment by trivikr** [comment]
Zoom link: https://zoom.us/j/381668642

**Comment by keywordnew** [comment]
Closing as this event is complete :)
