### ISSUE TITLE
Summit topic proposal: Security, modules and Node.js 

### ISSUE THREAD

**Issue by guybedford** [nodejs/summit#155]
I think it could be interesting to discuss modular package security in Node.js and npm including various concepts around least authority and the ecosystem in general. I don't have any exact proposals, ideas or suggestions apart from simply wanting to look at and discuss some of the major directions Node.js might consider in moving to a more secure ecosystem in future, including in relation to browser security, what Deno is doing, and WASM / WASI security as well.

I am by no means an expert on any of these topics, but could give a very brief overview of some of the considerations and questions, before opening up to further discussion and feedback for the major part of the session.

As security is such a complex and wide-reaching topic, I think it would be useful to be able to have a session like this at the summit where hopefully many different perspectives can be brought to these discussions.

Slides: https://docs.google.com/presentation/d/1VUpxoxitZCINJI7jXec4i87YiYZsXr8pCSHdHY5pW30/edit?usp=sharing

**Comment by benjamingr** [comment]
@lirantal

**Comment by lirantal** [comment]
Thanks @benjamingr 
I unfortunately can't make it to the one in Berlin but have pinged the @nodejs/security-wg on the issue queue to see our availability for that.

Thanks for bringing these up @guybedford, they are interesting topics plus we have quite a bunch on the issue queue but I like your suggestions that would benefit more of open discussion and feedback from the larger Node.js collaborators to collect opinions and touch some sensitive topics.

**Comment by vdeturckheim** [comment]
Unfortunately, I won't ne in Berlin either (collision with a talk I am giving somewhere else). 

But I'd be +1 for such session!

**Comment by mhdawson** [comment]
I'll be there :)

**Comment by mcollina** [comment]
Hey @guybedford would you mind to fill in https://docs.google.com/forms/d/e/1FAIpQLScneYhY4iqm8x2C2AO9EEzJ5smkOKhLqfxEMQcfNvP5rvXfHg/viewform? It'd be easier for scheduling for us.

**Comment by guybedford** [comment]
@mcollina sure I've posted the form. It seemed to default to the session suggestion page as mandatory when clicking "next", so I submitted an almost-serious suggestion topic too :)

**Comment by sam-github** [comment]
Is there someone who is going to speak on this topic, package security? I should be at the summit, but I don't have the packground to update anyone on the current state of things. If @lirantal and @vdeturckheim are also not there, who would do this?

**Comment by mhdawson** [comment]
What I suggest is that @lirantal and @vdeturckheim put together a short deck with an update on that front and either you or I can deliver it.

**Comment by jorydotcom** [comment]
just documenting that this has been added to the agenda!

**Comment by trivikr** [comment]
Is this session going to be recorded for viewing later?
If yes, do share the link once it's over

**Comment by trivikr** [comment]
Time: **CEST Thu 30-May-2019 14:00 (02:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by guybedford** [comment]
For those interested, the slides from the presentation can be found here - https://docs.google.com/presentation/d/1VUpxoxitZCINJI7jXec4i87YiYZsXr8pCSHdHY5pW30/edit?usp=sharing.

**Comment by WaleedAshraf** [comment]
closing as the summit is over. 👍

**Comment by keywordnew** [comment]
Closing as this event is complete :)
