### ISSUE TITLE
Summit topic: (form not working?)

### ISSUE THREAD

**Issue by mhdawson** [nodejs/summit#159]
I tried to submit through the form but after having gone through the submission it does not look like it ended up in the list.

This is the content of what I had submitted:

Session Name: Package maintenance
Format: Round table discussion
Goals: Evanglise the efforts of the package maintenance team, discuss key work items, and connect with and get feedback from package maintainers.
Who should attend: Members of the package maintenance group, Node.js collaborators concerned with the use of packages with Node.js, JS package maintainers, JS project collaborators concerned with how modules are supported by their projects.
Agenda/session outline:

outline of approach, current work and status
agenda bashing
follow agenda
Session leaders: Matteo Collina, Michael Dawson, (@nodejs/package-maintenance any other volunteers)
Resources to support my proposal: nothing special.

@mcollina @ladyleet 

ref: https://github.com/nodejs/package-maintenance/issues/189

**Comment by mhdawson** [comment]
I'll add that I think somebody else mentioned in the CommComm meeting that they'd had a similar problem when submitting through the form.

**Comment by keywordnew** [comment]
That's right. I'm unsure what is happening. I tested the form and found my test submitted. But this is now the second report of the same problem. Sorry this happened, @mhdawson, we def need to dig more into this.

**Comment by evahowe** [comment]
I will add your second session to the spreadsheet and agenda @mhdawson.  Do you have a time estimate so I know where to slot it in the agenda?

**Comment by mhdawson** [comment]
I think something like an hour assuming that is what other team/WG sessions are getting.

**Comment by keywordnew** [comment]
Anyone who wants to can still submit a session proposal for the Collab Summit using [this issue template](https://github.com/nodejs/summit/issues/new?template=summit-topic-proposal.md).

**Comment by keywordnew** [comment]
Closing as this is complete :)

**Comment by keywordnew** [comment]
FWIW, for the next we don't intend to use forms.
