### ISSUE TITLE
Node.js Collaboration Summit - Amsterdam Sept 17-18

### ISSUE THREAD

**Issue by mikeal** [nodejs/summit#16]
Finally, another Collaboration Summit!

Collaboration Summit is an un-conference for contributors to Node.js to get together and discuss Node.js :)

We have space for a few hundred people in the same venue as Node.js Interactive the two days following all the talks.

http://events.linuxfoundation.org/events/node-interactive-europe

Node.js Interactive attendees can join for no additional cost. If you are a committer and are not attending interactive we can register you just for the collaboration summit.

/cc @nodejs/members

### Content

The content is provided by the participants! Please use this issue to discuss any topics you might want to put on the agenda so that we can flush a few things out before the event.

### Travel Assistance

We have some budget to cover travel stipends but it is limited. Any contributors who can't make it without a stiped should comment on this issue and the TSC will give out the stipends where possible based on the budget restrictions.

I would also recommend that contributors in Europe only apply to the event in the EU and US contributors to the one in the US so that we can spread out the funds we have. If you do not live in either the EU or the US, please apply to whichever one you prefer. Also, anyone speaking at the event is already eligible for the same stipend so no need to apply here.

**Comment by eljefedelrodeodeljefe** [comment]
Will attend, even in case I can't attend Node Interactive. If anyone wants to share an AirBnB give me ping. 

**Topic Proposals**
* [modular core](https://github.com/nodejs/node/issues/7098). Maybe we see an eps from or with @dominictarr
* ChildProcess (v2)
* toolchain / build / build runner

**Comment by YurySolovyov** [comment]
@eljefedelrodeodeljefe did you meant possibly planned WebWorkers?

**Comment by mcollina** [comment]
I propose a session on streams. Possibly going through how the thing works internally.

I'm also interested in diagnostics, benchmarking, and performance in general.

Anyway, I'm in.

**Comment by mikeal** [comment]
@mcollina I think we should have a session called "So, what are we gonna do about streams?"

**Comment by eljefedelrodeodeljefe** [comment]
@YurySolovyov no (unless there is overlap). I rather mean something "So, what are we gonna do about child_process?", or "Node.js and systems programming". We'll see. I need to work on this myself first. 

+1 for @mcollina points.

**Comment by mcollina** [comment]
@mikeal LOL. Yes. Given that's the most legacy thing that is in Node.

**Comment by YurySolovyov** [comment]
I'm not sure this is a good place to ask, but will sessions be recorded? I can't attend, but would love to see them afterwards.

**Comment by lucamaraschi** [comment]
Life after death aka the future of post-mortem!

- Common Heap dump format
- Cross platform analysis tools

**Comment by mikeal** [comment]
@YurySolovyov the talks at Interactive are recorded but you can't really record unconf discussions. We considered this last time and decided against it in favor of just keeping quality notes.

**Comment by vladmiller** [comment]
Would be really interesting to hear about complex task processing, e.g. when you need to merge data from multiple sources and there are dozens of steps to complete the task and each step can fail. Like which tools to use, what if you need process millions of records, how to preserve state, how to recover state.

**Comment by mafintosh** [comment]
If there is a streams session I'll try to swing by.

**Comment by fibric** [comment]
@vladmiller Queues may help you today http://blog.yld.io/2016/05/10/introducing-queues

--

I would like to attend on both events, EU and US. But NI-US is scheduled for Nov/Dec -_- Being in SF/CA in October. Bad timing.

I'm mostly interested in how we can keep up with the ECMA standard. `require` vs. `import`. Callbacks vs. Promise/Async&Await, etc.

**Comment by vladmiller** [comment]
@fibric You probably misunderstood me. I want to hear about how other people build their workers to be resilient when processing big data.

**Comment by nebrius** [comment]
I'll most likely be attend Interactive US, not sure about EU yet. If I ended up attending Interactive EU though, I'll be there for the summit. If so, I'd love to chat about https://github.com/nodejs/inclusivity/issues/132, which I suspect will still be a work in progress in September.

**Comment by yunong** [comment]
I'm with @lucamaraschi -- would like to talk about post-mortem tooling but also production tooling as well.

**Comment by yunong** [comment]
@mikeal do you have the exact dates?

**Comment by TheAlphaNerd** [comment]
@yunong Sept 17 - 18 in EU Dec 1 - 2

**Comment by bnoordhuis** [comment]
If there's a BoF on post-mortem / profiling / debugging in Amsterdam, I'll be happy to swing by.  I suppose there is no chance of having it on Friday rather than Saturday or Sunday?

> If you are a committer and are not attending interactive we can register you just for the collaboration summit.

(raises hand)

**Comment by yoshuawuyts** [comment]
I'll try and make my way back to Europe for this :sparkles:

**Comment by saghul** [comment]
> If you are a committer and are not attending interactive we can register you just for the collaboration summit.

✋

**Comment by mhdawson** [comment]
I should be able to be there

**Comment by jasnell** [comment]
@bnordnuis ... it would be great to finally meet! The Interactive
conference itself is the 15th and 16th which pretty much rules out having
the collab summit on Friday, but that doesn't mean the members of the post
mortem WG couldn't get together informally on Friday on their own.

**Comment by hemanth** [comment]
* Streams

* ES{6,7} features.

* Memory optimizations.

* App profiling.

* Debugging with devtools.

^ Would be nice to have?

**Comment by benjamingr** [comment]
> If you are a committer and are not attending interactive we can register you just for the collaboration summit.

I'd like to register for that too.

Also - my job is not going to cover anything (not even days off) - so any help from the foundation on getting there or staying there would be nice. Otherwise I'll probably just pay for it from my own money.

**Comment by rictorres** [comment]
i'm not a commiter but am/was part of the translation working groups that started with the iojs fork.
i've registered already for the main event, although i have a question: can i still attend this unconf? i'd really love to :)

ps: i live and work in amsterdam

thanks ;)

**Comment by mikeal** [comment]
@rictorres yup! :)

**Comment by piccoloaiutante** [comment]
I'm in a similar position as @rictorres and I plan to join you all ;-)

**Comment by bnb** [comment]
@mikeal In the Travel Assistance section you mention a US edition. Are you talking about the Austin Node Interactive? Will there be a collaborator's summit there, as well?

**Comment by mikeal** [comment]
@bnb yup! :)

**Comment by bnb** [comment]
@mikeal Okay! Would I be able to apply for assistance? There's a _chance_ I wouldn't need it based on an employment situation, but there's no certainty in that at this point (there will be come September). I very much feel a need to go, and want to ensure I can, so I thought I'd ask.

**Comment by mikeal** [comment]
@bnb yup, we'll open that up in a few months when we get closer to that event.

**Comment by bnb** [comment]
@mikeal Okay, sounds good. Thanks!

**Comment by mhdawson** [comment]
You mentioning registering for the summit. Is there a link for where to do that ?

**Comment by saghul** [comment]
@bnoordhuis (and anyone who wants to join) How about some discussion / planning for libuv v2.x ?

**Comment by bnoordhuis** [comment]
Good idea!

**Comment by yosuke-furukawa** [comment]
I will go there! I dont need assistance. I would like to discuss about ES.next features for Node.js. 
like:

- ES Modules
- Zone
- Promise (with default unhandledRejection behavior)
- Stream

**Comment by bnoordhuis** [comment]
cc @addaleax - as a student you're almost certainly eligible for reimbursement.

**Comment by mikeal** [comment]
@bnoordhuis @addaleax we also have a fund for the Code and Learn workshop that we can use to send committers who are taking part in the workshop.

**Comment by williamkapke** [comment]
On the less technical side, I would like to discuss Collaboration + Node.js Bot + Openness.

**Comment by bnoordhuis** [comment]
@williamkapke Can you elaborate?

**Comment by williamkapke** [comment]
Sure @bnoordhuis...

The Foundation's list of goals includes:
- Increase Contributions
- Maintain transparency & open governance

...which I'm a big advocate for. We want these things, but we don't want to add annoying overhead that makes it HARDER to contribute. My preferred way of improving on those topics is through automation. A few of us have been working on the [Node.js GitHub Bot](https://github.com/nodejs-github-bot/github-bot) to accomplish this. **_I_** think it's a really neeto project and would like to: show it off / talk about plans / solicit feedback / drum up interest.

I know other people have ideas and I'd like there to be a forum for them to share them.

**Comment by mikeal** [comment]
At this point people should create new issues for sessions they would like to see. These issues should also solicit someone to lead them.
