### ISSUE TITLE
Access to Settings tab of this repo for @keywordnew

### ISSUE THREAD

**Issue by keywordnew** [nodejs/summit#162]
Issue templates are [not showing up as expected](https://github.com/nodejs/summit/pull/158#issuecomment-488754122).

I need access to the Settings tab for this repo to check what could be preventing that.

**Comment by Trott** [comment]
Removing the quotation marks and the non-ASCII character from the YAML front matter fixed it in my fork.

**Comment by Trott** [comment]
Fix is in https://github.com/nodejs/summit/pull/163.

**Comment by keywordnew** [comment]
👏🏽👏🏽👏🏽
