### ISSUE TITLE
Summit Topic: Rethinking Transpilation in JavaScript Package Distribution

### ISSUE THREAD

**Issue by nomadtechie** [nodejs/summit#170]
## Topic

**Rethinking Transpilation in JavaScript Package Distribution**

In 2019, the JavaScript bloat in web application bundles is really high! A big contributor to bundles sizes is the inclusion of polyfills and transpiled code, often included from NPM modules that aren't the author's code. Teams that care about bundle sizes can encounter difficulty in reducing this bloat because of the pervasive publication of post-transpiled modules. Let’s start a discussion on how we can improve this process to allow application developers to reduce their bundle sizes, and improve performance.

### Session Breakdown

- Overview of the problem statement _(10 min - presenter @nomadtechie)_
- Surprise group breakout activity _(30 min - lead facilitator @spectranaut)_
- Group Breakout Report Back  _(10 min - lead facilitator @spectranaut)_
- Closing thoughts & next steps _(5 min - presenter @nomadtechie)_

### Additional Facilitators for Group Breakouts
@tzmanics
@pipobscure
@amiller-gh

### Post-Session Resources

// Slides will be linked here after the session
// Notes from the group breakout sessions will be linked here

**Comment by ljharb** [comment]
Hopefully the intention will Include how to preserve backwards compatibility as transpilation is rethought :-)

**Comment by nomadtechie** [comment]
Hi Jordan! :-) 

Coming up with a solution is not the intent of the session, but the constraint you just described is exactly the feedback I am looking to collect for a new initiative which I will be a discussion during the session. 

Will you be there today?

**Comment by nomadtechie** [comment]
> Hopefully the intention will Include how to preserve backwards compatibility as transpilation is rethought :-)

Hi Jordan (@ljharb)

Coming up with a solution is not the intent of the session, but the constraint you just described is exactly the feedback I am looking to collect for a new initiative which I will be a discussion during the session. 

Will you be there today?

**Comment by ljharb** [comment]
Great to hear!

No, unfortunately I'm unable to travel at the moment, so I won't be able to attend.

**Comment by trivikr** [comment]
Time: **CEST Thu 30-May-2019 17:00 (05:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by nomadtechie** [comment]
thanks @trivikr!

**Comment by WaleedAshraf** [comment]
closing as the summit is over. 👍

**Comment by keywordnew** [comment]
Closing as this event is complete :)
