### ISSUE TITLE
Summit Topic: Bob Streams

### ISSUE THREAD

**Issue by jasnell** [nodejs/summit#172]
**Topic of the session**

"Bob" Streams in Node.js

**Describe the session**
Update and Discussion of the new "bob" streams development effort.

**Session facilitator(s) and Github handle(s)** 
@Fishrock123 @jasnell 

**Additional context (optional)**

**Comment by trivikr** [comment]
Time: **CEST Fri 31-May-2019 17:00 (05:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by Fishrock123** [comment]
Link to slides, if I show them: _(note: mostly unchanged from Vancouver 2018)_ https://fishrock123.github.io/nodejs-collab-summit-berlin-2019

**Comment by WaleedAshraf** [comment]
closing as the summit is over. 👍
