### ISSUE TITLE
Summit Topic: Promises

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/summit#175]
**Topic of the session / Describe the session**

This is just an overview of the actual promise session.

Topics are:

* What modules have native promise support right now and which still need that / how should we implement it
* Unhandled rejections survey / gathering questions / examples
* Multiple resolves hook - how to improve this and what solution do we favor?
* Log unresolved promises on exit

**Additional context (optional)**

* Link to the survey questions: https://docs.google.com/document/d/1W0ReQq6tHiyVaI04ON2_peYu33NiTG3WwNdn6NHNxFQ/edit (please add new suggestions - they will be brought to the diagnostics working group for review)
* List of all modules and their native promise support status: TBD

**Comment by joesepi** [comment]
API List: https://docs.google.com/spreadsheets/d/1yG3DBX30sYA3-8XFlXQAF4JR8NrJSMMe7TGAR8V5woc/edit?usp=sharing

**Comment by joesepi** [comment]
User Feedback survey was started last year. We should pick that up again and execute the survey when we feel we've crafted it to gather the information we'd like to help us on this question: https://github.com/nodejs/user-feedback/issues/77

**Comment by keywordnew** [comment]
Closing as this event is complete :)
