### ISSUE TITLE
Update session submission issue template to include required subject matter familiarity levels

### ISSUE THREAD

**Issue by keywordnew** [nodejs/summit#179]
Creating this issue from the retrospective to address a need to help sessions clarify their purpose.

The levels could include:
* willing to allocate 10 minutes at the start of the session to answer Q/A from folks not completely up-to-date
* looking for folks to contribute, familiarity with some other part of the project is requested
* we're diving right in, you're welcome to attend but Q/A time is not explicitly allocated

**Comment by sendilkumarn** [comment]
I think something like [this](https://github.com/nodejs/summit/compare/session-submission?expand=1) will really help us

**Comment by christian-bromann** [comment]
@sendilkumarn mind adding a small description (as comment) so all people are in the same boat?

**Comment by sendilkumarn** [comment]
@christian-bromann Sorry, I updated the comment above and also the branch again. Hope this clarifies.

**Comment by keywordnew** [comment]
Thank you for proposing these edits. They look great!

> This is required for both Intermediate and Advanced sessions

I'd suggest modifying this explanation as it's unclear what "this" refers to. Scoping pains ;)

Consider: "_List pre-requisite knowledge that it would be helpful for participants to have_" or similar.

+1 to having both levels and a section for pre-req. That way people can have more info to decide if they'd like to go.

> **Follow-up / Set-up sessions (if any)**

If this section is for listing related sessions, I'd suggest indicating that.

Looking forward to the PR!

**Comment by christian-bromann** [comment]
Closing as #189 has been merged.
