### ISSUE TITLE
Austin: VM Summit

### ISSUE THREAD

**Issue by mikeal** [nodejs/summit#19]
We need to have a followup VM summit during the Collaboration Summit in Amsterdam.

Who wants to step up to lead this?

**Comment by jasnell** [comment]
I'll volunteer.

**Comment by kriry** [comment]
great!

**Comment by jasnell** [comment]
Ok, had the best intentions of pulling together the organization on this last week but never was able to get around to it. I'll pull together the details early next week.

**Comment by mhdawson** [comment]
Initial agenda proposal is as follows:

1) Quick recap for any new attendees
2) Update in the 4 areas we broke out into last time
  - Native API
  - FFI
  - Motivation
  - Compliance/Spec/Testing.
3) Collaboratively agree on next topics to cover while together.  One good candidate is to 
    break out into the 4 areas again to work/discuss together face to face.

I'll be looking for volunteers to lead the updates in each of the original 4 sections.

I'll also email the original attendees to better capture who we think will be there.

**Comment by joshgav** [comment]
In the compliance/spec/testing area, we finished last time with this: https://docs.google.com/document/d/12F1UDMVcBwEVkAhKqTEqLGbdfhb7ojgyk-YYf_LHlCA

Could be a good starting point for that area this time.

**Comment by dshaw** [comment]
I won't be able to attend in person. @Fishrock123 should be able to join in my stead.

Any thought of doing remote dial in like last time?

**Comment by jasnell** [comment]
We can potentially do remote depending on reliability of the wifi at the venue. Not sure what the schedule is going to be yet either so attendees in the US might be a bit inconvenienced.

**Comment by dshaw** [comment]
@jasnell Yeah, that makes sense. I don't think we need to force it. It's a nice to have though and would continue to encourage participations from interested parties who cannot make it in person.

**Comment by aruneshchandra** [comment]
This is what we captured for Motivation last time. IMO nothing significant has changed in this area - but we can discuss it again if there is interest  
https://docs.google.com/document/d/1BfmTarR6M0LJreSbFLxaorX7Wx7anfb-9wZtLyXsZ74

**Comment by williamkapke** [comment]
We're not doing this in Amsterdam- aiming for Austin now ;)

**Comment by aruneshchandra** [comment]
**Proposed Date/Time for VM Summit 2: Thursday Dec 1st 2016 (13:00-17:00)** 

Recap from VM Summit 1
- [Native API  (aka Node API)](https://github.com/nodejs/abi-stable-node/issues/18)
- [FFI] (https://github.com/nodejs/api/blob/master/ffi/FFI%20presentation%20%40%20VM%20summit.pdf)
- [Motivation](https://docs.google.com/document/d/1BfmTarR6M0LJreSbFLxaorX7Wx7anfb-9wZtLyXsZ74)
- [Compliance/Spec/Testing](https://docs.google.com/document/d/12F1UDMVcBwEVkAhKqTEqLGbdfhb7ojgyk-YYf_LHlCA)

Agenda Proposal:

- Agreement on VM Summit cadence (Quarterly?)
- Volunteer selection for each of the 4 areas from the last summit
- Review updates / establish roadmap for each area
- Anything else ?

**Comment by joshgav** [comment]
Notes here: https://docs.google.com/document/d/1D7-RBkuJiakADIWXOBVNyb6FNSXdoE3XIEXZ1axq97Q/

**Comment by jasnell** [comment]
Awesome meeting today.  One of the key follow ups will be scheduling the next checkpoint meeting. We are looking at late Feb / early March timeframe. It does not have to be in person but @Qard asked if we could use video conf -- definitely a possibility and I will look into it. We'll have to see what the options are because we've got a large group. I will get the follow up meeting scheduled by early to mid next week. If there are dates in that timeframe that absolutely do not work for you, please let me know

**Comment by fhinkel** [comment]
@joshgav thanks for the detailed notes!
