### ISSUE TITLE
Ensuring the Code of Conduct

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/summit#2]
Since I'm not sure core's CoC formally applies to this, we should state that this will be under that CoC. (Presumably.)

**Comment by mikeal** [comment]
Good point, we should grab a proper event CoC as well since the language is better suited for this.

**Comment by mikeal** [comment]
unless there are objections I'm going to pull from http://confcodeofconduct.com/

**Comment by jasnell** [comment]
@mikeal ... I would ping @mkdolan to see if LF already has something in use.

**Comment by mikeal** [comment]
@jasnell after pulling up a few different LF run events they don't appear to have the same CoC between events which I think means they let the individual events figure this stuff out, but I'll bring it up with @mkdolan next I talk to him, if he doesn't end up popping in here :)

**Comment by mkdolan** [comment]
Hi, the LF events team has a standard policy for all of our events here: http://events.linuxfoundation.org/events/linuxcon-north-america/attend/code-of-conduct <http://events.linuxfoundation.org/events/linuxcon-north-america/attend/code-of-conduct>

Some of the events that we host for other projects (non-LF projects that engage our LF events team) may have their own code of conduct. Examples would be the Apache events.

**Comment by Fishrock123** [comment]
I would prefer the Conference CoC. cc @nodejs/diversity

**Comment by mikeal** [comment]
ya, the confcodeofconduct has become pretty standard across JS events. it's a superset of the language in the linux CoC.

**Comment by nebrius** [comment]
I would like to point out one exception: most NodeBots events use the http://citizencodeofconduct.org/, and we're in the process of using it for the hardware WG too.

There are a couple of reasons I prefer the Citizen CoC over Conf CoC (and contributor covenant, and a bunch of other CoCs) including, but not limited to:
- Citizen CoC has a comprehensive list of what is and is not acceptable, so there's less ambiguity
- Citizen CoC has very good, explicit steps on what to do if an issue crops up, including anonymous reporting options, whereas the conf CoC just says "find someone in an event shirt".
- Citizen CoC has guarantees of confidentiality in reporting, the conf CoC does not
- Citizen CoC has clearly labeled sections, so it's easy to jump to the part you need
- Overall, the Citizen CoC feels, to me, to put more effort into making those dealing with an issue, or worried that they may deal with an issue, feel comfortable and confident that issues will be dealt with properly.

**Comment by mikeal** [comment]
My impression, and this may be incorrect, was that the Citizen CoC was built for "projects" and other non-physical spaces. Is it in use at any events other than NodeBots?

I'll defer this decision to the diversity WG though, they know more about this than I do. I will offer myself up as the point of contact for the CoC though.

**Comment by nebrius** [comment]
@mikeal Unfortunately I'm not sure if it's used elsewhere for conferences. My reading of it is that the citizen CoC is built for communities. This does include projects, but isn't necessarily limited to them. IIRC it was originally created for hacker spaces (my memory is fuzzy on this, so I could be wrong). In any case it certainly does address meatspace events, in addition to online events.

Another option is to modify the conf coc to address the limitations in it, bringing in very select bits and pieces from the citizen coc, which I could definitely get behind.

I'll bring it up in the diversity slack channel to get feedback from others (these ideas are my own, not necessarily those of the WG).

**Comment by williamkapke** [comment]
The LF events for Node Interactive have a CoC page....
http://events.linuxfoundation.org/events/node-interactive/attend/code-of-conduct
http://events.linuxfoundation.org/events/node-interactive-europe/attend/code-of-conduct

I'm going to conclude that even though Collab Summit was added later, this now applies to them. Feel free to reopen to continue the conversation if desired.
