### ISSUE TITLE
Amsterdam: Discuss JS API (ala API wg) in regards to nucleus-js

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/summit#22]
I can probably lead this, see https://github.com/nodejs/api#js-api

**Comment by Fishrock123** [comment]
this also ties into the VM-summit stuffs

**Comment by williamkapke** [comment]
@Fishrock123 Amsterdam, Austin, or both?

**Comment by Fishrock123** [comment]
Amsterdam only I think.

**Comment by Fishrock123** [comment]
Won't be there. You can discuss without me if you wish but I doubt anyone has played with these ideas. Closing I guess.
