### ISSUE TITLE
Amsterdam: Collaboration + Github Bot

### ISSUE THREAD

**Issue by williamkapke** [nodejs/summit#23]
I would like to lead a talk about Collaboration on GitHub. As part of it, I would like to go over some of the great ideas that have been suggested- and see what else surfaces!

/cc some bot folks: @nodejs/build

**Comment by Starefossen** [comment]
Great suggestion @williamkapke! Not sure if @jbergstroem or @phillipj will be attending the Amsterdam summit this year?

**Comment by jbergstroem** [comment]
I won't be able to make it :(

**Comment by phillipj** [comment]
It would be great to get some ideas about what the bot should (and should
not?) be used for 👍
Sadly I'm not going either cause I'm in the middle of changing jobs in
september/october.

**Comment by Starefossen** [comment]
Too bad none of you can go. Congrats on new job, @phillipj 🎆

**Comment by jbergstroem** [comment]
How about I join the gh 'group' and we try to get some meetings going? The first one (blue skies:ish) could just be about throwing things on the wall -- whats required, whats good to have and how much sugar on top.

**Comment by Fishrock123** [comment]
I'll be there, but I don't really work on the bot that much...

**Comment by Starefossen** [comment]
I like a good wall throwing as as much as the next person 😄
