### ISSUE TITLE
Amsterdam: stream internals for everyone

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#25]
I would like to have an _informal_ session on "how streams works" internally, discussing the code, and seeing if we could see ways for improving it.

cc @nodejs/streams who is coming and can help?

**Comment by TheAlphaNerd** [comment]
o/

Very interested in learning, not sure how much help I can be though

**Comment by addaleax** [comment]
Yeah, I’m interested! I’d say I have a pretty good understanding of some of the code bits, but not so much on others, so this sounds great.

**Comment by williamkapke** [comment]
This is happening now!

**Comment by mcollina** [comment]
I'm happy to keep the discussion going afterwards, as I was faced with a very hard challenge: Internet Explorer.

Let me know if you have any questions.
