### ISSUE TITLE
Amsterdam: Releases

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/summit#26]
It would be a good idea for us to get together and discuss the release process.

* What is working?
* What isn't working?
* How can we set up a more reliable cadence

/cc @nodejs/release

**Comment by TheAlphaNerd** [comment]
This could also be a good place to on board new members

**Comment by jasnell** [comment]
One specific discussion point for this:

Even tho we have implemented a stable and reliable LTS, follow semver closely and pace out our breaking changes every six months, and have a fairly stable current, there's a perception that if we happen to land any breaking changes in master, we've "broken the ecosystem" and have done something bad. This has been particularly evident in the `new Buffer()` and `fs.realpath()` discussions. The view seems to be that if we make any changes in core that require the ecosystem to do *any* work to update, then we've done something terrible, even if the breaking changes sitting in master have absolutely no impact on LTS or Current.

A key question is: what should we / can we do about this ?

**Comment by cjihrig** [comment]
What do you envision as an ideal size for the release team? I don't think this is a case of more is always better, with only 3 release streams.
