### ISSUE TITLE
Amsterdam: Venue details?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/summit#28]
I'm sure this is a question for @mikeal. You said in #16:
> We have space for a few hundred people in the same venue as Node.js Interactive the two days following all the talks.

Will there be any AV setup for people to display their screen if they want?
"A few hundred" is a lot... so microphone(s)?
Will there be multiple topics at a time?

I think this is important to know so people can come better prepared to share their thoughts. (like bring a HDMI adapter for your USB-C only laptop!)

**Comment by mikeal** [comment]
If you need something we can have it provided, just let us know :)

I doubt a few hundred will be attending the summit, but we do have room for that many :)

**Comment by williamkapke** [comment]
I think a screen with HDMI might be nice if there is any show & tell type stuff.
I'm ok with yelling so maybe not microphones ;)
