### ISSUE TITLE
Amsterdam: Post Mortem Debugging

### ISSUE THREAD

**Issue by yunong** [nodejs/summit#29]
This is a good opportunity to discuss postmortem debugging with the broader group. cc: @lucamaraschi, @davidmarkclements, @mhdawson, @mcollina

**Comment by mcollina** [comment]
I'll be there both saturday and sunday.

**Comment by lucamaraschi** [comment]
I was thinking to maybe get all together in a nice place and start hacking
something together!
Il giorno gio 1 set 2016 alle 23:29 Matteo Collina <notifications@github.com>
ha scritto:

**Comment by indutny** [comment]
I'll be around too
