### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by mikeal** [nodejs/summit#3]
Please propose Agenda topics that we can consider.

# Proposed Subjects

## Core

* First Converged Release Schedule
* LTS
 * Roadmap to Second converged LTS
 * Discussion of the key internal changes that still need to be made (e.g. improved abstraction layer, multiple isolates, refactoring internal dependencies -- e.g. the pure js http parser and dns work, etc)
* Debugging and Discussing what we're going to do about domains
* FFI
* tracing_event.h
* API
* Making StreamBase public.

## Project / WG

* project goal setting
* timelines
* best practices for issues/meetings

**Comment by jasnell** [comment]
1. LTS
2. First Converged Release Schedule
3. Roadmap to Second converged LTS
4. Discussion of the key internal changes that still need to be made (e.g. improved abstraction layer, multiple isolates, refactoring internal dependencies -- e.g. the pure js http parser and dns work, etc)
5. Debugging and Discussing what we're going to do about domains

**Comment by Qard** [comment]
I'd like to bring up the tracing topic and discuss how we can generically describe linkage between caller and callback invocation barriers. It'd be especially valuable if we can discuss this with people from the V8 team.

I feel like AsyncWrap exists because of a deficiency in V8 which, if dealt with properly, could make that feature a lot less painful.

**Comment by mikeal** [comment]
@Qard what is the status of integrating the tracing API v8 is landing in to node?

**Comment by TooTallNate** [comment]
FFI in core

**Comment by Qard** [comment]
@mikeal No progress on the node side. I need to check in with @ofrobots or @natduca to see where things are at on their end.

I was holding off on doing anything with trace_event.h because they said it wasn't ready yet, last time we talked.

**Comment by trevnorris** [comment]
@Qard `AsyncWrap` is mostly meant to exist outside the realm of V8. It notifies about internal events that happen at the libuv layer. Also to bring all asynchronous functionality to a single location for easier tracing. So even in the case we use `tracing_event.h` it will be much easier to implement.

**Comment by trevnorris** [comment]
Topics for me would be the API compatibility discussions and tracing. Google team says that the `tracing_event.h` API is stable and we could start integrating it now for testing.

Will there be a formal agenda made?

**Comment by mikeal** [comment]
* Working Group Best Practices

**Comment by mikeal** [comment]
@trevnorris yes, I'm going to write up a formal schedule before the event.

**Comment by indutny** [comment]
Making StreamBase public.

**Comment by chrisdickinson** [comment]
I'd like for the collaborators & the TSC to talk about how we set goals for the project, over what timespans, and how we communicate those goals to our users. This should also touch on how we want to communicate our progress towards those goals to our fellow collaborators. The goal would be to see what aspects of project management we're currently lacking in, and agree on ways to fill those gaps.

**Comment by mikeal** [comment]
@chrisdickinson would you want to combine this with the WG "best practices" stuff or run it right after as sort of a followup?

**Comment by jasnell** [comment]
@mikeal ... thinking about the agenda, it would make sense for us to dedicate one of the two days for WG specific breakout sessions. Given the amount of overlap between the WG's, these do not need to be done in parallel -- just need to have specific allotments of time dedicated for the members of each WG to discuss their status and specific agenda items. The second of the two days would be dedicated to larger project wide discussions -- foundation discussions, the release schedule, the strategy around V8, the LTS schedule, Roadmap discussions, etc.

Do we have the plans figured out for hosting of the event? e.g. Who's providing the snacks, who's paying for things? etc.

**Comment by mikeal** [comment]
@jasnell my plan was to actually split the Agenda in to chunks (either 2 or 3 per day) and to put TSC/Core stuff together in a block, along with WG stuff, so that people can step our or come late if the agenda doesn't appeal to them for significant parts of the day. 

> Who's paying.

The foundation :) This week I'll find out who I send all that to.

> Hosting.

There's been a lot of offers for hosting, I'm speaking to my favorite in Thursday to see if we can work out a deal for accommodations as well. I should have a more definitive answer by next week.

Who provides the snacks and what they are is pretty dependent on the location.

**Comment by jasnell** [comment]
:+1: sounds good.

**Comment by mikeal** [comment]
updated description w/ proposed subjects.

**Comment by Fishrock123** [comment]
If possible, I'd like to do a bit of a thing on the morning of the first day for those who are newer to collaborating on core before diving into discussions.

I.e. like have a couple more experienced people explain in detail some deep technical topics. (And then have those recorded for future onboarding of collaborators.)

**Comment by Qard** [comment]
:+1: for internals deep-dive.

**Comment by bnb** [comment]
@Fishrock123 Also +1 for that.

**Comment by mikeal** [comment]
Just had a productive meeting with @groundwater about running the sessions with proper facilitation.

We're looking to do 2 hour sessions, 3 a day.

* 10am - Noon Session 1
* Noon - 1pm Lunch
* 1pm - 3pm Session 2
* 3pm - 4pm Break
* 4pm - 6pm Session 3

This means we'll only have 6 sessions total over the 2 day timespan. @groundwater will be kicking off a new thread to determine what those sessions are and what the goals for each session are so that we can ensure they are productive.

I'm going to close this issue in favor of building the 6 topics in a new thread that is more well described and scoped.
