### ISSUE TITLE
Austin: Diagnostics

### ISSUE THREAD

**Issue by joshgav** [nodejs/summit#30]
Transferring from https://github.com/nodejs/diagnostics/issues/58

Some topics from that thread:
- tracing: controller, protocol, format
- async_hooks
- es6 module patching
- inspector protocol and tools

/cc @nodejs/diagnostics @watson

**Comment by danielkhan** [comment]
Adding
- Event Loop metrics (pending tasks, tasks per second). More or less like Linux load.

**Comment by joshgav** [comment]
From the November Diag WG meeting -

* work on adding trace points to Node and core modules based on https://github.com/nodejs/node/pull/9304
* discuss context propagation across async boundaries (@ofrobots - I think that's what you meant)

**Comment by joshgav** [comment]
Several of us chatted yesterday and agreed to meet Friday for Diagnostics, allowing Thursday afternoon for participating with other groups etc. Any opposed please let us know here.

Let's flesh out the agenda a bit, the following is based on what's above and other evolving discussions:

* TracingController
  * Adding trace points to core modules
  * JS API?
  * Intended use cases

* Inspector - CLI Debugger
  * [node-inspect](https://github.com/buggerjs/node-inspect) in core itself or alongside it?
  * Opportunities for new capabilities available through inspector - specifically CPU and Heap profiling at the moment.

We may also want to discuss the UUID associated by Inspector with each process as in https://github.com/nodejs/node/issues/9185.

* Context propagation and async_hooks (@ofrobots)
* Event loop (@danielkhan)

/cc @nodejs/ctc in case some of you can join.

**Comment by Trott** [comment]
I'd like to be there for the Debugger stuff.

**Comment by Trott** [comment]
(Time?)

**Comment by jkrems** [comment]
I'd also like to join for the Debugger stuff.

**Comment by joshgav** [comment]
@Trott 

> Time?

Going with https://github.com/nodejs/summit/issues/35, how about 9am? Meet near where the keynotes were and choose a room. We can review and set the agenda first thing. Perhaps we can spend a chunk of the time coding and presenting to each other.

@jkrems - Was counting on you coming! Thanks!

**Comment by danielkhan** [comment]
I'll be there as well.

**Comment by jkrems** [comment]
@joshgav Side note - inspired by your talk today I added some quick profiler support to `node-inspect`:

```
debug> profile
# [...]
debug> profileEnd
[Profile 2572307μs]
debug> _.save('my.cpuprofile')
Saved profile to /path/to/cwd/my.cpuprofile
debug> takeHeapSnapshot('my.heapsnapshot')
Heap snaphost prepared.
Wrote snapshot: /path/to/cwd/my.heapsnapshot
```

**Comment by joshgav** [comment]
Notes: https://docs.google.com/document/d/1hUiG1nv4hxjnznN2NjU3F-MzXtKhWxvMI3R8caJyzCs/edit

**Comment by joshgav** [comment]
Great meeting everyone! Cooked notes in this PR: https://github.com/nodejs/diagnostics/pull/76, PTAL.
