### ISSUE TITLE
Amsterdam Agenda

### ISSUE THREAD

**Issue by williamkapke** [nodejs/summit#31]
Post your ideas here:
http://www.ideaboardz.com/for/Collaboration%20Summit/2490012

**Comment by eljefedelrodeodeljefe** [comment]
Just added this here for consideration https://github.com/nodejs/summit/issues/32

**Comment by eljefedelrodeodeljefe** [comment]
saghul opened #33

**Comment by bengl** [comment]
KeySigning Party (#27) should be tomorrow (Sunday) if we're going to do it. That way instructions can be provided today for what to bring (ID, etc.).

**Comment by yosuke-furukawa** [comment]
@jasnell opened #34

**Comment by jasnell** [comment]
https://docs.google.com/document/d/14xxdZa5llZf4kGJXDpRavbus8qJqy1hTw1pdNEKW4jk/edit?usp=sharing
