### ISSUE TITLE
Amsterdam: preparing libuv v2

### ISSUE THREAD

**Issue by saghul** [nodejs/summit#33]
We ( @bnoordhuis, @piscisaureus, @indutny and myself) will gather and plan a rough sketch for libvu v2.

**Comment by piscisaureus** [comment]
Priorities following from the libuv session:
1. Merge Windows and UNIX timer implementation.
2. Implement `uv_timeout_t`.
3. Implement `uv_read()` and `uv_poll_read()`.
4. LEP for supporting multiple/custom thread pools.
5. Improve docs.

**Comment by saghul** [comment]
I'll publish the updates slides soon.
