### ISSUE TITLE
Collaboration Summit at Node Interactive Austin

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/summit#35]
## Let's plan a Collaboration Summit!

Looking at how we can improve for November from the Amsterdam event. It would be great to do _lots_ of outreach to the various working groups to make sure they know this is happening, that there's lots of space/time for working groups to discuss things, and that each one should represent! 

_Please edit these things! This is a draft._
### Organizers
- William Kapke @williamkapke 
- James Snell @jasnell 
- Myles Borins @thealphanerd
- ? Your name here ?
- Tracy Hinds @hackygolucky
### Things to cover:

- Make plan for contributor meeting
- Share sign up schedule for people to sign up tomorrow
- All presentations should be at the beginning
- Unconf planning time to figure out who wants to work on what and then breakout

We'd love to know ahead who will be represented. Filing issues in this repo is helpful for discussion particular to a working group and how they'd like to manage their time. Linking to that here would be great! We'd like to be able to post times for this on the conf agenda so people are aware of when WG meet and can maybe get a break, if needed. We'll be looking at issues filed in this repo titled "Austin: working group something something" to add these below as well.
- Working group that will be at Collaboration Summit 
  - Name of contact @github-handle
  - link to working group planning issue
  - Any extra requests(space during conf, av/sound, etc.)
- Evangelism WG
  - @bnb
  - [help plan the Evangelism session](https://github.com/nodejs/summit/issues/37)
- Version Management
  - @ljharb
  - [help plan the Version Management session](https://github.com/nodejs/summit/issues/36)
- Diagnostics WG
  - @joshgav joshgav
  - [help plan the Diagnostics session](https://github.com/nodejs/summit/issues/30)
- VM Summit
  - @jasnell 
  - [help plan the VM Summit](https://github.com/nodejs/summit/issues/19)
- Inclusivity WG
  - @hackygolucky and @nebrius
  - [help plan the Inclusivity session](https://github.com/nodejs/inclusivity/issues/151)
  - meeting in "Outside Griffin #1" on Dec. 2, 11am-12pm
- (NEW) Security WG
  - @rvagg and @evilpacket (?)
  - [help plan the security session](https://github.com/nodejs/security-wg/issues/5)

### Day-of Agenda

_Dec. 1, 2016_
12:00-13:00 Lunch
13:00-14:00 Introduction and presentations pertinent to majority of audience
14:00 - 17:00 Working group breakouts

There are no signups for this day with room breakouts. Wander and find an open room after presentations occur.

_Dec. 2, 2016_
08:00-09:00 Breakfast
09:00-12:00 Collaborator gathering
12:00-13:00 Lunch break(is lunch provided?)
13:00-17:00 Working group breakouts
**Sign up for breakout rooms [HERE](https://docs.google.com/spreadsheets/d/1gJoyiq0z6rjS7jEoHkRe6jte8Dd7ZBkwD3WjOh6djvQ/edit?ts=583e17e9#gid=0)**
  
### AV Setup
- Big projector/screen with HDMI(do we need something else?) and audio output
- Microphone on podium
- A wireless microphone to pass around
- Power outlets for tables
- WiFi
### Space Setup(proposed due to venue space available)

The events team shared this image of what they thought should work for Code & Learn and Day one of the Collaboration Summit. They also asked if a crescent table setup would be more helpful, but my suggestion was that it is more important for attendees to be able to sit at tables with each other/mentors and get help for Code & Learn, so chairs on both sides isn't a bad thing because looking at the projector only happens towards the beginning. _Does this sound right?_

_Day One Collaboration Summit:_
![image](https://cloud.githubusercontent.com/assets/1981088/19402387/d9ac2e3e-922e-11e6-8d53-06c768b4abba.png)

_Day Two Collaboration Summit:_
There will be breakout spaces available after the general space meeting occurs(if that's still a thing). This map represents the general space meeting
![image](https://cloud.githubusercontent.com/assets/1981088/19402608/ef14a62e-922f-11e6-9739-ac6a1437e580.png)
### Outreach

_A  description of what Collaboration Summit will be a great way for us to spread the word so people will register and attend in Austin. Anyone who would like to attempt a bit of copy for this gets brownie points! PR and Marketing at the Node.js Foundation will happily share this and post the full agenda on the conference website_
-  outreach to the various working groups to make sure they know this is happening, that there's lots of space/time for working groups to discuss things, and that each one should represent! 
- share on Twitter, GitHub, other social media
### Logistics to prep
- Figure out a way for any open spaces available for working groups to meet during the conf/collaboration summit to be schedulable online and in-person(large poster or whiteboard because things change last minute and not everyone likes looking at their phones)

Question(s):  
- Do we still want to call this Collaboration Summit? I think a slightly more atomic preliminary agenda(understanding the importance of some unconf-ing happening) helps communicate that portions of this program are contributors-only will be helpful, but is there another name that communicates this better?

UPDATE 11/16
- 257 registrants. Attrition expected at %50, but we're needing to close registration now because we will run into space issues if more people show/signup.

UPDATE 11/30
SIGN UP WORKING GROUP SLOTS [HERE](https://docs.google.com/spreadsheets/d/1gJoyiq0z6rjS7jEoHkRe6jte8Dd7ZBkwD3WjOh6djvQ/edit?ts=583e17e9#gid=0)

**Comment by joshgav** [comment]
To be sure, will this be open to all who'd like to attend, new collaborators too?

**Comment by williamkapke** [comment]
@joshgav That's how EU was and I haven't heard anyone say it would be different for NA.

**Comment by jasnell** [comment]
Oy I just now spotted this. Sorry about that! This is looking great so far

**Comment by hackygolucky** [comment]
*Update on registration!*  
Currently,  257 folks have registered for Collaboration Summit. We're expecting ~%50 attrition if NI EU is a base to go from.

**Comment by hackygolucky** [comment]
We will be updating this agenda with more atomic meetings for specific working groups the week of the event. We will paste a signup link for a spreadsheet in the description above on Monday, November 27.

**Comment by nebrius** [comment]
Question about the schedule: is there anything planned for the morning of December 1st? I notice the first day starts at lunch time.

**Comment by nebrius** [comment]
I'd like to see us spend a little time discussing the CTC/TSC merger during the general collaborator section. We've been discussing it in the TSC for a while, and @rvagg [wrote a really good summary of where we are right now](https://github.com/nodejs/TSC/issues/146#issuecomment-261220901). tl;dr the next step is trying to formalize a list of concerns that are trying to be solved, something I think the summit format would be well suited for kickstarting.

**Comment by addaleax** [comment]
> is there anything planned for the morning of December 1st?

@nebrius There’s [Code & Learn](https://github.com/nodejs/code-and-learn/issues/60), which will ideally involve most of the collaborators who are there

**Comment by nebrius** [comment]
> @nebrius There’s Code & Learn, which will ideally involve most of the collaborators who are there

Ah that's right, thanks @addaleax!

**Comment by rvagg** [comment]
I've added a session for the newly forming security WG.

**Comment by joshgav** [comment]
Many of us may like to attend several of the sessions. Here's a proposed schedule based on the threads at the moment:

Group | Time
-------|-----
VM | Thursday 1pm
Diag | Friday 9am
Security | Friday 1pm (?)
Version Mgmt | Thursday 12pm (?)

**Comment by evilpacket** [comment]
I would love to attend but I fly out tomorrow morning. :( I talked briefly with Rod and he said that there would be notes and transparency of the sessions posted to GitHub so all the rest of us can catch up later.

**Comment by sam-github** [comment]
https://docs.google.com/document/d/1VlCFFOaN-00SE7-eNdjznjzvuGVfOlTryyfz3Zp4uow/edit?usp=sharing <--- notes for Friday morning
