### ISSUE TITLE
Session Proposal: OSS - Zen and the Art of Open Source

### ISSUE THREAD

**Issue by codyzu** [nodejs/summit#353]
### Proposal

**Topic of the session**

Zen and the Art of Open Source

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

30 minutes / Open for discussion

**Date and Time of the session**

Open for discussion

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

noe

**Describe the session**

Open source software and communities can drive meaningful change in organizations. What lessons can we take from open source to drive change in our own organizations? According to the Linux Foundation, it has been estimated that Free and Open Source Software constitutes 70-90% of any given piece of modern software solutions. 

In order to reach true organizational open source zen, organizations need to take a stepwise approach to embracing open source. Learn how to categorize your organization's open source zen level, what steps it should take to level up, and why leveling up will ultimately bring more value and help differentiate your organization from the competition.

What does it mean to go deep and maximize the value of open source in your organization? Open source enlightenment can bring a huge return on investment for an organization. Let’s talk about how we can reach true open source enlightenment.

**Session facilitator(s), Github handle(s) and timezone(s)**

Cody Zuschlag (@codyzu) - CEST (Note, I will be in Vancouver for the summit)

**Meeting notes and Virtual Meeting Link**

TBD

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by ovflowd** [comment]
**FYI:** This session got approved and added to our agenda ✅ 🎉
