### ISSUE TITLE
Austin: Version Management

### ISSUE THREAD

**Issue by williamkapke** [nodejs/summit#36]
Official version management has become a significant topic. Seems like a good candidate for Collaborator Summit!

/cc @ljharb

**Comment by joshgav** [comment]
More discussion here: https://github.com/nodejs/summit/issues/35, seeking a good time for those with an interest to chat at least informally.

**Comment by joshgav** [comment]
We said we'd meet at the front of the big room at 2:30, but can we postpone till 3:00pm?

**Comment by joshgav** [comment]
cc @coreybutler @TheAlphaNerd

**Comment by TheAlphaNerd** [comment]
I can do 3

**Comment by joshgav** [comment]
Still in VM meeting, sorry! How late are you all here?

**Comment by joshgav** [comment]
Notes here: https://github.com/nodejs/version-management/blob/master/meetings/2016-12-01.md.

We can close this now, thanks!
