### ISSUE TITLE
Austin: Evangelism WG

### ISSUE THREAD

**Issue by bnb** [nodejs/summit#37]
Would be great to get an Evangelism WG group together at the Summit.

Some topics we could talk about:
* Ramping up the Evangelism WG into full-swing again
  * Define an Evangelism WG master-plan for 2017, with some broad, overarching goals that we can dig deeper into and iterate on (https://github.com/nodejs/summit/issues/37#issuecomment-261043580).
* Engaging the community further
* Building more blog content
  * Enabling the blog to be "better" (metadata for sharing)
* What tasks can the WG take on at this point?
* What can we do to get the boll rolling (faster) on current tasks?
  * Weekly Updates - How can we improve?
  * Issue Summaries (https://github.com/nodejs/evangelism/pull/243)
  * Updating the Node.js Wikipedia (YIKES! https://github.com/nodejs/evangelism/issues/102)
* Which old tasks can we/should we work on?  
  * The Enterprise Case for Node.js (https://github.com/nodejs/evangelism/issues/239)
  * Cadence for StackOverflow Open-source Ads (https://github.com/nodejs/evangelism/issues/214)
  * Official Node.js Podcast (https://github.com/nodejs/evangelism/issues/204)

If anyone has questions or suggestions on topics, happy to add them!

**Comment by bnb** [comment]
D'oh! Forgot to mention @nodejs/evangelism! 👋

**Comment by vdeturckheim** [comment]
Great plan!
We might want to define some goals for 2017 in term of Evangelism as a Master plan for the year.

**Comment by bnb** [comment]
@vdeturckheim Added to the first point 😊

**Comment by williamkapke** [comment]
@bnb can you pick a room/time here?...
https://docs.google.com/spreadsheets/d/1gJoyiq0z6rjS7jEoHkRe6jte8Dd7ZBkwD3WjOh6djvQ/edit?ts=583e17e9#gid=0
