### ISSUE TITLE
Facilitation Training

### ISSUE THREAD

**Issue by groundwater** [nodejs/summit#4]
As per https://github.com/nodejs/summit/issues/1#issuecomment-118430460 Mikeal and I talked about using a facilitator for all summit meetings.

Facilitating a meeting can be difficult, and even just a few hours can wear someone out. Given that there are 3 sessions a day, I'm recommending at least 3 people to spread out the load.

Given the multiplicative effect a good/bad facilitator can have on a discussion, **I would like to run a introductory workshop** for _anyone_ interested in learning to facilitate. I would prefer to select the summit volunteers from attendees of the workshop, but volunteering is not a requirement of the workshop. No commitments need to be made to volunteer before the workshop.

Ideally, **the workshop would be 1-2 weeks prior to the summit**. I realize this may exclude people who are travelling specifically to attend the summit. If there are a lot of people interested who are travelling, I may re-visit this choice.

## About Facilitating

A facilitator is a non-participant in the meeting they are guiding. Their role is to combat cognitive biases, and direct the meeting according to the best needs of the group.

The most important part of being a facilitator is **trust**. _The group must trust you._

If you have a strong stake in the topics you're facilitating, the group may choose not to trust your objectivity. This does not exclude you from participating. It just means maintaining trust comes first.

## Workshop

The workshop will be interactive. We will practice facilitating discussions, with each person having a chance to practice.

You can (and are encouraged to) attend even as an _audience member only_. This will help participants practice against larger groups.

## Call to Action

- Please comment here if you are interested in attending (keep in mind the time window) as either a facilitator or passive-participant.
- _Optional_ you may indicate if you wish to volunteer to facilitate for the summit. You can opt-in/out later. This is just straw poll.

**Comment by zkat** [comment]
I'd love to attend! I might wait until I get a feel for the experience a little better and have a chance to think about it more before deciding whether to do it during the summit (or save the skill for a later time). This sounds like a generally good life skill to have. :)

**Comment by groundwater** [comment]
@zkat that's great to hear. You can of course decide after the workshop if you feel comfortable participating in the summit.

**Comment by jedireza** [comment]
I'd like to attend the workshop as a facilitator. I'm willing to help at the summit as needed.

**Comment by nebrius** [comment]
I would like to attend the workshop as well. As for the summit, my thoughts mirror @zkat's, I'm on the fence at the moment and would like to wait and see how the training goes.

**Comment by groundwater** [comment]
I updated the writeup to clarify that people can attend as audience members only. Nobody will be forced to practice facilitating if they do not wish to.

**Comment by Trott** [comment]
Interested in attending in either role.

**Comment by isaacs** [comment]
I am interested in this workshop, and potentially facilitating one or more discussions at the summit.  (My objectivity may be questionable for some topics, of course.)

**Comment by Qard** [comment]
Can you record and/or broadcast this, for those of us not in the area at the time?

**Comment by mikeal** [comment]
Being that this is a workshop for teaching a skill that is pretty specific to being delivered in person I don't think it would be effective to broadcast it.

Also, RSVP me :)

**Comment by nebrius** [comment]
Do we have any ideas on time? It will probably be difficult for me to get time off from work during the day to attend. Would it be possible to do during the evening or on a weekend?

**Comment by nebrius** [comment]
_poke_. The summit is two weeks away at this point. @groundwater, have you had any luck securing a date/venue/etc for this workshop? Need help with that?

**Comment by groundwater** [comment]
@nebrius thanks!

Okay, **Thursday Aug 30**, I've booked time at New Relic in SF. This will be *off the grid* so I will just coordinate letting everyone up.

I've booked space from 5 onward, but we can start as late as 6pm. I would prefer earlier to later, but recognize not everyone can make it at 5.

I will provide coffee/tea but please BYO snacks.

**Comment by jedireza** [comment]
@groundwater Did you mean Thursday July 30th?

**Comment by groundwater** [comment]
@jedireza WHOOPS, yes. Thank you for pointing that out. Corrected above.

**Comment by jedireza** [comment]
I'm glad to see this scheduled and sad that I won't be in town for it.

**Comment by nebrius** [comment]
That should work for me, and I can make it at 5pm.

**Comment by zkat** [comment]
I'll be there :)

**Comment by mikeal** [comment]
I'll be there.

**Comment by groundwater** [comment]
Okay. Let's say arrive at 5pm. We'll start soon after.

**Comment by Trott** [comment]
Do you need people to confirm here or just show up? (Uh, confirming: See you 5PM, Thursday July 30 at New Relic.)

**Comment by groundwater** [comment]
@Trott can't hurt to confirm. I will leave someone in the lobby to let people up until 5:20. After that, you're going to have to twitter storm someone to let you up :grin:

**Comment by nebrius** [comment]
I'm afraid I'm going to have to back out of the training. I seem to have picked up the conference plague so I need to rest and don't want to get anyone else sick. 😞

**Comment by groundwater** [comment]
@nebrius :frowning: get well soon!

**Comment by groundwater** [comment]
If you need to reach me, my temporary number is 510.434.6132 (text message works best)

You can probably get access to 12th floor by asking nicely for New Relic. I will also try to have someone in the lobby until 5:30 letting guests up.

**Comment by isaacs** [comment]
I'm so sorry, I was looking forward to this, but I'm going to have to bail.  Too many evening things, not enough time to recuperate.  :(

**Comment by zkat** [comment]
This was great. Thanks for hosting and organizing this, @groundwater!
