### ISSUE TITLE
VM Summit - 2017-03-03

### ISSUE THREAD

**Issue by jasnell** [nodejs/summit#40]
## Agenda

* 9:00 – 12:00 	Morning Session
  * 9:00 – 9:30 	Breakfast / Meet & Greet
  * 9:30 – 10:30 	FFI Presentation / Status Update
  * 10:30 – 10:45	Break
  * 10:45 – 11:45	N-API Presentation / Status Update
  * 11:45 – 12:00	Logistics for Landing into Core
* 12:00 – 1:00	Lunch
* 1:00 – 4:00	Open Agenda
  * Spill over from morning discussions
  * N-API Roadmap (evangelism, documentation, support, repository and distribution, etc)
  * Node-VM Compliance
  * Inspector Protocol
  * Gyp/gn
  * Others (Put other topics here)
    * ?
    * ?

**Comment by pmuellr** [comment]
I don't suspect there will be a live feed of this somewhere, but if so, let us know!

And I hope any content collected can be linked to in a page somewhere; lots of interesting topics, wish I could be there!

**Comment by mhdawson** [comment]
Live feed to just watch: http://youtu.be/ZRVjWhBEwB0

Hangout link to participate: https://hangouts.google.com/hangouts/_/ytl/nRRLLy2l-k9Vh8OtorwVWEZY-OfhJUy3tyn5LZLFeCA=?eid=100598160817214911030&hl=en_US

**Comment by mhdawson** [comment]
If you want to add issues to the agenda that we will discuss if there is extra time, add them to this issue

**Comment by joshgav** [comment]
ref: https://github.com/nodejs/vm/issues/4

**Comment by mhdawson** [comment]
Stream is now muted and video off until after lunch, at which point we'll turn it back on.

**Comment by mhdawson** [comment]
Streaming restarting for afternoon session.

**Comment by mhdawson** [comment]
meeting done

**Comment by joshgav** [comment]
Can someone with close rights close this issue? Perhaps the next one should be listed in https://github.com/nodejs/vm. Thanks!

**Comment by williamkapke** [comment]
@joshgav You should have TSC access now that you are TSC (Org owner).
_Any_ existing owner can do this for you... unless you declined having it.

**Comment by joshgav** [comment]
@williamkapke waiting for that permission bit, particularly for maintenance tasks like this :)

**Comment by addaleax** [comment]
@joshgav See also https://github.com/nodejs/TSC/issues/125 … currently, it’s the CTC members that are org owners, not the TSC ones… I personally wouldn’t see any problem with adding you as an owner
