### ISSUE TITLE
May 4-5 2017, Berlin: Schedule

### ISSUE THREAD

**Issue by addaleax** [nodejs/summit#41]
# Collab Summit Berlin 
May 4-5, 2017
[co.up Coworking
Adalbertstraße 8
10999 Berlin, Germany](https://www.google.com/maps/place/Adalbertstra%C3%9Fe+8,+10999+Berlin,+Germany/@52.501965,13.41923,15z/data=!4m5!3m4!1s0x47a84e3378472c71:0xb2d0599ca60e594c!8m2!3d52.500588!4d13.4191152?hl=en)
> To get in, go through the big metal gate to the left of Adalbertstr. 7, straight to the far end of the courtyard, and in the first tunnel to your right. Ring the doorbell marked "co.up Coworking UG"

### [View the Collab Summit Berlin Project Board to schedule your working group and register yourself to attend!](https://github.com/nodejs/summit/projects/1?fullscreen=true)

*Organizers*
- Anna Henningsen @addaleax
- James Snell @jasnell
- Myles Borins @MylesBorins
- Bryan Hughes @nebrius
- Ashley Williams @ashleygwilliams
- Tracy Hinds @hackygolucky
```
Anyone can come, but we will not be explicitly onboarding at Collab 
Summit Berlin. Conversations can move fast as working groups have 
a lot of context. This Spring instance of Collab Summit will not include
a morning Code + Learn to learn how to contribute prior to congregating
for the summit. Please look to the Fall Collab Summit in Vancouver, BC 
for this pairing.  

Working groups will put together a brief schedule so that people can 
familiarize themselves before folks get onsite, having the general collaborator 
discussions, and then dive into breakout sessions.
```
### Working groups in attendance
We'd love to know ahead who will be represented. Filing issues in this repo is helpful for discussion particular to a working group and how they'd like to manage their time. Linking to that here would be great! We're working on creating a Projects Board to post times for this on the conf agenda so people are aware of when a WG meets and can maybe get a break, if needed. We'll be looking at issues filed in this repo titled "Berlin: working group something something" to add these below as well.  
- Working group that will be at Collaboration Summit
  - Name of contact @github-handle
  - link to working group planning issue
  - Any extra requests(space during conf, av/sound, etc.)

## Day-of Agenda
*May. 4, 2017*
- 09:00-10:00 Introduction and presentations pertinent to majority of audience
- 10:00 - 12:00 Working group breakouts
- 12:00-13:00 Lunch break (not provided)
- 13:00-17:00 Working group breakouts

**Sign up for breakout tables or room [HERE](https://github.com/nodejs/summit/projects/1?fullscreen=true).**

*May 5, 2017*
- 09:00-12:00 Collaborator gathering
- 12:00-13:00 Lunch break (not provided)
- 13:00-17:00 Working group breakouts
  
**Sign up for breakout tables or room [HERE](https://github.com/nodejs/summit/projects/1?fullscreen=true).**

### AV Setup
TBD(asked the venue, waiting to hear back)

### The venue 
[The venue](http://co-up.de/about.html)
- Seven tables in the big room (±155sqm) that can seat 6-8 people each, with 20 office chairs, 50 wooden chairs, a corner with a couch & a few soft chairs.
- Smaller meeting room(15sqm) seats 6-8 people. 
- Welcome to move around the furniture according to your needs!

*Day One Collaboration Summit:*
- intro setup: chairs for everyone
- afternoon setup: tables pulled out for working groups to meet
  
*Day Two Collaboration Summit:(TBD)*
Tables pulled out for working groups to discuss work.
------------------------
  
@nodejs/collaborators @nodejs/v8  @nodejs/ctc @nodejs/tsc @nodejs/community-committee  We should figure out what topics we want to cover. 

Things that were mentioned in https://github.com/nodejs/summit/issues/39:
* Spend time working on our issue/PR backlog (https://github.com/nodejs/summit/issues/39#issuecomment-282870817)
* *Maybe* do a small Code & Learn session (also https://github.com/nodejs/summit/issues/39#issuecomment-282870817)
* Website issues (https://github.com/nodejs/summit/issues/39#issuecomment-289451640) @nodejs/website 
* Streams WG meeting? (more or less implicitly in https://github.com/nodejs/TSC/pull/235) @nodejs/streams
* HTTP/2
* N-API

… what else? No doubt there’s enough ground to cover here.

**Comment by calvinmetcalf** [comment]
streams wg meeting came up here originally https://github.com/nodejs/readable-stream/issues/261#issuecomment-287413053

**Comment by mhdawson** [comment]
Depending on who is going to be there a session on post-mortem would be useful.

**Comment by mcollina** [comment]
Here is our agenda for the in-person meeting (or at least my proposal):  https://github.com/nodejs/readable-stream/issues/275. I can update at the top if you want.

**Comment by yunong** [comment]
@mhdawson I might be able to attend and would definitely want to talk about post-mortem, I wonder if the Microsoft folks will be attending, since they've been working on similar tooling for Chakra.

In general, I'd also want to talk about HTTP/2 and ABI if there are enough folks around.

**Comment by Trott** [comment]
Not exactly Collaborator Summit stuff necessarily, but If some small number of streams folks want to tackle all the remaining bits of https://github.com/nodejs/node/issues/445, that would be awesome. It's been open for more than 2 years, but it also seems achievable.

**Comment by addaleax** [comment]
> I wonder if the Microsoft folks will be attending, since they've been working on similar tooling for Chakra.

@nodejs/chakracore @nodejs/node-chakracore fyi ^^^

**Comment by hackygolucky** [comment]
Planning doc for the event started here https://docs.google.com/document/d/1ai9n0fpYE-3GnUAMKp1U8OdGOtUoQCpzQTBMAwIHXWA/edit# for folks to chime in!

**Comment by aruneshchandra** [comment]
>I wonder if the Microsoft folks will be attending, since they've been working on similar tooling for Chakra.

@yunong @addaleax - Unfortunately @nodejs/node-chakracore team will not be able to make it to this summit, but we would love to meet up at NodeSummit if folks are available.

**Comment by nebrius** [comment]
The community committee is still fleshing out agenda ideas at https://github.com/nodejs/community-committee/issues/28, but we will definitely be there with sessions!

**Comment by joyeecheung** [comment]
Just noticed https://github.com/nodejs/node/issues/11273 might need some attention during the summit (if most of it is approved in the next CTC meetings). It has been a bit stalled and there are many related PRs still open.

**Comment by fhinkel** [comment]
Are any @nodejs/benchmarking folks at the summit?

**Comment by gareth-ellis** [comment]
I'm not going to be able to make it.  unfortunately

**Comment by piccoloaiutante** [comment]
the @nodejs/build is planning an in person session too

**Comment by mikeal** [comment]
I've added the `members` team to this repo so that we can try and use the Project board for scheduling :)

**Comment by hackygolucky** [comment]
Hey all! Added some more finalized details, feel free to edit the issue and add your WG details in the appropriate area. We're working on the Project board that @mikeal mentioned above.

**Comment by hackygolucky** [comment]
Ah, shot that off a little soon.

 We're also setting up a sign-up for folks to register a ticket. It's free, we just need to get an idea for who will attend to make sure the venue and capacity attendance is matching up. We have some flexibility here if we know ahead of time that more people would like to attend, but with JSConfEU happening around the same time, we want to make sure that collaborators absolutely have seats and can get in, if for some reason a LOT of people show up.

**Comment by mhdawson** [comment]
@fhinkel re benchmarking, I'll be there, but @Currykitten won't be.

**Comment by mhdawson** [comment]
@fhinkel if there are people not currently part of @nodejs/benchmarking but who would like to talk about benchmarking it would be a good topic. Always looking to get more people involved.  Given that intel has donated a new machine it might be a good opportunity to talk about how to leverage it in person. @jasnell what do you think ?

**Comment by jasnell** [comment]
Yep, SGTM

**Comment by mhdawson** [comment]
Have I missed the sign-up link or is it not available yet ?

**Comment by mhdawson** [comment]
We probably need a link to a new signup for topics: https://docs.google.com/spreadsheets/d/1gJoyiq0z6rjS7jEoHkRe6jte8Dd7ZBkwD3WjOh6djvQ/edit#gid=0

Went to add one for benchmarking, and see its an old issue.

**Comment by refack** [comment]
I envy you all so much. Really wanted to join, but can't leave the US.
🦅🇺🇸🇮🇱

**Comment by fhemberger** [comment]
Unfortunately, I can't make it this time. :disappointed:

**Comment by fhinkel** [comment]
@mhdawson I added a sheet (May2017) to the [doc](https://docs.google.com/spreadsheets/d/1gJoyiq0z6rjS7jEoHkRe6jte8Dd7ZBkwD3WjOh6djvQ/edit?usp=sharing). I'd say go ahead an sign up.

**Comment by mhdawson** [comment]
@fhinkel Thanks !

**Comment by hackygolucky** [comment]
@mhdawson @fhinkel I update the issue and the [Projects board(https://github.com/nodejs/summit/projects/1?fullscreen=true) to reflect for open tables and the side room available. This was in the hopes that more people would pay attention if we kept everything in GitHub, since last time we had a lot of last minute meetings schedule that conflicted with one another and meant some folks couldn't attend all the meetings they wanted to participate in.

I've also linked the registration form in the Collab Summit Berlin Projects Board, since we need everyone to register(it's free of course!) to make sure we have enough space.

**Comment by jkrems** [comment]
Clicking on the "Signup HERE", I see "This event is not live" - is that expected?

**Comment by mhdawson** [comment]
@hackygolucky works for me, move the N-API one after discussion with the rest of the team so they can call in.

**Comment by hackygolucky** [comment]
@jkrems No that was not expected, ugh. Fixed. :woman_facepalming:

**Comment by hackygolucky** [comment]
As update above, [View the Collab Summit Berlin Project Board to schedule your working group and register yourself to attend!](https://github.com/nodejs/summit/projects/1?fullscreen=true) cc @nodejs/tsc @nodejs/ctc @nodejs/build @nodejs/website @nodejs/evangelism @nodejs/community-committee @nodejs/security-wg  (is there a better way to @ all the working groups?)

**Comment by hackygolucky** [comment]
As update above, [View the Collab Summit Berlin Project Board to schedule your working group and register yourself to attend!](https://github.com/nodejs/summit/projects/1?fullscreen=true) cc @nodejs/tsc @nodejs/ctc @nodejs/build @nodejs/website @nodejs/evangelism @nodejs/community-committee @nodejs/security-wg  (is there a better way to @ all the working groups?)

**Comment by addaleax** [comment]
> is there a better way to @ all the working groups?

Well, there’s @nodejs/members for pinging *everyone* … :smile: (If you’re seeing this notification without context, this thread might be interesting for you if you’re in Berlin next week)

**Comment by jasnell** [comment]
I've added a couple of agenda items for HTTP/2, Promises, and TC-39 Related matters. PTAL :-)

**Comment by nebrius** [comment]
I grabbed the small room for CommComm during the first session on the first day. I figure we can use this to figure out goals/scope for CommComm during collab summit (and hopefully short to medium term goals for the group as a whole over the coming months).

**Comment by watson** [comment]
I'll be attending as well. Anyone who wants to talk about diagnostics, debugging, APM etc let me know 😃 /cc @nodejs/diagnostics

**Comment by claudiorodriguez** [comment]
I'll be around for the morning of the 5th. I'm afraid I don't have much to offer re: working groups, but if anyone is curious about how node fits into a modern react/redux app, I'm happy to offer any insight I can.

**Comment by hackygolucky** [comment]
If folks are having trouble finding the venue from the street(I've quoted the directions from the street into the courtyard gate above), please @ me or other folks you know are already onsite on Twitter(my handle is the same on Twitter).

**Comment by RichardLitt** [comment]
Heard about this yesterday, am here to represent @nodeschool mainly. Here for the community stuff. \o/

**Comment by PatrickHeneise** [comment]
Just arrived, also here for community / NodeConf /cc @RichardLitt
