### ISSUE TITLE
Collaborator's Summit in Vancouver, October 6th and 7th

### ISSUE THREAD

**Issue by nebrius** [nodejs/summit#44]
The last collaborator's summit in Berlin was really productive, and I think most folks are on board with holding them twice a year. I think it makes sense to hold the next one at Node Interactive in Vancouver. Node Interactive itself is on Wednesday October 4th through Friday October 6th.

Here's a few early questions to be answered:

- Do we know if the V8 team has any plans to be in town either before or after, like they were for the Berlin summit? cc @fhinkel @MylesBorins
- Do we want to try and integrate Code + Learn into the summit? There has been discussion about incorporating a Code + Learn into the beginning of the summit, and then help connect the attendees to working groups they are interested in contributing too.
    - I seem to recall we had an issue about this topic somewhere @hackygolucky, but I can't seem to find it. Do you remember if there is an actual issue filed?

~~UPDATE: Please vote using emoji reactions for which days work best for you:~~

~~🎉  - Monday the 2nd and Tuesday the 3rd~~
~~❤️ - Saturday the 7th and Sunday the 8th~~

UPDATE: the Node Interactive venue has been booked for Friday October 6th and Saturday October 7th for the collaborator's summit!

**Comment by mcollina** [comment]
Both are good ideas. I thought we were going for the 7-8 like last year, and almost bought my plane tickets.. can we make a decision asap? Flight tickets would increase in prices the more we wait.

**Comment by sam-github** [comment]
I can do the weekend after, but would prefer the weekdays before.

**Comment by sam-github** [comment]
@nebrius maybe you should run an emoji vote on dates? In terms of venue, if we need a smaller one there are various work hubs around that are generous to hack-a-thons and meetups that might lend us space. @Qard might have some contacts there. @misterdjules might have some ideas on a space, as well.

**Comment by mhdawson** [comment]
I prefer the weekdays as well, but will make it for  whatever days work out best for everybody.

**Comment by Qard** [comment]
Yep, I'm happy to help in any way I can. What sort of scale is expected for the collab summit? CodeCore and Mobify have good spaces, depending on what the scale is.

As for days, I'm happy with whichever. Also, I'd love to get a Code + Learn in there too. :+1:

**Comment by nebrius** [comment]
@sam-github good idea on the vote, OP updated.

@Qard It's a little hard to know scale at this point in time, but I would guesstimate around 60-70 folks

**Comment by addaleax** [comment]
I have a (very mild) preference for the weekdays as well, but I wouldn’t be surprised if @hackygolucky & co already had started planning something?

**Comment by nebrius** [comment]
> I have a (very mild) preference for the weekdays as well, but I wouldn’t be surprised if @hackygolucky & co already had started planning something?

Probably? I haven't heard anything about it, and I know some folks are starting to plan travel (myself included), so it would be nice to get this nailed down quickly so we can book flights.

**Comment by hackygolucky** [comment]
We have the venue booked for the two days after the conf. They need the
days prior for setup so it wasn't available for meeting. We've also
advertised the first day of Collab Summit as part of the schedule,
including code + learn, afaik.

**Comment by mcollina** [comment]
I think that settles it, let's do the two days after the conf.

**Comment by nebrius** [comment]
Thanks @hackygolucky! I updated the title to reflect this info

**Comment by jasnell** [comment]
As part of the collab summit, I would like to have an organized effort to have each of the chartered working groups take 20 minutes each to give a presentation on their status, goals, issues, roadmap, etc. Also, we've talked about this before, but an organized, moderated plenary session co-chaired by the TSC and CommComm chairs would be excellent, along with timeboxed discussions.

**Comment by fhinkel** [comment]
/cc @hashseed @ofrobots @psmarshall because they're going to Interactive. 

I need to double check the dates, but I'll probably be there for the collaborator summit. Last one in Berlin was really productive!

**Comment by bnb** [comment]
@jasnell That's an amazing idea - if possible, it would be great to get these recorded both for those members not present, and those who are otherwise interested but can't attend. Would we need to allocate funds to do that?

**Comment by yosuke-furukawa** [comment]
I will be there as a speaker, and would love to go to collabo summit!

**Comment by XadillaX** [comment]
seems good

**Comment by jasnell** [comment]
@hackygolucky ... I can take the lead on organizing the plenary portion of the Collab Summit.

**Comment by mhdawson** [comment]
I don't see discussion on the agenda for the summit yet, but Anil from Intel was suggesting (and I agree) it would be good to have 1-2 hours to discuss benchmarking.

**Comment by mcollina** [comment]
I would like to have a session on http2, maybe with representatives of the various frameworks (Express, Hapi, Restify) if they are coming or willing to come.

**Comment by danielkhan** [comment]
I'll be there if we manage to have a diagnostics session as outlined here https://github.com/nodejs/diagnostics/issues/103

**Comment by MylesBorins** [comment]
Is there an agenda page? We should likely start something for signups if not

I believe @hackygolucky had something set up last time.

I'd like to see discussions around

* governance
* workers
* installer
* gyp / gc

and maybe more... will think on it

**Comment by Trott** [comment]
> Is there an agenda page? 

While it seems like a good idea to discuss topics ahead of time, I think we might be best served by the unconference model that we've sorta kinda (but not completely) used in the past: Find out how many rooms we have, divvy up into time slots, and people decide (on the day of the event) what topics are discussed where and when. This allows prioritization based on (a) who actually shows up and (b) whatever transpires between now and the event.

**Comment by Qard** [comment]
Well, various working groups have made loose plans for some sort of meeting at past summits. Nothing wrong with having a couple topics prepared when the suggestions are made.

**Comment by Trott** [comment]
> Well, various working groups have made loose plans for some sort of meeting at past summits. Nothing wrong with having a couple topics prepared when the suggestions are made.

Yup, nothing wrong with that whatsoever. Just commenting on the word _agenda_ which I took (perhaps wrongly) to mean setting up times for things to happen.

**Comment by jasnell** [comment]
> Is there an agenda page?

Yes. https://github.com/nodejs/summit/blob/master/2017-10/agenda.md

**Comment by hackygolucky** [comment]
ack sorry that was a mistake.

**Comment by fhinkel** [comment]
This has happened. Closing.
