### ISSUE TITLE
Meta-contributing welcoming group for Collaboration Summit

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/summit#47]
@Trott @addaleax @bengl  @rachelnicole @bnb @mhdawson @MylesBorins @jasnell @bnb 

This will be a meta collaboration session during Collab Summit, designed to get people new to the project who participated in, say, Code + Learn and then onboarding them into the various working groups participating in the collaborator summit. 

I see this going as:
1. We welcome everyone interested in participating. 
2. We split people off into buckets according to interests and where they'd like to get started. 
3. We show them the relevant repos, collaboration and contributing guidelines(if they exist), and after they feel comfortable... 
4. We as leaders walk them over to the working group or folks we know involved and introduce them. 4a. If there is no one present, we do an online intro. 

This is super helpful and breaks the 'oh gah I am terrified to say hi to these people but I want to help' barrier.  Some of this content already exists in the [Getting Started](https://github.com/nodejs/getting-started) repo, but it's always better to walk through things with folks to make it more personal.

**Comment by MylesBorins** [comment]
SGTM. What can we do to help?

**Comment by rachelnicole** [comment]
sgtm too, would it be helpful to start considering the interests and things we'd like to go over ahead of time? Maybe in this issue?

**Comment by jasnell** [comment]
SGTM

**Comment by dshaw** [comment]
I'm happy to help with anyone who overflows into "I'm too corporate to fit in these interest buckets, but still want to engage."

**Comment by hackygolucky** [comment]
@bnb and I had started documenting the onboarding materials for repos in [Getting Started](https://github.com/nodejs/getting-started), and I really think that the documents there + an instruction for the 'Node.js greeters' who will be onboarding folks is the other part of the plan.

**Comment by mhdawson** [comment]
SGTM

**Comment by bnb** [comment]
SGTM. Happy to help however/wherever needed for this before-hand or during the event.

**Comment by Trott** [comment]
Seems like this can now be closed. If I'm wrong, re-open! :-D
