### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by mikeal** [nodejs/summit#5]
So, the initial venue we were looking at fell through and we're currently looking and waiting on several options:
* [Mozilla SF](https://www.google.com/maps/place/Mozilla+San+Francisco/@37.7892969,-122.3892897,15z/data=!4m2!3m1!1s0x0:0x8e0e3ee611504063)
 * My preferred venue as it is quite large and well located for us to leave and go out to lunch/dinner and Mozilla may be willing to provide lunch.
* [New Relic SF](https://www.google.com/maps/place/New+Relic/@37.7913539,-122.3930477,15z/data=!4m2!3m1!1s0x0:0xd46c50778b436768)
 * Large, well located.
 * Waiting to hear from @groundwater if we can book it.
* [IBM BlueMix Garage](https://www.google.com/maps/place/IBM+Bluemix+Garage/@37.7874519,-122.3965307,17z/data=!3m1!4b1!4m2!3m1!1s0x8085807c97e6a22b:0x1bfe77eda7f2a26d)
 * A little tight for 40 people.
 * Waiting to hear from @jasnell if we can book it.
* [Famous Downstairs](https://foursquare.com/v/famous-industries-inc/50e5e9b5e4b050d8c3eb7dbf)
 * Small for 40 people and somewhat awkwardly arranged for that many people (big pillar in the middle).
 * According to @TheAlphaNerd we have it if we want it.

One of the constraints we're operating under is that we can't actually pay any money, or commit to paying money, for a venue until the Foundations budget is approved on the 27th in the next board meeting, so we're trying for places that don't cost anything.

Would love any other suggestions that are free, in downtown SF, and spacious :)

**Comment by mikeal** [comment]
Update: @jedireza is trying to book Mozilla's space in SF. Updated Description.

**Comment by jasnell** [comment]
Sorry @mikeal .. just now saw this. I will follow up on the Bluemix garage space on Monday.

**Comment by mikeal** [comment]
Ok, we are confirmed for the Mozilla "Commons" space at their office in San Francisco. Thanks @jedireza :)
