### ISSUE TITLE
How do we get WGs to stand up and talk in Vancouver?

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#50]
Typically talks requires a bit of prep!
I think we should open an issue on each WG repo to ping them, so that we know who is going to speak.

**Comment by jasnell** [comment]
That could work. What I was thinking is that at the start of the summit we could call out that any group that meets during the working sessions will give a quick status update during the closing... in other words, more ad hoc. Not sure if that would be successful or not.

**Comment by Trott** [comment]
I was imagining a run-down of what they talked about when they met and what decisions (if any) were arrived at. More of a report on their meeting than a presentation.
