### ISSUE TITLE
Working groups, unite!

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/summit#52]
Collaborator Summit is happening next week–October 6-7. We would love to have you suggest what you'd like to see happen by filing issues in this repo. Check out the starter schedule [HERE](https://github.com/nodejs/summit/blob/master/2017-10/agenda.md#nodejs-collaborator-summit-2017-10-06---2017-10-07-vancouver-bc-canada). A recommendation for working groups is to file an issue in your own repo about potential agenda for your working session and link to it on the schedule.

A reminder that you can file for travel fund [here](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.MD#purpose).

Could y'all help spread the word and encourage?
@MylesBorins @mhdawson @bnb @rachelnicole @jasnell @dshaw 
@nodejs/tsc @nodejs/community-committee

**Comment by dshaw** [comment]
@hackygolucky You bet.
