### ISSUE TITLE
Node+JS Interactive - Oct. 10-12, 2018

### ISSUE THREAD

**Issue by JamesMGreene** [nodejs/summit#59]
# Node+JS Interactive - Oct. 10-12, 2018

f.k.a. Node.js Interactive

@ Vancouver, BC

https://events.linuxfoundation.org/events/js-interactive-2018/

## Collaboration Summit

**Dates:** Oct. 12-13, 2018

### Organizers
* Dan Shaw @dshaw
* Matteo Collina @mcollina
* Manil Chowdhury @chowdhurian (in Vancouver)

**Comment by ladyleet** [comment]
Thx @JamesMGreene for starting this issue!

@annmarietonog and I work on community relations at Node Foundation and we would love to start helping plan/collaborate this and support the community as much as possible. 

As node is an open source project, we know time constraints around volunteers can be painful to manage. So we'd love to take as much as we can off your plates as possible!

@dshaw @mcollina @MylesBorins @oe @hackygolucky going to start an email thread about this to see what we can do - or brainstorm on here as well.  

October is coming up quickly! <3

**Comment by trivikr** [comment]
Is Collaborator Summit in Vancouver going to happen over weekend (Oct 13-14)?
If that's the case, more collaborators might be able to join as it's weekend. If it's before the event (Oct 9-10), it might be difficult for some to take off from work.

**Comment by JamesMGreene** [comment]
The Collaboration Summit is on Friday, Oct. 12 @ 1:00 - 5:00pm.

**Comment by mcollina** [comment]
@JamesMGreene the collaborator summit will likely be 2 days, Oct 12th and Oct 13th. The information was **very confusing** last year as well.

@ladyleet can you please confirm we have space for 2 days in Vancouver, like last year?
We will likely run a Code & Learn in the morning, and then summit on the afternoon and the day after.

**Comment by JamesMGreene** [comment]
The Collaboration Summit was 2 days last year, too? That makes way more sense but I left after the first day of it since I didn't know about the second day.

**Comment by mcollina** [comment]
@JamesMGreene the collaborator summit has always been 2 days.

**Comment by JamesMGreene** [comment]
😖

**Comment by ladyleet** [comment]
Hey all and thx @mcollina for the ping. 

Yes - we do have space reserved. Have you all decided who will be the organizers of the next Collab Summit on the community side?

Let's chat about this next week after this Collab Summit and JSConfEU is completed - I will get all the information and we can determine the best action plan next week!

**Comment by mcollina** [comment]
I'm ok in helping again.

**Comment by ladyleet** [comment]
That is great all! :) I'm happy we found the leads. @annmarietonog and I will be coordinating on the Node Foundation side.

Who will be leading and coordinating the Code & Learn from the community side? 

Confirmed from the JS Interactive team that we have Friday and Saturday reserved for the Collaborator's Summit.

Friday will be from 1-6 and Saturday will be from 9-6 if that suits. 

Lunch should probably happen offsite and we would love someone to sponsor this! 

I'm still getting the size dimensions of the rooms reserved but for now:

Friday:
1 large room that can be split into 2
3 small breakouts

Saturday:
5 rooms

Additional question: Someone mentioned updating the website - do they mean the JS Interactive website to list out the code & learn and the collab summit?

Thanks much all! <3

**Comment by mcollina** [comment]
> Additional question: Someone mentioned updating the website - do they mean the JS Interactive website to list out the code & learn and the collab summit?

Yes. We need to list also Saturday, it created so much confusion last year.
Moreover, that would need to be listed as the _Node.js_ Collaborator Summit.
We need to mention that the event registration for the event will happen at XYZ, and that a ticket for the conference is _not needed_.

@nodejs/tsc @nodjes/community-committee are you in allowing access to non-collaborators? We would not have space for all attendees of JS Interactive, and we need some text to limit attendance (or maybe not).

@ladyleet how many people could we host both days?

**Comment by ladyleet** [comment]
@mcollina still waiting on dimensions of rooms and the layout specs.

I'll poke around at the website and discuss with the JS Interactive team! :) Currently Friday is listed but Saturday is not - so that def needs to be changed.

Yes - please discuss on this thread what y'all are thinking of making sure you don't have a slew of people on Saturday. I would suggest we keep the conf dates listed as the same as it is currently 10-12 but perhaps list out the Collab Summit for Saturday too on the agenda? Do we need any special verbiage about what the Collab Summit is, etc? 

I suggest we set up an Eventbrite or Google form to collect the info for Collab Summit this time. The registration could remind people that they need to be a collaborator - or give people more insight into what the Collab Summit actually is.

// @annmarietonog

**Comment by mcollina** [comment]
> Yes - please discuss on this thread what y'all are thinking of making sure you don't have a slew of people on Saturday. I would suggest we keep the conf dates listed as the same as it is currently 10-12 but perhaps list out the Collab Summit for Saturday too on the agenda? 

I think that would be ok. What does other things?

> Do we need any special verbiage about what the Collab Summit is, etc?

I think some special verbiage about the collab summit is needed. I would also add a link in the registration process with some text like "If you are a Node.js collaborator, the collaborator summit is going on 12th and 13th (one more day after the conference), don't forget to register at LINK". Feel free to change this to fit the process.

**Comment by ladyleet** [comment]
@mcollina just an FYI @annmarietonog and I are discussing this today.

**Comment by mcollina** [comment]
Awesome, let us know how it goes!

**Comment by ladyleet** [comment]
Submitted a PR for this to update the README.MD https://github.com/nodejs/summit/pull/98

**Comment by ladyleet** [comment]
@JamesMGreene can you update your top comment on this to include the dates for the summit pls? :)

**Comment by AnnMarieTonog** [comment]
@mcollina got the info on the different rooms today! 

For Friday, they have one large room for 100 persons + three small rooms that can fit 10 each. The one large room can also be split into two smaller rooms that can fit 60 each. Lara did mention that once the rooms are set, we can’t really go from one to two rooms or vice versa in a timely manner (basically, we should decide whether we can one or two rooms beforehand). 

For Saturday, they have one room for 100 + four rooms for 50. 

// @ladyleet LMK if there any details I might've left out!

**Comment by JamesMGreene** [comment]
@ladyleet Added.

**Comment by hashseed** [comment]
Are there going to be slots for presentations?

I was approached to give an overview over Node.js', Chrome's, and V8's release schedules, how we do integration testing, and how bisection into V8 works.

**Comment by rachelnicole** [comment]
I'd love to help out with Code & Learn

**Comment by tniessen** [comment]
@rachelnicole Me too! I think I can get a couple dozen tasks together 🤔

**Comment by joyeecheung** [comment]
> are you in allowing access to non-collaborators? We would not have space for all attendees of JS Interactive, and we need some text to limit attendance (or maybe not).

I thought we always allow WG members? (basically everyone under this organization).
If space is a concern then limiting the attendance makes sense to me, but there could be people from other organizations who want to collaborate with us like in Berlin - we had V8 team members, people from the TC39 and people from the WASM working group.

**Comment by mcollina** [comment]
I think we should not be limiting attendance, but I will restrict it at member of this org + guests.

**Comment by joyeecheung** [comment]
Maybe we should plan the agenda a bit earlier beforehand and use something similar to [ti.to](https://ti.to) to count how many people would be attending?

I also think that we should take a look at the proposed agenda and make sure we drop the ones that are better left online or hard for remote participant to join. Open-ended discussions without a clear goal or a good explainer in advance tend not to be effective in summits.

**Comment by MylesBorins** [comment]
So qq
With the rate of velocity we currently have, do we want to run another code
and learn?

**Comment by jasnell** [comment]
I would think so. The events typically have not had much impact on the pr rate over time. They instead cause a single spoke that is typically quickly dealt with. With the fast track and properly scoped tasks, it shouldn't be much of an issue imo.

**Comment by addaleax** [comment]
I’d stick with the messaging that we used in #60: Anyone can come, but expectations should be set right. (“this org + guests” sounds like we’d be making kinda arbitrary decisions about who a guest is.)

**Comment by joyeecheung** [comment]
Can we use some sort of service to count the number of people planning to attend before putting up a text? Who knows, if we make sure people are aware what they would sign up for by coming to the summit, maybe not that many people would be interested in attending the summit and we don't need to limit the attendance at all :3.

I also slightly worry about the velocity, but that kind of depends on our tasks. Also it would be nice if we can use backports or fixing flakes as tasks for those who finish quickly and want something more challenging.

**Comment by jasnell** [comment]
Previously the Foundation had set up registration for the code and learn specifically for purposes of estimating attendance. It worked reasonably well in that we had a large enough room for all the additional people who did not register but still showed up.

I think the best way to limit the attendance in the collab summit is to simply *not advertise* it. We let collaborators know about it and if others just happen to come across it and stumble in, that's perfectly fine, but most interactive attendees won't even think to go if it's not in the calendar.

**Comment by ladyleet** [comment]
Hi all! Notes from myself and @AnnMarieTonog from the Foundation side:

- @joyeecheung @jasnell Yes - we will use some sort of attendance setup like ti.to to make sure we get headcounts. 
- @rachelnicole Thank you for volunteering to help with Code & Learn! Should I add you and @tniessen as the official Code & Learn leads?
- @jasnell the complaint has been that folks who wanted to attend the Collab Summit before did not know about it because it was not clear.

Things we need (will wait on @mcollina @dshaw @chowdhurian to chime in since they are leading for direction).

1. Should we set up a ti.to for both Code & Learn and Collab Summit SEPARATELY? I guess question is how you would want this to be set up and it will depend on how you decide to "market" collab summit.
2. Can we add verbiage that @rachelnicole and @tniessen are leads if they agree to be the official leads for this?
3. Circling back to the marketing question - let's decide asap how we want this promoted on the JS Interactive site so we can put it up.
4. This is getting so messy so I am going to create another .md doc with @AnnMarieTonog  for organizing things like how many people we can fit, etc so we don't have to sift through this huge comment thread.

**Comment by Trott** [comment]
I had been operating under the assumption that (if she's willing) @addaleax and (whether or not she's wiling) I would be leading Code + Learn, but I'm totally fine to let someone else who's eager to take it on do so. I would recommend making it someone who's run more than one similar and successful smaller scale first-contribution-to-Node.js events, although that admittedly limits the leadership pool to basically @addaleax, @benjamingr, and me. Maybe @bengl too. 

The alternative is to change the focus from first-contribution-to-Node.js-core and make it more contribute-to-Node.js-more-broadly-defined. I'd be fine with that too.

**Comment by jasnell** [comment]
My preference is for @trott and @addaleax to lead code and learn. They've more than demonstrated their ability to lead it successfully on multiple occasions.

**Comment by ladyleet** [comment]
@jasnell okay well let's all work together! we def need a lot of people being a part of the code & learn and it would be great to give people more knowledge so others can learn how to run code & learns. What do y'all think? Maybe have 3-4 leads and then a bunch of volunteers?

**Comment by joyeecheung** [comment]
> Should we set up a ti.to for both Code & Learn and Collab Summit SEPARATELY? I guess question is how you would want this to be set up and it will depend on how you decide to "market" collab summit.

I think we should. Based on my observation most code & learn attendees leave after the code & learn session instead of attending the summit that follows, and a lot of people attending the summit (e.g. WG members) do not attend/mentor the code & learn.

I think we definitely want to promote the code & learn in the website, but not necessarily the summit because people who want to go to the summit usually already watch this repo or can learn that from twitter.

**Comment by tniessen** [comment]
> I had been operating under the assumption that (if she's willing) @addaleax and (whether or not she's wiling) I would be leading Code + Learn

I'd prefer this, I can help out in person and provide some tasks beforehand, but @Trott and @addaleax are in a much better position to lead it!

**Comment by ladyleet** [comment]
@joyeecheung okay - well currently Friday is marketed on the site as Code & Learn and Collab Summit - Sat is not listed.

@AnnMarieTonog and myself can set up a ti.to for Code & Learn separately and Collab Summit separately.

Can we get some consensus? :) ❤️

**Comment by ladyleet** [comment]
@tniessen 🎉

**Comment by ryzokuken** [comment]
I'd love to volunteer to help with the Code+Learn as well, but yeah, @addaleax and @Trott should lead it, definitely.

**Comment by AnnMarieTonog** [comment]
Hey, everyone! Just wanted to keep all of you in loop with what @ladyleet & I are working on!

- Updating information on the JS Interactive website (https://events.linuxfoundation.org/events/js-interactive-2018/agenda/agend-at-a-glance-2/)
          - Making sure it says “Node.js Collab Summit”, instead of just “Collab Summit” 
          - Adding second day Oct 13, making sure to avoid advertising it
- Figuring out registration for both Code + Learn & Collab Summit
          - Working with the events team to set this up, so we don’t have to make a separate registration 
             apart from JS Interactive registration 

If there’s anything else you need help with please let me know! :) More than happy to assist where I can.

**Comment by AnnMarieTonog** [comment]
Hi, all - worked with the events team to create a way for separate registration for Collab Summit

Link here: https://www.regonline.com/?eventID=2152653&rTypeID=511098
Access code: COLLABSUMMITONLY 

This can also be a way for collaborators to get visa letters needed for travel - the email confirmation you receive after registering will provide details on this, or you can just go ahead and visit this link:
https://events.linuxfoundation.org/events/elc-openiot-north-america-2018/attend/visa-request/

For any requests that have been previously been denied, please register first for the summit, then re-send your request in through the visa request form.

// @ladyleet

**Comment by ladyleet** [comment]
Yes - we did hear that a few were denied for some reason - perhaps it was because there was no registration attached? Happy to help trouble shoot this.

Let us know if you have any questions!

**Comment by MylesBorins** [comment]
I've cross posted this on the foundation members discussion board for visibility

https://github.com/orgs/nodejs/teams/members/discussions/10

**Comment by codeekage** [comment]
Nigeria is not in list of country on the form.

**Comment by ladyleet** [comment]
Looking into this @codeekage

**Comment by codeekage** [comment]
Thank you @Ladyleet

**Comment by ladyleet** [comment]
@codeekage you are talking about registration for JSI correct? If you are talking about registration for JSI you can just choose the nearest country. 

Our system (I know, I wish we could change this) will not add Nigeria bc they have experienced fraud before. 

Hope this helps? Let me know. And thanks for bringing this up!

**Comment by lance** [comment]
I missed the survey @joyeecheung just closed. I plan to be at the conference and the summit. Is there some place to register this besides the survey? Thanks.

**Comment by joyeecheung** [comment]
@lance The survey was mainly used to estimate the cost so that we can get back to the foundation events team with a number of JS Interactive tickets we need them to sponsor. If you do not need a JS Interactive ticket (which is separated from the collab summit), I think you can just leave a comment in https://github.com/nodejs/summit/issues/59 since we do anticipate more people to show up than those who participated in the survey.

**Comment by lance** [comment]
@joyeecheung thanks for getting back to me. I do not need a ticket for JS Interactive, but will be there for both the conference and the collab summit. Looking forward to it!

**Comment by ChALkeR** [comment]
![screenshot_20180805_214248](https://user-images.githubusercontent.com/291301/43688798-7f5fde3a-98f8-11e8-9a0c-ac5fa5671d6c.png)

> You will only be charged a cancellation/no-show fee of $50.00 USD if you do not cancel by 11:59pm PST on Tuesday, October 2, 2018, or do not attend the event.  Your credit card will only be charged under these circumstances.  This helps us in planning accurately for the event.

I don't think that I entirely understand what is written there :-/. I suppose that this means that «if you do not cancel by … **and** do not attend», but when reading it on the first time, it did not look clear to me what would happen if I do not cancel and attend the event. Or if I do cancel before October 2, and do not attend the event.

**Comment by ladyleet** [comment]
Yes in order to account for the cost of saving the space and getting the food you will need to cancel by October 2 or if you were a no-show then you will be charged $50. 

Unfortunately this is the standard and we weren’t able to change it but hopefully it just makes everyone accountable so that we don’t rack up a huge bill for the space and food :-)

**Comment by ChALkeR** [comment]
@ladyleet that itself is totally fine, I am saying that the exact wording is on that page is unclear.

**Comment by ChALkeR** [comment]
It says:
> You will only be charged a cancellation/no-show fee of $50.00 USD if you do not cancel by 11:59pm PST on Tuesday, October 2, 2018, or do not attend the event.

It can be read as: «You will only be charged _in either of these two cases:_ **(1)** you do not cancel by 11:59pm PST on Tuesday, October 2, 2018, **(1)** you do not attend the event». Which, as I presume, is not what was meant.

**Comment by ladyleet** [comment]
I see what you mean I’ll bring this up with the events team :-)

**Comment by ladyleet** [comment]
@Trott @addaleax how can folks like @choilmto get involved with code & learn? 

@choilmto if you are attending JSI, you are welcome to attend collab summit as well!

**Comment by benjamingr** [comment]
@ladyleet the Node collaborator summit is typically limited to project members - people who are not Node core or involved in Node initiatives directly will likely not benefit from attending.

As for code & learn - I think it would be great if they participated and volunteered - though as a participant in the code and learn rather than as a mentor since a code & learn literally teaches how to contribute code to Node core (unless they are already a collaborator and I missed it).

**Comment by mcollina** [comment]
@benjamingr either it's open to the public, or it is limited to members/collaborators. In the past, there have been significant contributions from individuals that were not members, but rather people that are interested in some of the subjects that just wants to be part of the discussion. Thanks to this approach, we welcomed more people into our community.

**Comment by mcollina** [comment]
@JamesMGreene @ladyleet I find the current title of this issue misleading. Should we make it 10-13 instead?

**Comment by ladyleet** [comment]
The topic of public or not was also discussed in this issue # https://github.com/nodejs/summit/issues/101

**Comment by ladyleet** [comment]
Just FYI super stoked that Netflix will be sponsoring Day 1 (Friday) lunch at Collaborator's Summit! Thanks so much @yunong for making this happen! :)

**Comment by SMotaal** [comment]
Is there a possibility/need for a non-member wanting to become involved to help around collab coding or other sessions?

**Comment by mcollina** [comment]
Yes, everybody is welcomed. See https://github.com/nodejs/summit/issues/100
for more details.

Il giorno lun 17 set 2018 alle ore 21:06 Saleh Abdel Motaal <
notifications@github.com> ha scritto:
