### ISSUE TITLE
i18n & l10n

### ISSUE THREAD

**Issue by zeke** [nodejs/summit#61]
Let's talk about internationalization and localization!

From https://github.com/orgs/nodejs/teams/i18n:

> The recent [Node.js i18n proposal](https://medium.com/the-node-js-collection/internationalizing-node-js-fe7761798b0a) has met consensus, and there’s going to be a lot to talk about and do.

The work will probably already be underway by the time May/June rolls around. If there's enough interest at the summit, I'd love to lead and/or participate in a discussion about this effort.

**Comment by Rukeith** [comment]
I think it will be great to discuss about this.

**Comment by bnb** [comment]
I'd love to join in on this discussion. Also worth pinging the @nodejs/i18n team to
 see if any other members can make it ❤️

**Comment by obensource** [comment]
@bnb [done](https://github.com/orgs/nodejs/teams/i18n/discussions/2). 💥

**Comment by rachelnicole** [comment]
If I can make it I'm def into this!

**Comment by Tiriel** [comment]
Same here!

**Comment by maddhruv** [comment]
I am very interested and excited about coming to the *Summit* and meet the @nodejs/i18n team,  I'll definitely be there. :relaxed: :relaxed:

**Comment by vanessayuenn** [comment]
🙋very into this!

**Comment by obensource** [comment]
We've got quite a bit of interest going here! So stoked to see y'all there and make rad stuff happen together! 🙌

**Comment by sotayamashita** [comment]
I'd like to join if I make it

**Comment by maddhruv** [comment]
@zeke @obensource
Please add me over the line

I am not able to make to the Summit :(

**Comment by zeke** [comment]
We have a meeting up. You should be able to join here: https://app.chime.aws/meetings/7635603096

**Comment by zeke** [comment]
Follow this project to see what's shipped recently, and what's coming up next: https://github.com/nodejs/i18n/projects/1

**Comment by obensource** [comment]
Meeting Recap:

* We were able to integrate our crowdin-user bot with Node.js for integration with the Crowdin Service.
* We set up the Crowdin–GitHub integration.
* We setup and turned on Travis CI in the i18n repo for testing and more–and it just worked!
* Dan gave us an update on Ecma402, and we discussed how we can get further involved with them over time.
