### ISSUE TITLE
Summit Topic: the scope and status of a core collaborator

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/summit#67]
Refs: https://github.com/nodejs/node/issues/20367
Refs: https://github.com/nodejs/node/issues/20589

Opening a new issue since https://github.com/nodejs/summit/issues/60 is already pretty long. The collaborator summit is a good opportunity to discuss about this topic.

------------------

Time: 9:30 - 10:30, June 1 2018
Place: Mozilla Berlin
Champion: @MylesBorins @joyeecheung

Proposed agenda (no necessarily in this order):

- An overview of activity of existing collaborators in the past year (Joyee)
- A proposal regarding https://github.com/nodejs/node/issues/20367 (Joyee)
- Discussion about the scope of collaborators
  - Define who they are
  - What access should they have
  - What makes a contributor a potential nominee
  - Potential improvement of https://github.com/nodejs/node/blob/master/GOVERNANCE.md#collaborator-nominations
- Growing Collaborators (Myles)

**Comment by joyeecheung** [comment]
cc @mcollina can you put this in a slot, thanks.

**Comment by benjamingr** [comment]
Note this also heavily relates to https://github.com/nodejs/summit/issues/64

**Comment by joyeecheung** [comment]
I will try to gather some stats using https://github.com/nodejs/node-core-utils/pull/186 and present a more concrete proposal during that session.

**Comment by mcollina** [comment]
I would like to run an interactive session with this. Specifically, I would like for the participants to brainstorm on this together. Maybe you can present that data and then we can ask the participants to work on this in groups. I will share some plans with you tomorrow morning if you are interested.

**Comment by joyeecheung** [comment]
I updated the OP with a proposed agenda.

@mcollina I will be on a plane tomorrow morning (Berlin time), probably won't have WiFi there. You can leave comments here or we can find some time to discuss before Day 2.

**Comment by chowdhurian** [comment]
Minutes doc! Feel free to add.

If you have notes for 9:30 to 10:15, let's combine.

https://docs.google.com/document/d/1pGCG91U9tcpR-i6ntg1TWhN0gSRJXCjs1Un2Cf-ul5A/edit?usp=sharing

**Comment by joyeecheung** [comment]
https://tcq.app/meeting/6tS3

**Comment by joyeecheung** [comment]
Data added in answer to a question in the session

- The last commits of 17 collaborators were adding themselves to the README (14% of the existing collaborators)

**Comment by benjamingr** [comment]
@joyeecheung can we see if any of them haven't had any interaction in the repo in the last 6 months and ask them to consider moving to emiratus status?

**Comment by Trott** [comment]
> @joyeecheung can we see if any of them haven't had any interaction in the repo in the last 6 months and ask them to consider moving to emiratus status?

FWIW, just a month or two ago, I emailed 8 people who haven't had any commits in the last 2 years and asked them if they'd like to move to Emeritus. 1 person took me up on it.

(Yes, commits != activity. I was using it as a rough proxy because it was easy for me to determine commit activity without learning anything about GitHub APIs.)

**Comment by benjamingr** [comment]
@Trott 

> 1 person took me up on it.

Thanks for doing this and for the info!
 
Did the other 7 respond saying they're still interested in playing an active role in the project?

**Comment by Trott** [comment]
> Did the other 7 respond saying they're still interested in playing an active role in the project?

I believe 3 responded and asked to remain Collaborators. (They have been active commenting on issues and/or reviewing PRs.) 4 did not respond at all.

**Comment by apapirovski** [comment]
> 4 did not respond at all.

Seems nearly equivalent to agreeing to it. That's just my opinion, of course.

**Comment by Trott** [comment]
> Seems nearly equivalent to agreeing to it. That's just my opinion, of course.

I'm of that opinion too. I think I intended to run the revised name list past TSC but didn't. I'll do it now.
