### ISSUE TITLE
Agenda for Diagnostics session at collaborator summit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/summit#71]
First cut please comment:

* Quick intros
* Async terminology - Mark will lead.  [PR #197](https://github.com/nodejs/diagnostics/pull/197).
* Async hooks - exist criteria
* Update on other actions from Diagnostic summit
  * nodereport into core (Michael)
  * tracing (? James will not be at the summit, not sure if anybody else can do an update)
  * etc.
  * Expectations on https://github.com/nodejs/diagnostics/issues/157
* Promise hooks changes in V8
* Testing
* Post mortem merge with Diagnostics
* Walk through proposal for current resource for async hooks

#### Present
Yunong
Anna
Joyee
Vladimir
Bethany
Dan
Stephan
Mark
Thomas
Jan
Jeremiah
Ruben
Matteo
Benjamin
Maya
Ali
Anatolli
Greoge
Greg
Michael

**Comment by Trott** [comment]
This is an agenda for one specific session at the summit, right? If so, can you add the name of the session to the title of this issue? Otherwise it looks like it's supposed to be an agenda for the entire summit.

**Comment by mcollina** [comment]
I guess this would be for the diagnostics session? Could you please adjust the title?

**Comment by mcollina** [comment]
@jasnell will not be at the Berlin summit.

**Comment by benjamingr** [comment]
> Promise hooks changes in V8

I would love to attend this and I am currently doing a lot of research on this and in general I would love to attend this session - does this overlap with the modules team working group? 

Also note there is specifically a promises workshop at a later point and I was planning to talk about use cases for the promise hooks there :)

**Comment by mhdawson** [comment]
@mcollina yes will be for the diagnostics session.

**Comment by mhdawson** [comment]
I did mention the promises workshop but other people in the meeting thought it would be covering different topics.  As long as its covered in one of the 2 I think people will be happy.

**Comment by mike-kaufman** [comment]
RE "async terminology", please see [PR #197](https://github.com/nodejs/diagnostics/pull/197) which describes the current direction & set of terms.

**Comment by tlobinger** [comment]
Meeting Link: https://chime.aws/1822360907
Meeting ID: 1822 36 0907
U.S. Toll: +1 206-462-5569
Meeting PIN: 1822 36 0907
U.S. Toll-free: +1 855-552-4463
International: https://chime.aws/dialinnumbers/

**Comment by tlobinger** [comment]
Just making sure that this is clear - you won't need an account but can call in as a guest with the client.

Also with the client you can share your screen with others in the room as well as remote.

**Comment by joyeecheung** [comment]
link to node-report WIP PR: https://github.com/nodejs/node/pull/19661

**Comment by dshaw** [comment]
@gtewallace @nodejs/user-feedback Question from this group:
What percentage of Node.js users are using an APM?

**Comment by mhdawson** [comment]
Diagnostics Session Summary

- Async terminology - update from Mark
  - Please provide feedback on https://github.com/mike-kaufman/diagnostics/tree/mkaufman-add-async-context/async-context
- Async Hooks exit criteria
  - Need terminology to be comfortable we have API `right`
- Actions from last Summit
  - node-report into core
    - PR with steps immanent
  - testing tiers
    - add tests
    - propose Tools/tiers
    - Possible survey
- Merge Post-mortem and Diagnostics WG
