### ISSUE TITLE
Brainstorming session on Recognizing The Unglamorous Parts

### ISSUE THREAD

**Issue by bnb** [nodejs/summit#77]
Per a twitter discussion with @ofrobots, @mhdawson, and @jasnell I'd really like to see us have a discussion on how we can lift up and recognize those who are doing work on the more unglamorous parts of Node.js.

We largely owe Node.js's smooth operation to these individuals, yet we very rarely discuss the work they do. I'd like to propose that in this session we work on how we can be more vocal about that work and the individuals who do it.

**Comment by benjamingr** [comment]
Somewhat related to https://github.com/nodejs/summit/issues/64

**Comment by mhdawson** [comment]
A few ideas to start.

Everyday hero award
Prioritize these areas in the badges effort
More discussion/coverage in TSC meetings
Regular thanks in tweets from the node.he foundation account.

**Comment by Tiriel** [comment]
This is definitely a good idea, and I'd like to attend this if I can!

**Comment by mhdawson** [comment]
I agree that we need to make it easier for people to help out but at the same time I think some work on the recognition side would still be a good thing.

**Comment by Trott** [comment]
Making things scale is the most important thing. The growth of the Node.js project has been astonishing, and it's been rewarding to be a part of it. But the project's practices just aren't scaling. Recognition won't hurt, but without addressing the aspects of the project that have become unmanageable, it's a lot of proverbial deck chairs on the Titanic.
