### ISSUE TITLE
Docs: Integrating with All The Groups

### ISSUE THREAD

**Issue by bnb** [nodejs/summit#79]
There are two CommComm efforts (Website Redesign and i18n) that are currently interested and dealing with working around the Node.js Docs. I've also seen some renewed interest in a few other places around making the docs experience better.

I'd love to have a session that we can pull together interested individuals and groups together to discuss Docs and how we can all work together on them 👍

**Comment by NickNaso** [comment]
I'd like to attend at this session. I'm interesting on share ideas on how to create a standard for documentation and on how to improve it to make it something more than a reference.

**Comment by purplecode** [comment]
Meeting Link: https://chime.aws/7259704916
Meeting ID: 7259 70 4916
U.S. Toll: +1 206-462-5569
Meeting PIN: 7259 70 4916
U.S. Toll-free: +1 855-552-4463
International: https://chime.aws/dialinnumbers/

**Comment by tlobinger** [comment]
Just making sure that this is clear - you won't need an account but can call in as a guest with the client.

Also with the client you can share your screen with others in the room as well as remote.

**Comment by tolmasky** [comment]
This is me making a comment as asked.

**Comment by erulabs** [comment]
Leaving contact information: Seandon@runkit.com - interested in helping out with analytics!

**Comment by pouwerkerk** [comment]
I attended as well! Happy to help out as needed!

**Comment by bnb** [comment]
Here are my notes from the meeting: https://docs.google.com/document/d/1uxzMQtWHMga2NKflHhLgyaIdvEsLaVgwjdkgoNyCOlk/edit?usp=sharing

**Comment by dkundel** [comment]
Would love to help out with content related things :)

**Comment by fhinkel** [comment]
I was there 🙋

**Comment by tlobinger** [comment]
https://s3-eu-west-1.amazonaws.com/ponyhof/2018+05+31+Node.js+Summit+-+documentation+working+group.mp4

feel free to upload to YouTube or whatever the preferred channel is.

**Comment by NickNaso** [comment]
I can help on improving  and fixing tutorials.

**Comment by add1sun** [comment]
I was there, and willing to help out where it makes sense.

**Comment by Trott** [comment]
Closing issues for sessions that happened. Re-open if that's the wrong thing to do.

**Comment by pouwerkerk** [comment]
@bnb: I added my meeting minutes to the doc you shared. (Also, this is a [Google doc](https://docs.google.com/document/d/1V63oQx8eIuAHMTLpUhyx2gNNs1FuuaJG7MJxs2Uuc5A/edit) for the meeting minutes with formatting, and [here are these notes in Markdown](https://gist.github.com/pouwerkerk/485ba5e5850f89a354bb4286f0b1af87) if we wanted to put this in [nodejs/website-redesign > meetings](https://github.com/nodejs/website-redesign/tree/master/meetings)).
