### ISSUE TITLE
Summit Topic: Streams Future API(s) Session

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/summit#82]
If some folks were interested, I'd be willing to lead a kind of thing at the collab summit about how to move forward with our future streams api project (and/or alternatives).

This could include some kind of review / discussion about it and other potential alternatives.

- Current repo: https://github.com/Fishrock123/bob

cc @jasnell, @mcollina, @mafintosh, @addaleax

**Comment by benjamingr** [comment]
I would love to attend in order to understand it better as well as understand why the API change is needed for the performance improvements (and why?).

I would also appreciate any slides you have on the topic (or if you've given a talk about it - that would also help).

**Comment by Fishrock123** [comment]
Unfortunately, I don't have any slides. (I'm on Vacation atm so also won't be making much of anything.)

I think there should be enough collective knowledge between myself, James, and Matteo to be able to disseminate it better at the summit, though.

**Comment by jasnell** [comment]
I won't be at the summit but would love for there to be discussion on this

**Comment by NickNaso** [comment]
I'd like to attend at this session.

**Comment by mcollina** [comment]
Topic: Streams Session at the Collaborator Summit 2018
Time: May 31, 2018 3:30 PM Amsterdam, Berlin, Rome, Stockholm, Vienna

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/942530127

Or iPhone one-tap :
    US: +16699006833,,942530127#  or +16465588656,,942530127# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 669 900 6833  or +1 646 558 8656  or +1 877 369 0926 (Toll Free) or +1 855 880 1246 (Toll Free)
    Meeting ID: 942 530 127
    International numbers available: https://zoom.us/u/dymTWfm9W

**Comment by mcollina** [comment]
Some of the notes from the sessions:

* Streams cookbook.
* How do we scale the dev?
* Document the userland modules.
* Add tests for the event ordering.
* Use readable-stream as the issue tracker / call to action for streams.
* We need mini streams summit.
