### ISSUE TITLE
Summit Topic: Scoping core modules

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/summit#84]
Refs: https://github.com/nodejs/TSC/issues/389

> We can use a slot in the collaboration summit to discuss about this. The decision should not be made there but we can brainstorm about the pros and cons of scoping modules and come back with a proper proposal/some kind of document

------------

Proposed agenda:

- Identify upcoming APIs that could be exposed via a new module ID
- Discuss about scoping strategies
  - What scope should that be? `@nodejs`?
  - Should we use `@scope/module` or `scope:module`?
  - What happens to existing modules?
  - What's the migration path and story for modules that support multiple versions of Node.js?
  - What about unscoped modules that are taken on npm? e.g. `@scope/new_api` v.s. `new_api`
  - What happens to code that runs on the browser with browser-core polyfills?
- Brainstorming pros and cons of scoping modules

**Comment by MylesBorins** [comment]
Did this get followed up on? Could be a good session for also discussing the future of core apis

**Comment by joyeecheung** [comment]
@MylesBorins I can draft some topics to discuss, maybe we can also look at upcoming APIs and discuss about a better strategy for graduating them in the future

**Comment by benjamingr** [comment]
@joyeecheung I have left an idea here: https://github.com/nodejs/TSC/issues/389#issuecomment-392504998

**Comment by joyeecheung** [comment]
Copied from @benjamingr 's comment

>  - What happens to existing modules?
> - What's the migration path and story for users on older versions of Node.js or authors of packages that need to run on both scoped and unscoped module versions of Node.js?
> -  What happens if a user owns an unscoped version of a module we're adding https://github.com/nodejs/TSC/issues/389#issuecomment-392257060 ? Anything we can do to prevent people from being malicious in the future?
> - What happens to code that runs on the browser with browser-core polyfills? How does versioning work since that code is less-strictly-versioned and users might be using it with old/new Node.js together.

**Comment by devsnek** [comment]
will remote participation be available?

**Comment by Trott** [comment]
@devsnek I don't know the details, but several people have indicated they will be attending remotely, so I'm pretty sure there's a remote attendance option planned. Let me see if I can find anything...

**Comment by Trott** [comment]
Hmmm...some talk about remote attendance but no indication that I can find that someone is actively working on making it happen... I hope the AWS office has something slick already dialed in or else this might be a problem...

**Comment by ljharb** [comment]
Notes, or at least a summary, would be appreciated for those who were unable to attend.

**Comment by mcollina** [comment]
The full day has ideally been recorded. We need to look at the footage and check where this lives. My current wi-fi availability is not going to be enough for the next week or so, so I would recommend if somebody has access to our Zoom account to go in "recordings" and check what we have.
