### ISSUE TITLE
Summit Topic: Website Redesign – Content Creation

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/summit#89]
## Motivation
A website redesign requires more than just information architecture reworks and new designs mocks! To truly create something useful for the community we need more roust, better targeted, and well organized content. Under the new IA, this content largely falls under the "Learn" section (containing "Getting Started" guides and the very nebulous "Advanced Topics" section), and the home page messaging. 

In this session we will quickly review progress made by the Website Redesign Working Group thus far, then dive into a number of exercises and activities to kickstart our new content creation. At the end of this session we expect to deliver:

 - 3-6 User Personas
 - A collection of "Getting Started" and "Advanced Topics" section titles, ready for drafting
 - Discussion started around "Learn" section organization and home page messaging (stretch goal, time allowing)

## Agenda
 1. Review high-level report of progress so far (5 mins)
 2. Deep Dive: Content Creation
    a. Stakeholder Identification Exercise (10 mins)
    b. User Persona Creation Activity (20 mins)
    c. Topic Creation – News Conference Exercise || Post-It Game (10 mins)
    d. Topic Mapping – In and Out Game (20 mins)
3. "Learn" page IA and home page messaging – Open Discussion (remaining time)

Related session topic: https://github.com/nodejs/summit/issues/79. Will cover the more technical and cross-functional aspects of documentation drafting, ingestion and translation.

**Comment by maddhruv** [comment]
@amiller-gh @bnb please share some method i could connect remotely
I was not able to make it to the Summit 'cause of delayed VISA

**Comment by sagirk** [comment]
@amiller-gh @chowdhurian @bnb +1 to what @maddhruv said about remote!

**Comment by chowdhurian** [comment]
@maddhruv @sagirk the session was switched to 15:30 local time.

**Comment by amiller-gh** [comment]
Streaming link is here!

https://chime.aws/2026648915

**Comment by codeekage** [comment]
@amiller-gh  add WG members as an invited member to enable us mics

**Comment by chowdhurian** [comment]
https://docs.google.com/presentation/d/1gGwqydeSHa8CsqZW49X9u7AL0BUrxuao-oZXYox2c5k/edit?usp=sharing

**Comment by gtewallace** [comment]
Hi - can someone please grab my computer power cord? I left it in the room we were using for the website discussion. I already left AWS. thank you!!!

**Comment by sagirk** [comment]
@amiller-gh @chowdhurian Did we record the session? Sorry, I missed the live stream.

**Comment by amiller-gh** [comment]
@sagirk We had some technical issues with the room so the recording ended up on my laptop I believe – will try to get it uploaded to YouTube early this week and will post the link here 👍 

Also, just a heads up that the session was a lot of paired exercises, so most of the discussion will likely be at the beginning and end of the video.
