### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by jasnell** [nodejs/summit#9]
What is the schedule for the summit? What time on Thursday are we expecting to get started? 8:00am or 9:00am?

**Comment by Starefossen** [comment]
Mikael posted a schedule in #7

**Comment by jasnell** [comment]
Hmm.. Yes, I see the agenda but, unless I missed it, there are no times attached to anything. Need to have some sense of what time everything is happening.

**Comment by Starefossen** [comment]
From #1

> First session starts at 10am :) We have a few threads in this repo where we're nailing down the agenda for each session. There's no registration other than letting us know in this thread :)

**Comment by jasnell** [comment]
@Starefossen ... sigh... I need more coffee. Thanks! :-)
