### ISSUE TITLE
NodeJS Summit at Brazil?

### ISSUE THREAD

**Issue by renanbastos93** [nodejs/summit#91]
Hey,

Do you will make a conference at Brazil ?

see ya.

**Comment by joyeecheung** [comment]
@renanbastos93 Are you asking about a summit or a conference (I think it's the latter?). This repo is for summits (meetings) that happen around conferences.

**Comment by renanbastos93** [comment]
@joyeecheung,

Do I want know if to have a official event, of NodeJS here at Brazil?

**Comment by benjamingr** [comment]
Maybe someone from @nodejs/nodejs-pt knows? In any case - this repository is for summit events rather than conferences :)

**Comment by renanbastos93** [comment]
Thank's a lot!

Sorry my english is very ungly.

see ya

**Comment by mmarchini** [comment]
@renanbastos93 por enquanto os únicos eventos organizados oficialmente pela Node.js Foundation são JS Interactive (antigo Node.js Interactive) e as reuniões de colaboradores (os Summits).

http://www.nodesummit.com/ e as NodeConfs em geral são organizadas por empresas. Não estou ciente de nenhum evento nesse porte no Brasil (só o BrazilJS, que abrange todo o ecossistema JavaScript). Os eventos de Node.js nesse porte mais próximos do Brasil que eu conheço são https://2018.nodeconf.com.ar/ e https://colombia.nodeconf.com/.

------

@renanbastos93 the only events organized by the Node.js Foundation are JS Interactive (former Node.js Interactive) and the Collaborators Summits.

http://www.nodesummit.com/ and other NodeConfs are usually organized by companies. I'm not aware of any similar conferences in Brazil (besides BrazilJS, which is a JavaScript conference). Some Node.js conferences closer to Brazil are https://2018.nodeconf.com.ar/ and https://colombia.nodeconf.com/.

**Comment by trivikr** [comment]
There's also [Frontinsampa](http://www.frontinsampa.com.br/) which is more of a front-end conference.
I maintain [confs.tech](https://confs.tech/) where you can see more conferences.
