### ISSUE TITLE
Summit Topic: Collaborator effort - CI Fixathon

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/summit#95]
## Motivation

Our CI results are super bad and a green CI became a rare thing instead of being the default. This has two main causes: 1. we have multiple tests that are [flaky](https://github.com/nodejs/node/issues?q=is%3Aissue+is%3Aopen+label%3A%22CI+%2F+flaky+test%22). Some of those might also indeed hide a underlying bug. 2. Our infrastructure is under constant fire and every help in the [build issues](https://github.com/nodejs/build/issues) would be great. That would be great as a short term improvement.

Since we all have different knowledge it would be great to gather a bunch of people all in one room to sit down for 1-2 hours to address these issues in a collaborative way. This is likely not something anyone of us really likes to do but I think it is super important nevertheless. So please volunteer.

Refs: https://github.com/nodejs/node/issues/18660

## Agenda:

1. Identify what tests and issues each one in the group looks into.
2. Work on those and open a pull request to fix them or address infrastructure related things right away if possible.
3. Help out others when finishing a PR / verify fixes.
4. Make a plan how to solve this issue on the long term. Having the CI in the current state makes it super hard for everyone working on Node.js and confuses new people.

**Comment by joyeecheung** [comment]
Do we have available slots for this? cc @mcollina

**Comment by maclover7** [comment]
https://nodejs-ci-health.mmarchini.me/ is a nice way to view failures platform-by-platform, could use help on ones that fail more often than others

**Comment by joyeecheung** [comment]
https://docs.google.com/document/d/1ssi_cnskdjjGouN6yfvby0OuA16fNa8iLd5JPaAa1Ik/edit?usp=sharing

Minutes
