### ISSUE TITLE
Post-mortem: What Did You Achieve at Berlin Collaborator's Summit?

### ISSUE THREAD

**Issue by bnb** [nodejs/summit#97]
I briefly had a discussion with @mcollina yesterday at JSConfEU, discussing how we could begin to capture what worked _well_ for us as individuals at the Collaborator's Summit.

I'd like to try to capture what went well. What did you achieve? What barriers did you overcome? What _happened_ because of the Summit?

**Comment by benjamingr** [comment]
For me, mostly we solved a bunch of issues related to promises in core, lots of good progress in that session. I thought interacting with core was very useful and positive. It was my first summit and it was great to see the Node.js project community is so welcoming and positive.

**Comment by joyeecheung** [comment]
We (@addaleax @apapirovski  @Fishrock123  @hashseed @targos @Trott me etc.) managed to fix a few flakes by sitting together hacking them, before Berlin the CI is 70%-90% red, now it's 50%-60% 
 according to https://nodejs-ci-health.mmarchini.me/#/job-summary (still very red, but better)
